module Anthropic
  module Resources
    class Beta
      class Files
        def list: (
          ?ids: ::Array[String]?,
          ?limit: Integer,
          ?page: String?,
          ?scope_id: String,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::BetaFileMetadata]

        def delete: (
          String file_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaDeletedFile

        def download: (
          String file_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> StringIO

        def retrieve_metadata: (
          String file_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaFileMetadata

        def upload: (
          file: Anthropic::Internal::file_input,
          ?expires_in_seconds: Integer,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaFileMetadata

        def initialize: (client: Anthropic::Client) -> void
      end
    end
  end
end
