module Anthropic
  module Resources
    class Beta
      class UserProfiles
        def create: (
          ?access_type: Anthropic::Models::Beta::UserProfileCreateParams::access_type,
          ?external_id: String?,
          ?external_user_details: Anthropic::Beta::BetaUserProfileExternalUserDetailsParams,
          ?external_user_onboarded_at: Time,
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaUserProfile

        def retrieve: (
          String user_profile_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaUserProfile

        def update: (
          String user_profile_id,
          ?access_type: Anthropic::Models::Beta::UserProfileUpdateParams::access_type?,
          ?external_id: String?,
          ?external_user_details: Anthropic::Beta::BetaUserProfileExternalUserDetailsParams,
          ?external_user_onboarded_at: Time,
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaUserProfile

        def list: (
          ?limit: Integer,
          ?order: Anthropic::Models::Beta::UserProfileListParams::order,
          ?order_by: Anthropic::Models::Beta::UserProfileListParams::order_by,
          ?page: String,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::BetaUserProfile]

        def create_enrollment_url: (
          String user_profile_id,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Beta::BetaUserProfileEnrollmentURL

        def initialize: (client: Anthropic::Client) -> void
      end
    end
  end
end
