//! `string_type_custom("crate::types::FlexStr")`

/// A `ProtoString` backed by [`flexstr::SharedStr`]: short strings inline
/// (no heap), long strings shared via `Arc<str>` so clones are `O(1)`.
///
/// The `buffa::ProtoString` impl, `Deref`/`AsRef`, and the `From`
/// conversions are generated by [`buffa_remote_derive::ProtoString`] — see
/// that crate for the full pattern this collapses. The serde derives stay
/// hand-added: the remote derive covers the binary codec only, and this
/// type needs its own `Serialize`/`Deserialize` because repeated-string
/// elements and map values serialize through the element's serde (see this
/// example's README for the per-newtype JSON table). The other newtypes in this
/// module remain hand-written and show the written-out shape of the
/// pattern; `small_bytes.rs`/`small_vec.rs` stay that way on purpose,
/// because their impls carry allocation behavior the generic derive can't
/// express (`SmallBytes::from_wire` builds straight from the wire slice
/// with no intermediate `Vec`, and `SmallVec`'s `clear` retains capacity
/// where the derive's drops it).
#[derive(
    Clone,
    PartialEq,
    Eq,
    Hash,
    Default,
    Debug,
    serde::Serialize,
    serde::Deserialize,
    buffa_remote_derive::ProtoString,
)]
#[serde(transparent)]
#[buffa(remote = flexstr::SharedStr)]
#[repr(transparent)]
pub struct FlexStr(pub flexstr::SharedStr);
super::assert_transparent!(FlexStr, flexstr::SharedStr);
