module Anthropic
  module Models
    module Beta
      module Organization
        type beta_service_account_workspace_member =
          {
            created_by_actor_id: String?,
            implicit: bool?,
            service_account_id: String,
            type: :service_account_workspace_member,
            workspace_id: String,
            workspace_role: Anthropic::Models::Beta::Organization::beta_workspace_role
          }

        class BetaServiceAccountWorkspaceMember < Anthropic::Internal::Type::BaseModel
          attr_accessor created_by_actor_id: String?

          attr_accessor implicit: bool?

          attr_accessor service_account_id: String

          attr_accessor type: :service_account_workspace_member

          attr_accessor workspace_id: String

          attr_accessor workspace_role: Anthropic::Models::Beta::Organization::beta_workspace_role

          def initialize: (
            created_by_actor_id: String?,
            implicit: bool?,
            service_account_id: String,
            workspace_id: String,
            workspace_role: Anthropic::Models::Beta::Organization::beta_workspace_role,
            ?type: :service_account_workspace_member
          ) -> void

          def to_hash: -> {
            created_by_actor_id: String?,
            implicit: bool?,
            service_account_id: String,
            type: :service_account_workspace_member,
            workspace_id: String,
            workspace_role: Anthropic::Models::Beta::Organization::beta_workspace_role
          }
        end
      end
    end
  end
end
