module Anthropic
  module Models
    module Beta
      module Organization
        type beta_compliance_settings =
          {
            state: Anthropic::Models::Beta::Organization::beta_compliance_settings_state,
            type: :compliance_settings
          }

        class BetaComplianceSettings < Anthropic::Internal::Type::BaseModel
          attr_accessor state: Anthropic::Models::Beta::Organization::beta_compliance_settings_state

          attr_accessor type: :compliance_settings

          def initialize: (
            state: Anthropic::Models::Beta::Organization::beta_compliance_settings_state,
            ?type: :compliance_settings
          ) -> void

          def to_hash: -> {
            state: Anthropic::Models::Beta::Organization::beta_compliance_settings_state,
            type: :compliance_settings
          }
        end
      end
    end
  end
end
