module Anthropic
  module Models
    module Beta
      module Organization
        type beta_workspace_role =
          :workspace_admin
          | :workspace_billing
          | :workspace_developer
          | :workspace_restricted_developer
          | :workspace_user

        module BetaWorkspaceRole
          extend Anthropic::Internal::Type::Enum

          WORKSPACE_ADMIN: :workspace_admin
          WORKSPACE_BILLING: :workspace_billing
          WORKSPACE_DEVELOPER: :workspace_developer
          WORKSPACE_RESTRICTED_DEVELOPER: :workspace_restricted_developer
          WORKSPACE_USER: :workspace_user

          def self?.values: -> ::Array[Anthropic::Models::Beta::Organization::beta_workspace_role]
        end
      end
    end
  end
end
