module Anthropic
  module Models
    module Beta
      module Organization
        type beta_service_account =
          {
            id: String,
            archived_at: Time?,
            archived_by_actor_id: String?,
            created_at: Time,
            created_by_actor_id: String?,
            description: String?,
            name: String,
            organization_role: Anthropic::Models::Beta::Organization::BetaServiceAccount::organization_role,
            type: :service_account,
            updated_at: Time,
            updated_by_actor_id: String?
          }

        class BetaServiceAccount < Anthropic::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor archived_at: Time?

          attr_accessor archived_by_actor_id: String?

          attr_accessor created_at: Time

          attr_accessor created_by_actor_id: String?

          attr_accessor description: String?

          attr_accessor name: String

          attr_accessor organization_role: Anthropic::Models::Beta::Organization::BetaServiceAccount::organization_role

          attr_accessor type: :service_account

          attr_accessor updated_at: Time

          attr_accessor updated_by_actor_id: String?

          def initialize: (
            id: String,
            archived_at: Time?,
            archived_by_actor_id: String?,
            created_at: Time,
            created_by_actor_id: String?,
            description: String?,
            name: String,
            organization_role: Anthropic::Models::Beta::Organization::BetaServiceAccount::organization_role,
            updated_at: Time,
            updated_by_actor_id: String?,
            ?type: :service_account
          ) -> void

          def to_hash: -> {
            id: String,
            archived_at: Time?,
            archived_by_actor_id: String?,
            created_at: Time,
            created_by_actor_id: String?,
            description: String?,
            name: String,
            organization_role: Anthropic::Models::Beta::Organization::BetaServiceAccount::organization_role,
            type: :service_account,
            updated_at: Time,
            updated_by_actor_id: String?
          }

          type organization_role = :admin | :developer

          module OrganizationRole
            extend Anthropic::Internal::Type::Enum

            ADMIN: :admin
            DEVELOPER: :developer

            def self?.values: -> ::Array[Anthropic::Models::Beta::Organization::BetaServiceAccount::organization_role]
          end
        end
      end
    end
  end
end
