module Anthropic
  module Models
    module Beta
      module Organization
        type beta_compliance_settings_state_disabled = { type: :disabled }

        class BetaComplianceSettingsStateDisabled < Anthropic::Internal::Type::BaseModel
          attr_accessor type: :disabled

          def initialize: (?type: :disabled) -> void

          def to_hash: -> { type: :disabled }
        end
      end
    end
  end
end
