module Anthropic
  module Models
    module Beta
      module Organization
        type external_key_list_params =
          { limit: Integer, page: String? }
          & Anthropic::Internal::Type::request_parameters

        class ExternalKeyListParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_accessor page: String?

          def initialize: (
            ?limit: Integer,
            ?page: String?,
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            limit: Integer,
            page: String?,
            request_options: Anthropic::RequestOptions
          }
        end
      end
    end
  end
end
