module Anthropic
  module Models
    module Beta
      module Organization
        type invite_delete_params =
          { invite_id: String } & Anthropic::Internal::Type::request_parameters

        class InviteDeleteParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor invite_id: String

          def initialize: (
            invite_id: String,
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            invite_id: String,
            request_options: Anthropic::RequestOptions
          }
        end
      end
    end
  end
end
