module Anthropic
  module Models
    module Beta
      module Organization
        type service_account_create_params =
          {
            name: String,
            description: String?,
            organization_role: Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role,
            betas: ::Array[Anthropic::Models::anthropic_beta]
          }
          & Anthropic::Internal::Type::request_parameters

        class ServiceAccountCreateParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor name: String

          attr_accessor description: String?

          attr_reader organization_role: Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role?

          def organization_role=: (
            Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role
          ) -> Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          def initialize: (
            name: String,
            ?description: String?,
            ?organization_role: Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            name: String,
            description: String?,
            organization_role: Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            request_options: Anthropic::RequestOptions
          }

          type organization_role = :admin | :developer

          module OrganizationRole
            extend Anthropic::Internal::Type::Enum

            ADMIN: :admin
            DEVELOPER: :developer

            def self?.values: -> ::Array[Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role]
          end
        end
      end
    end
  end
end
