module Anthropic
  module Models
    module Beta
      module Organization
        type workspace_retrieve_params =
          { workspace_id: String }
          & Anthropic::Internal::Type::request_parameters

        class WorkspaceRetrieveParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor workspace_id: String

          def initialize: (
            workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            workspace_id: String,
            request_options: Anthropic::RequestOptions
          }
        end
      end
    end
  end
end
