module Anthropic
  module Resources
    class Beta
      class Organization
        class ServiceAccounts
          attr_reader workspaces: Anthropic::Resources::Beta::Organization::ServiceAccounts::Workspaces

          def create: (
            name: String,
            ?description: String?,
            ?organization_role: Anthropic::Models::Beta::Organization::ServiceAccountCreateParams::organization_role,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Organization::BetaServiceAccount

          def retrieve: (
            String service_account_id,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Organization::BetaServiceAccount

          def update: (
            String service_account_id,
            ?description: String?,
            ?organization_role: Anthropic::Models::Beta::Organization::ServiceAccountUpdateParams::organization_role?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Organization::BetaServiceAccount

          def list: (
            ?include_archived: bool,
            ?limit: Integer,
            ?page: String?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::Organization::BetaServiceAccount]

          def archive: (
            String service_account_id,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Organization::BetaServiceAccount

          def initialize: (client: Anthropic::Client) -> void
        end
      end
    end
  end
end
