package com.anthropic.models.beta.messages

import com.anthropic.core.JsonField
import com.anthropic.core.JsonSchemaLocalValidation
import com.anthropic.core.JsonValue
import com.anthropic.core.betaOutputFormatFromClass
import com.anthropic.core.checkRequired
import java.util.Objects
import java.util.Optional

/**
 * A wrapper for [BetaOutputConfig] that provides a type-safe [Builder] that can record the
 * [outputType] used to derive a JSON schema for the output format when using the _Structured
 * Outputs_ feature. Unlike passing only the output type to
 * [MessageCreateParams.Builder.outputConfig], this allows the other output configuration options
 * (such as the effort level) to be set alongside the output type. See the SDK documentation for
 * more details on _Structured Outputs_.
 *
 * @param T The type of the class that will be used to derive the JSON schema in the request and to
 *   which the JSON response will be deserialized.
 */
class StructuredOutputConfig<T : Any>
private constructor(
    @get:JvmName("outputType") val outputType: Class<T>,
    /** The raw, underlying output configuration wrapped by this structured instance. */
    @get:JvmName("rawOutputConfig") val rawOutputConfig: BetaOutputConfig,
) {

    fun toBuilder() = Builder<T>().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [StructuredOutputConfig].
         *
         * The following fields are required:
         * ```java
         * .format()
         * ```
         */
        @JvmStatic fun <T : Any> builder() = Builder<T>()
    }

    /** A builder for [StructuredOutputConfig]. */
    class Builder<T : Any> internal constructor() {

        private var outputType: Class<T>? = null
        private var outputConfigBuilder = BetaOutputConfig.builder()

        /** Injects a given `BetaOutputConfig.Builder`. For use only when testing. */
        @JvmSynthetic
        internal fun inject(outputConfigBuilder: BetaOutputConfig.Builder) = apply {
            this.outputConfigBuilder = outputConfigBuilder
        }

        @JvmSynthetic
        internal fun from(structuredOutputConfig: StructuredOutputConfig<T>) = apply {
            outputType = structuredOutputConfig.outputType
            outputConfigBuilder = structuredOutputConfig.rawOutputConfig.toBuilder()
        }

        /** @see BetaOutputConfig.Builder.effort */
        fun effort(effort: BetaOutputConfig.Effort?) = apply { outputConfigBuilder.effort(effort) }

        /** @see BetaOutputConfig.Builder.effort */
        fun effort(effort: Optional<BetaOutputConfig.Effort>) = apply {
            outputConfigBuilder.effort(effort)
        }

        /** @see BetaOutputConfig.Builder.effort */
        fun effort(effort: JsonField<BetaOutputConfig.Effort>) = apply {
            outputConfigBuilder.effort(effort)
        }

        /**
         * Sets the output format to a JSON schema derived from the structure of the given class.
         *
         * @param outputType The class from which the JSON schema will be derived.
         * @param localValidation [JsonSchemaLocalValidation.YES] (the default) to validate the JSON
         *   schema locally when it is generated by this method to confirm that it adheres to the
         *   requirements and restrictions on JSON schemas imposed by the Anthropic specification;
         *   or [JsonSchemaLocalValidation.NO] to skip local validation and rely only on remote
         *   validation. See the SDK documentation for more details.
         * @throws IllegalArgumentException If local validation is enabled, but it fails because a
         *   valid JSON schema cannot be derived from the given class; or if the given class is a
         *   non-static inner class, a local class or an anonymous class. The kind of class is
         *   checked even when [localValidation] is [JsonSchemaLocalValidation.NO].
         * @see BetaOutputConfig.Builder.format
         */
        @JvmOverloads
        fun format(
            outputType: Class<T>,
            localValidation: JsonSchemaLocalValidation = JsonSchemaLocalValidation.YES,
        ) = apply {
            this.outputType = outputType
            outputConfigBuilder.format(betaOutputFormatFromClass(outputType, localValidation))
        }

        /** @see BetaOutputConfig.Builder.taskBudget */
        fun taskBudget(taskBudget: BetaTokenTaskBudget?) = apply {
            outputConfigBuilder.taskBudget(taskBudget)
        }

        /** @see BetaOutputConfig.Builder.taskBudget */
        fun taskBudget(taskBudget: Optional<BetaTokenTaskBudget>) = apply {
            outputConfigBuilder.taskBudget(taskBudget)
        }

        /** @see BetaOutputConfig.Builder.taskBudget */
        fun taskBudget(taskBudget: JsonField<BetaTokenTaskBudget>) = apply {
            outputConfigBuilder.taskBudget(taskBudget)
        }

        /** @see BetaOutputConfig.Builder.additionalProperties */
        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            outputConfigBuilder.additionalProperties(additionalProperties)
        }

        /** @see BetaOutputConfig.Builder.putAdditionalProperty */
        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            outputConfigBuilder.putAdditionalProperty(key, value)
        }

        /** @see BetaOutputConfig.Builder.putAllAdditionalProperties */
        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            outputConfigBuilder.putAllAdditionalProperties(additionalProperties)
        }

        /** @see BetaOutputConfig.Builder.removeAdditionalProperty */
        fun removeAdditionalProperty(key: String) = apply {
            outputConfigBuilder.removeAdditionalProperty(key)
        }

        /** @see BetaOutputConfig.Builder.removeAllAdditionalProperties */
        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            outputConfigBuilder.removeAllAdditionalProperties(keys)
        }

        /**
         * Returns an immutable instance of [StructuredOutputConfig].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```java
         * .format()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): StructuredOutputConfig<T> =
            StructuredOutputConfig(checkRequired("format", outputType), outputConfigBuilder.build())
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is StructuredOutputConfig<*> &&
            outputType == other.outputType &&
            rawOutputConfig == other.rawOutputConfig
    }

    override fun hashCode(): Int = Objects.hash(outputType, rawOutputConfig)

    override fun toString() =
        "${javaClass.simpleName}{outputType=$outputType, rawOutputConfig=$rawOutputConfig}"
}
