module Anthropic
  module Models
    module Beta
      module Environments
        type work_list_params =
          {
            environment_id: String,
            limit: Integer,
            page: String?,
            betas: ::Array[Anthropic::Models::anthropic_beta]
          }
          & Anthropic::Internal::Type::request_parameters

        class WorkListParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor environment_id: String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_accessor page: String?

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          def initialize: (
            environment_id: String,
            ?limit: Integer,
            ?page: String?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            environment_id: String,
            limit: Integer,
            page: String?,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            request_options: Anthropic::RequestOptions
          }
        end
      end
    end
  end
end
