# typed: strong

module Anthropic
  module Models
    BetaMessage = Beta::BetaMessage

    module Beta
      class BetaMessage < Anthropic::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(Anthropic::Beta::BetaMessage, Anthropic::Internal::AnyHash)
          end

        # Unique object identifier.
        #
        # The format and length of IDs may change over time.
        sig { returns(String) }
        attr_accessor :id

        # Information about the container used in the request (for the code execution
        # tool)
        sig { returns(T.nilable(Anthropic::Beta::BetaContainer)) }
        attr_reader :container

        sig do
          params(
            container: T.nilable(Anthropic::Beta::BetaContainer::OrHash)
          ).void
        end
        attr_writer :container

        sig { returns(T.nilable(T.anything)) }
        def parsed_output
        end

        # Content generated by the model.
        #
        # This is an array of content blocks, each of which has a `type` that determines
        # its shape.
        #
        # Example:
        #
        # ```json
        # [{ "type": "text", "text": "Hi, I'm Claude." }]
        # ```
        #
        # If the request input `messages` ended with an `assistant` turn, then the
        # response `content` will continue directly from that last turn. You can use this
        # to constrain the model's output.
        #
        # For example, if the input `messages` were:
        #
        # ```json
        # [
        #   {
        #     "role": "user",
        #     "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"
        #   },
        #   { "role": "assistant", "content": "The best answer is (" }
        # ]
        # ```
        #
        # Then the response `content` might be:
        #
        # ```json
        # [{ "type": "text", "text": "B)" }]
        # ```
        sig { returns(T::Array[Anthropic::Beta::BetaContentBlock::Variants]) }
        attr_accessor :content

        # Context management response.
        #
        # Information about context management strategies applied during the request.
        sig do
          returns(T.nilable(Anthropic::Beta::BetaContextManagementResponse))
        end
        attr_reader :context_management

        sig do
          params(
            context_management:
              T.nilable(Anthropic::Beta::BetaContextManagementResponse::OrHash)
          ).void
        end
        attr_writer :context_management

        # Request-level diagnostics: why the prompt cache could not fully reuse the prefix
        # of the request named by `diagnostics.previous_message_id`.
        sig { returns(T.nilable(Anthropic::Beta::BetaDiagnostics)) }
        attr_reader :diagnostics

        sig do
          params(
            diagnostics: T.nilable(Anthropic::Beta::BetaDiagnostics::OrHash)
          ).void
        end
        attr_writer :diagnostics

        # The model that will complete your prompt.
        #
        # See [models](https://docs.anthropic.com/en/docs/models-overview) for additional
        # details and options.
        sig { returns(Anthropic::Model::Variants) }
        attr_accessor :model

        # Conversational role of the generated message.
        #
        # This will always be `"assistant"`.
        sig { returns(Symbol) }
        attr_accessor :role

        # Structured information about a refusal.
        sig { returns(T.nilable(Anthropic::Beta::BetaRefusalStopDetails)) }
        attr_reader :stop_details

        sig do
          params(
            stop_details:
              T.nilable(Anthropic::Beta::BetaRefusalStopDetails::OrHash)
          ).void
        end
        attr_writer :stop_details

        # The reason that we stopped.
        #
        # This may be one the following values:
        #
        # - `"end_turn"`: the model reached a natural stopping point
        # - `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
        # - `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
        # - `"tool_use"`: the model invoked one or more tools
        # - `"pause_turn"`: we paused a long-running turn. You may provide the response
        #   back as-is in a subsequent request to let the model continue.
        # - `"refusal"`: when streaming classifiers intervene to handle potential policy
        #   violations
        # - `"model_context_window_exceeded"`: we exceeded the model's context window
        #
        # In non-streaming mode this value is always non-null. In streaming mode, it is
        # null in the `message_start` event and non-null otherwise.
        sig do
          returns(T.nilable(Anthropic::Beta::BetaStopReason::TaggedSymbol))
        end
        attr_accessor :stop_reason

        # Which custom stop sequence was generated, if any.
        #
        # This value will be a non-null string if one of your custom stop sequences was
        # generated.
        sig { returns(T.nilable(String)) }
        attr_accessor :stop_sequence

        # Object type.
        #
        # For Messages, this is always `"message"`.
        sig { returns(Symbol) }
        attr_accessor :type

        # Billing and rate-limit usage.
        #
        # Anthropic's API bills and rate-limits by token counts, as tokens represent the
        # underlying cost to our systems.
        #
        # Under the hood, the API transforms requests into a format suitable for the
        # model. The model's output then goes through a parsing stage before becoming an
        # API response. As a result, the token counts in `usage` will not match one-to-one
        # with the exact visible content of an API request or response.
        #
        # For example, `output_tokens` will be non-zero, even for an empty string response
        # from Claude.
        #
        # Total input tokens in a request is the summation of `input_tokens`,
        # `cache_creation_input_tokens`, and `cache_read_input_tokens`.
        sig { returns(Anthropic::Beta::BetaUsage) }
        attr_reader :usage

        sig { params(usage: Anthropic::Beta::BetaUsage::OrHash).void }
        attr_writer :usage

        # Changes the API made to the request's input before showing it to the model, and
        # blocks that failed a binding check but were left unchanged: one entry per block,
        # in request order. Two entry types today. `thinking_dropped` — a `thinking`,
        # `redacted_thinking` or `connector_text` block from the request's `messages` that
        # was removed from the prompt instead of being shown to the model because it
        # failed a binding check. `thinking_mismatch_allowed` — a `thinking` or
        # `redacted_thinking` block that failed the conversation check (the conversation
        # before it differs from the one it was created in, or it carries no record of one
        # on a model that requires it) and was shown to the model all the same, because
        # that check is not enforced for this request. More entry types may be added over
        # time; ignore types you do not recognize.
        #
        # Requires `anthropic-beta: thinking-binding-controls-2026-08-01`. Present on
        # every such response from a model that supports extended thinking, as `[]` when
        # there is no entry to report; without the beta, blocks are removed or left in
        # place all the same but nothing is reported. Removed blocks contribute nothing to
        # `usage.input_tokens`; blocks left in place count as sent. When streaming, the
        # array is final in `message_start`; the final `message_delta` event carries it
        # only when a server-side model fallback happened mid-stream, in which case it
        # holds the serving model's entries and replaces the one in `message_start`.
        sig do
          returns(
            T.nilable(
              T::Array[Anthropic::Beta::BetaInputTransformation::Variants]
            )
          )
        end
        attr_accessor :input_transformations

        sig do
          params(
            id: String,
            container: T.nilable(Anthropic::Beta::BetaContainer::OrHash),
            content:
              T::Array[
                T.any(
                  Anthropic::Beta::BetaTextBlock::OrHash,
                  Anthropic::Beta::BetaThinkingBlock::OrHash,
                  Anthropic::Beta::BetaRedactedThinkingBlock::OrHash,
                  Anthropic::Beta::BetaToolUseBlock::OrHash,
                  Anthropic::Beta::BetaServerToolUseBlock::OrHash,
                  Anthropic::Beta::BetaWebSearchToolResultBlock::OrHash,
                  Anthropic::Beta::BetaWebFetchToolResultBlock::OrHash,
                  Anthropic::Beta::BetaAdvisorToolResultBlock::OrHash,
                  Anthropic::Beta::BetaCodeExecutionToolResultBlock::OrHash,
                  Anthropic::Beta::BetaBashCodeExecutionToolResultBlock::OrHash,
                  Anthropic::Beta::BetaTextEditorCodeExecutionToolResultBlock::OrHash,
                  Anthropic::Beta::BetaToolSearchToolResultBlock::OrHash,
                  Anthropic::Beta::BetaMCPToolUseBlock::OrHash,
                  Anthropic::Beta::BetaMCPToolResultBlock::OrHash,
                  Anthropic::Beta::BetaContainerUploadBlock::OrHash,
                  Anthropic::Beta::BetaCompactionBlock::OrHash,
                  Anthropic::Beta::BetaFallbackBlock::OrHash,
                  Anthropic::Beta::BetaMCPToolListingBlock::OrHash
                )
              ],
            context_management:
              T.nilable(Anthropic::Beta::BetaContextManagementResponse::OrHash),
            diagnostics: T.nilable(Anthropic::Beta::BetaDiagnostics::OrHash),
            model: T.any(Anthropic::Model::OrSymbol, String),
            stop_details:
              T.nilable(Anthropic::Beta::BetaRefusalStopDetails::OrHash),
            stop_reason: T.nilable(Anthropic::Beta::BetaStopReason::OrSymbol),
            stop_sequence: T.nilable(String),
            usage: Anthropic::Beta::BetaUsage::OrHash,
            input_transformations:
              T.nilable(
                T::Array[
                  T.any(
                    Anthropic::Beta::BetaThinkingDroppedInputTransformation::OrHash,
                    Anthropic::Beta::BetaThinkingMismatchAllowedInputTransformation::OrHash
                  )
                ]
              ),
            role: Symbol,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # Unique object identifier.
          #
          # The format and length of IDs may change over time.
          id:,
          # Information about the container used in the request (for the code execution
          # tool)
          container:,
          # Content generated by the model.
          #
          # This is an array of content blocks, each of which has a `type` that determines
          # its shape.
          #
          # Example:
          #
          # ```json
          # [{ "type": "text", "text": "Hi, I'm Claude." }]
          # ```
          #
          # If the request input `messages` ended with an `assistant` turn, then the
          # response `content` will continue directly from that last turn. You can use this
          # to constrain the model's output.
          #
          # For example, if the input `messages` were:
          #
          # ```json
          # [
          #   {
          #     "role": "user",
          #     "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"
          #   },
          #   { "role": "assistant", "content": "The best answer is (" }
          # ]
          # ```
          #
          # Then the response `content` might be:
          #
          # ```json
          # [{ "type": "text", "text": "B)" }]
          # ```
          content:,
          # Context management response.
          #
          # Information about context management strategies applied during the request.
          context_management:,
          # Request-level diagnostics: why the prompt cache could not fully reuse the prefix
          # of the request named by `diagnostics.previous_message_id`.
          diagnostics:,
          # The model that will complete your prompt.
          #
          # See [models](https://docs.anthropic.com/en/docs/models-overview) for additional
          # details and options.
          model:,
          # Structured information about a refusal.
          stop_details:,
          # The reason that we stopped.
          #
          # This may be one the following values:
          #
          # - `"end_turn"`: the model reached a natural stopping point
          # - `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
          # - `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
          # - `"tool_use"`: the model invoked one or more tools
          # - `"pause_turn"`: we paused a long-running turn. You may provide the response
          #   back as-is in a subsequent request to let the model continue.
          # - `"refusal"`: when streaming classifiers intervene to handle potential policy
          #   violations
          # - `"model_context_window_exceeded"`: we exceeded the model's context window
          #
          # In non-streaming mode this value is always non-null. In streaming mode, it is
          # null in the `message_start` event and non-null otherwise.
          stop_reason:,
          # Which custom stop sequence was generated, if any.
          #
          # This value will be a non-null string if one of your custom stop sequences was
          # generated.
          stop_sequence:,
          # Billing and rate-limit usage.
          #
          # Anthropic's API bills and rate-limits by token counts, as tokens represent the
          # underlying cost to our systems.
          #
          # Under the hood, the API transforms requests into a format suitable for the
          # model. The model's output then goes through a parsing stage before becoming an
          # API response. As a result, the token counts in `usage` will not match one-to-one
          # with the exact visible content of an API request or response.
          #
          # For example, `output_tokens` will be non-zero, even for an empty string response
          # from Claude.
          #
          # Total input tokens in a request is the summation of `input_tokens`,
          # `cache_creation_input_tokens`, and `cache_read_input_tokens`.
          usage:,
          # Changes the API made to the request's input before showing it to the model, and
          # blocks that failed a binding check but were left unchanged: one entry per block,
          # in request order. Two entry types today. `thinking_dropped` — a `thinking`,
          # `redacted_thinking` or `connector_text` block from the request's `messages` that
          # was removed from the prompt instead of being shown to the model because it
          # failed a binding check. `thinking_mismatch_allowed` — a `thinking` or
          # `redacted_thinking` block that failed the conversation check (the conversation
          # before it differs from the one it was created in, or it carries no record of one
          # on a model that requires it) and was shown to the model all the same, because
          # that check is not enforced for this request. More entry types may be added over
          # time; ignore types you do not recognize.
          #
          # Requires `anthropic-beta: thinking-binding-controls-2026-08-01`. Present on
          # every such response from a model that supports extended thinking, as `[]` when
          # there is no entry to report; without the beta, blocks are removed or left in
          # place all the same but nothing is reported. Removed blocks contribute nothing to
          # `usage.input_tokens`; blocks left in place count as sent. When streaming, the
          # array is final in `message_start`; the final `message_delta` event carries it
          # only when a server-side model fallback happened mid-stream, in which case it
          # holds the serving model's entries and replaces the one in `message_start`.
          input_transformations: nil,
          # Conversational role of the generated message.
          #
          # This will always be `"assistant"`.
          role: :assistant,
          # Object type.
          #
          # For Messages, this is always `"message"`.
          type: :message
        )
        end

        sig do
          override.returns(
            {
              id: String,
              container: T.nilable(Anthropic::Beta::BetaContainer),
              content: T::Array[Anthropic::Beta::BetaContentBlock::Variants],
              context_management:
                T.nilable(Anthropic::Beta::BetaContextManagementResponse),
              diagnostics: T.nilable(Anthropic::Beta::BetaDiagnostics),
              model: Anthropic::Model::Variants,
              role: Symbol,
              stop_details: T.nilable(Anthropic::Beta::BetaRefusalStopDetails),
              stop_reason:
                T.nilable(Anthropic::Beta::BetaStopReason::TaggedSymbol),
              stop_sequence: T.nilable(String),
              type: Symbol,
              usage: Anthropic::Beta::BetaUsage,
              input_transformations:
                T.nilable(
                  T::Array[Anthropic::Beta::BetaInputTransformation::Variants]
                )
            }
          )
        end
        def to_hash
        end
      end
    end
  end
end
