# typed: strong

module Anthropic
  module Models
    BetaThinkingBlock = Beta::BetaThinkingBlock

    module Beta
      class BetaThinkingBlock < Anthropic::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              Anthropic::Beta::BetaThinkingBlock,
              Anthropic::Internal::AnyHash
            )
          end

        # A value used to verify that this thinking block was generated by Claude when it
        # is passed back to the API.
        #
        # This is an opaque field and should not be interpreted or parsed. When passing
        # thinking blocks back to the API (required when using tools with extended
        # thinking), pass them back exactly as received, with this field intact.
        #
        # See
        # [extended thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking)
        # for details.
        sig { returns(String) }
        attr_accessor :signature

        # The text of Claude's thinking process for this block.
        sig { returns(String) }
        attr_accessor :thinking

        sig { returns(Symbol) }
        attr_accessor :type

        sig do
          params(signature: String, thinking: String, type: Symbol).returns(
            T.attached_class
          )
        end
        def self.new(
          # A value used to verify that this thinking block was generated by Claude when it
          # is passed back to the API.
          #
          # This is an opaque field and should not be interpreted or parsed. When passing
          # thinking blocks back to the API (required when using tools with extended
          # thinking), pass them back exactly as received, with this field intact.
          #
          # See
          # [extended thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking)
          # for details.
          signature:,
          # The text of Claude's thinking process for this block.
          thinking:,
          type: :thinking
        )
        end

        sig do
          override.returns(
            { signature: String, thinking: String, type: Symbol }
          )
        end
        def to_hash
        end
      end
    end
  end
end
