# typed: strong

module Anthropic
  module Models
    BetaRawContentBlockDelta = Beta::BetaRawContentBlockDelta

    module Beta
      module BetaRawContentBlockDelta
        extend Anthropic::Internal::Type::Union

        Variants =
          T.type_alias do
            T.any(
              Anthropic::Beta::BetaTextDelta,
              Anthropic::Beta::BetaInputJSONDelta,
              Anthropic::Beta::BetaCitationsDelta,
              Anthropic::Beta::BetaThinkingDelta,
              Anthropic::Beta::BetaSignatureDelta,
              Anthropic::Beta::BetaCompactionContentBlockDelta
            )
          end

        module Type
          extend Anthropic::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, Anthropic::Beta::BetaRawContentBlockDelta::Type)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          TEXT_DELTA =
            T.let(
              :text_delta,
              Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
            )
          INPUT_JSON_DELTA =
            T.let(
              :input_json_delta,
              Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
            )
          CITATIONS_DELTA =
            T.let(
              :citations_delta,
              Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
            )
          THINKING_DELTA =
            T.let(
              :thinking_delta,
              Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
            )
          SIGNATURE_DELTA =
            T.let(
              :signature_delta,
              Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
            )
          COMPACTION_DELTA =
            T.let(
              :compaction_delta,
              Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                Anthropic::Beta::BetaRawContentBlockDelta::Type::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        sig do
          override.returns(
            T::Array[Anthropic::Beta::BetaRawContentBlockDelta::Variants]
          )
        end
        def self.variants
        end

        # Creates a new instance of the variant class whose `type` matches the given
        # value, passing the remaining arguments to its constructor.
        sig do
          params(
            type: Anthropic::Beta::BetaRawContentBlockDelta::Type::OrSymbol,
            text: String,
            partial_json: String,
            citation:
              T.any(
                Anthropic::Beta::BetaCitationCharLocation::OrHash,
                Anthropic::Beta::BetaCitationPageLocation::OrHash,
                Anthropic::Beta::BetaCitationContentBlockLocation::OrHash,
                Anthropic::Beta::BetaCitationsWebSearchResultLocation::OrHash,
                Anthropic::Beta::BetaCitationSearchResultLocation::OrHash
              ),
            estimated_tokens: T.nilable(Integer),
            thinking: String,
            signature: String,
            content: T.nilable(String),
            encrypted_content: T.nilable(String)
          ).returns(Anthropic::Beta::BetaRawContentBlockDelta::Variants)
        end
        def self.new(
          type:,
          text: nil,
          partial_json: nil,
          citation: nil,
          # Per-frame increment of a coarse, running estimate of the tokens this thinking
          # block has produced so far. Present whenever the
          # `thinking-token-count-2026-05-13` beta is set; `null` unless `thinking.display`
          # resolves to `"omitted"` and a count is due this frame. Sum the increments across
          # `thinking_delta` frames on this block for a progress indicator. Each increment
          # is a non-negative multiple of a fixed quantum and the cadence is rate-limited,
          # so this is a deliberately lossy display hint, not a billable count;
          # `usage.output_tokens` remains authoritative.
          estimated_tokens: nil,
          # The incremental `thinking` text for this content block. Concatenate the
          # `thinking` values of successive `thinking_delta` events to assemble the block's
          # full `thinking` value.
          thinking: nil,
          # The `signature` for this thinking block: an opaque value used to verify that the
          # block was generated by Claude when it is passed back to the API. Delivered in a
          # `signature_delta` event just before the block's `content_block_stop` event.
          signature: nil,
          content: nil,
          # Opaque metadata from prior compaction, to be round-tripped verbatim
          encrypted_content: nil
        )
        end
      end
    end
  end
end
