module Anthropic
  module Models
    module Beta
      module Organization
        module Federation
          type beta_jwks_inline =
            { keys: ::Array[::Hash[Symbol, top]], type: :inline }

          class BetaJWKSInline < Anthropic::Internal::Type::BaseModel
            attr_accessor keys: ::Array[::Hash[Symbol, top]]

            attr_accessor type: :inline

            def initialize: (
              keys: ::Array[::Hash[Symbol, top]],
              ?type: :inline
            ) -> void

            def to_hash: -> {
              keys: ::Array[::Hash[Symbol, top]],
              type: :inline
            }
          end
        end
      end
    end
  end
end
