module Anthropic
  module Models
    module Beta
      module Organization
        module Federation
          type rule_create_params =
            {
              issuer_id: String,
              match: Anthropic::Beta::Organization::Federation::BetaFederationRuleMatch,
              name: String,
              oauth_scope: String,
              target: Anthropic::Beta::Organization::Federation::BetaServiceAccountTarget,
              applies_to_all_workspaces: bool,
              attributes: ::Hash[Symbol, String]?,
              description: String?,
              token_lifetime_seconds: Integer,
              workspace_id: String?,
              betas: ::Array[Anthropic::Models::anthropic_beta]
            }
            & Anthropic::Internal::Type::request_parameters

          class RuleCreateParams < Anthropic::Internal::Type::BaseModel
            extend Anthropic::Internal::Type::RequestParameters::Converter
            include Anthropic::Internal::Type::RequestParameters

            attr_accessor issuer_id: String

            attr_accessor match: Anthropic::Beta::Organization::Federation::BetaFederationRuleMatch

            attr_accessor name: String

            attr_accessor oauth_scope: String

            attr_accessor target: Anthropic::Beta::Organization::Federation::BetaServiceAccountTarget

            attr_reader applies_to_all_workspaces: bool?

            def applies_to_all_workspaces=: (bool) -> bool

            attr_accessor attributes: ::Hash[Symbol, String]?

            attr_accessor description: String?

            attr_reader token_lifetime_seconds: Integer?

            def token_lifetime_seconds=: (Integer) -> Integer

            attr_accessor workspace_id: String?

            attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

            def betas=: (
              ::Array[Anthropic::Models::anthropic_beta]
            ) -> ::Array[Anthropic::Models::anthropic_beta]

            def initialize: (
              issuer_id: String,
              match: Anthropic::Beta::Organization::Federation::BetaFederationRuleMatch,
              name: String,
              oauth_scope: String,
              target: Anthropic::Beta::Organization::Federation::BetaServiceAccountTarget,
              ?applies_to_all_workspaces: bool,
              ?attributes: ::Hash[Symbol, String]?,
              ?description: String?,
              ?token_lifetime_seconds: Integer,
              ?workspace_id: String?,
              ?betas: ::Array[Anthropic::Models::anthropic_beta],
              ?request_options: Anthropic::request_opts
            ) -> void

            def to_hash: -> {
              issuer_id: String,
              match: Anthropic::Beta::Organization::Federation::BetaFederationRuleMatch,
              name: String,
              oauth_scope: String,
              target: Anthropic::Beta::Organization::Federation::BetaServiceAccountTarget,
              applies_to_all_workspaces: bool,
              attributes: ::Hash[Symbol, String]?,
              description: String?,
              token_lifetime_seconds: Integer,
              workspace_id: String?,
              betas: ::Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::RequestOptions
            }
          end
        end
      end
    end
  end
end
