module Anthropic
  module Resources
    class Beta
      class Skills
        class Versions
          def create: (
            String skill_id,
            files: ::Array[Anthropic::Internal::file_input],
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Skills::BetaSkillVersion

          def retrieve: (
            String version,
            skill_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Skills::BetaSkillVersion

          def list: (
            String skill_id,
            ?limit: Integer?,
            ?page: String?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::Skills::BetaSkillVersion]

          def delete: (
            String version,
            skill_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Skills::BetaDeletedSkillVersion

          def download: (
            String version,
            skill_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> StringIO

          def initialize: (client: Anthropic::Client) -> void
        end
      end
    end
  end
end
