# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.35.0"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "c0284fbbbaed8c4f2f4c53479f0b36530bad7c146434a0bf08cb3002779d465a"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "39cabc03346a84ee8ca7da2a754f4f0b1dd31cf86848a65fdcda7066955982ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "a861a51f62f70f5f6a136dddffc9fe4d9708807a25a24595ce9d640d88361308"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "5e53cb7953a8f92fd5cee47960d520765a532f2bafa7c9ff4c4312045d1f6265"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
