# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      class BetaSignatureDelta < Anthropic::Internal::Type::BaseModel
        # @!attribute signature
        #   The `signature` for this thinking block: an opaque value used to verify that the
        #   block was generated by Claude when it is passed back to the API. Delivered in a
        #   `signature_delta` event just before the block's `content_block_stop` event.
        #
        #   @return [String]
        required :signature, String

        # @!attribute type
        #
        #   @return [Symbol, :signature_delta]
        required :type, const: :signature_delta

        # @!method initialize(signature:, type: :signature_delta)
        #   Some parameter documentations has been truncated, see
        #   {Anthropic::Models::Beta::BetaSignatureDelta} for more details.
        #
        #   @param signature [String] The `signature` for this thinking block: an opaque value used to verify that the
        #
        #   @param type [Symbol, :signature_delta]
      end
    end

    BetaSignatureDelta = Beta::BetaSignatureDelta
  end
end
