# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      class BetaThinkingBlock < Anthropic::Internal::Type::BaseModel
        # @!attribute signature
        #   A value used to verify that this thinking block was generated by Claude when it
        #   is passed back to the API.
        #
        #   This is an opaque field and should not be interpreted or parsed. When passing
        #   thinking blocks back to the API (required when using tools with extended
        #   thinking), pass them back exactly as received, with this field intact.
        #
        #   See
        #   [extended thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking)
        #   for details.
        #
        #   @return [String]
        required :signature, String

        # @!attribute thinking
        #   The text of Claude's thinking process for this block.
        #
        #   @return [String]
        required :thinking, String

        # @!attribute type
        #
        #   @return [Symbol, :thinking]
        required :type, const: :thinking

        # @!method initialize(signature:, thinking:, type: :thinking)
        #   Some parameter documentations has been truncated, see
        #   {Anthropic::Models::Beta::BetaThinkingBlock} for more details.
        #
        #   @param signature [String] A value used to verify that this thinking block was generated by Claude when it
        #
        #   @param thinking [String] The text of Claude's thinking process for this block.
        #
        #   @param type [Symbol, :thinking]
      end
    end

    BetaThinkingBlock = Beta::BetaThinkingBlock
  end
end
