# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      class BetaServerToolUseBlockParam < Anthropic::Internal::Type::BaseModel
        # @!attribute id
        #
        #   @return [String]
        required :id, String

        # @!attribute input
        #
        #   @return [Hash{Symbol=>Object}]
        required :input, Anthropic::Internal::Type::HashOf[Anthropic::Internal::Type::Unknown]

        # @!attribute name
        #
        #   @return [Symbol, Anthropic::Models::Beta::BetaServerToolUseBlockParam::Name]
        required :name, enum: -> { Anthropic::Beta::BetaServerToolUseBlockParam::Name }

        # @!attribute type
        #
        #   @return [Symbol, :server_tool_use]
        required :type, const: :server_tool_use

        # @!attribute cache_control
        #   Create a cache control breakpoint at this content block.
        #
        #   @return [Anthropic::Models::Beta::BetaCacheControlEphemeral, nil]
        optional :cache_control, -> { Anthropic::Beta::BetaCacheControlEphemeral }, nil?: true

        # @!attribute caller_
        #
        #   @return [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120, nil]
        optional :caller_,
                 union: -> {
                   Anthropic::Beta::BetaServerToolUseBlockParam::Caller
                 },
                 api_name: :caller

        # @!method initialize(id:, input:, name:, cache_control: nil, caller_: nil, type: :server_tool_use)
        #   @param id [String]
        #
        #   @param input [Hash{Symbol=>Object}]
        #
        #   @param name [Symbol, Anthropic::Models::Beta::BetaServerToolUseBlockParam::Name]
        #
        #   @param cache_control [Anthropic::Models::Beta::BetaCacheControlEphemeral, nil] Create a cache control breakpoint at this content block.
        #
        #   @param caller_ [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120]
        #
        #   @param type [Symbol, :server_tool_use]

        # @see Anthropic::Models::Beta::BetaServerToolUseBlockParam#name
        module Name
          extend Anthropic::Internal::Type::Enum

          ADVISOR = :advisor
          WEB_SEARCH = :web_search
          WEB_FETCH = :web_fetch
          CODE_EXECUTION = :code_execution
          BASH_CODE_EXECUTION = :bash_code_execution
          TEXT_EDITOR_CODE_EXECUTION = :text_editor_code_execution
          TOOL_SEARCH_TOOL_REGEX = :tool_search_tool_regex
          TOOL_SEARCH_TOOL_BM25 = :tool_search_tool_bm25

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see Anthropic::Models::Beta::BetaServerToolUseBlockParam#caller_
        module Caller
          extend Anthropic::Internal::Type::Union

          discriminator :type

          # Tool invocation directly from the model.
          variant :direct, -> { Anthropic::Beta::BetaDirectCaller }

          # Tool invocation generated by a server-side tool.
          variant :code_execution_20250825, -> { Anthropic::Beta::BetaServerToolCaller }

          variant :code_execution_20260120, -> { Anthropic::Beta::BetaServerToolCaller20260120 }

          module Type
            extend Anthropic::Internal::Type::Enum

            DIRECT = :direct
            CODE_EXECUTION_20250825 = :code_execution_20250825
            CODE_EXECUTION_20260120 = :code_execution_20260120

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @!method self.variants
          #   @return [Array(Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120)]

          # Creates a new instance of the variant class whose `type` matches the given
          # value, passing the remaining arguments to its constructor.
          #
          # @param type [Symbol, Anthropic::Models::Beta::BetaServerToolUseBlockParam::Caller::Type, String]
          #
          # @param args [Hash{Symbol=>Object}] Attributes for the chosen variant.
          #
          #   @option args [String] :tool_id
          #
          # @raise [ArgumentError]
          # @return [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120]
          def self.new(type:, **args)
            case type.to_sym
            when :direct
              Anthropic::Beta::BetaDirectCaller.new(**args)
            when :code_execution_20250825
              Anthropic::Beta::BetaServerToolCaller.new(**args)
            when :code_execution_20260120
              Anthropic::Beta::BetaServerToolCaller20260120.new(**args)
            else
              raise ArgumentError, "unknown type: #{type}"
            end
          end
        end
      end
    end

    BetaServerToolUseBlockParam = Beta::BetaServerToolUseBlockParam
  end
end
