# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      class BetaToolUseBlock < Anthropic::Internal::Type::BaseModel
        # @!attribute id
        #
        #   @return [String]
        required :id, String

        # @!attribute input
        #
        #   @return [Object]
        required :input, Anthropic::Internal::Type::Unknown

        # @!attribute name
        #
        #   @return [String]
        required :name, String

        # @!attribute type
        #
        #   @return [Symbol, :tool_use]
        required :type, const: :tool_use

        # @!attribute caller_
        #
        #   @return [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120, nil]
        optional :caller_, union: -> { Anthropic::Beta::BetaToolUseBlock::Caller }, api_name: :caller

        # @!attribute toolset_name
        #   For a toolset member tool_use, the toolset family.
        #
        #   @return [String, nil]
        optional :toolset_name, String, nil?: true

        response_only do
          # @api public
          #
          # Parsed input data coerced to the tool's input schema model.
          # Only present when tools are defined using the InputSchema DSL.
          required :parsed, Anthropic::Internal::Type::Unknown

          # @api private
          #
          # Internal buffer for accumulating partial JSON during streaming.
          # Used by streaming helpers to reconstruct complete JSON input from deltas.
          optional :_json_buf, String
        end

        # @!method initialize(id:, input:, name:, caller_: nil, toolset_name: nil, type: :tool_use)
        #   @param id [String]
        #
        #   @param input [Object]
        #
        #   @param name [String]
        #
        #   @param caller_ [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120]
        #
        #   @param toolset_name [String, nil] For a toolset member tool_use, the toolset family.
        #
        #   @param type [Symbol, :tool_use]

        # @see Anthropic::Models::Beta::BetaToolUseBlock#caller_
        module Caller
          extend Anthropic::Internal::Type::Union

          discriminator :type

          # Tool invocation directly from the model.
          variant :direct, -> { Anthropic::Beta::BetaDirectCaller }

          # Tool invocation generated by a server-side tool.
          variant :code_execution_20250825, -> { Anthropic::Beta::BetaServerToolCaller }

          variant :code_execution_20260120, -> { Anthropic::Beta::BetaServerToolCaller20260120 }

          module Type
            extend Anthropic::Internal::Type::Enum

            DIRECT = :direct
            CODE_EXECUTION_20250825 = :code_execution_20250825
            CODE_EXECUTION_20260120 = :code_execution_20260120

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @!method self.variants
          #   @return [Array(Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120)]

          # Creates a new instance of the variant class whose `type` matches the given
          # value, passing the remaining arguments to its constructor.
          #
          # @param type [Symbol, Anthropic::Models::Beta::BetaToolUseBlock::Caller::Type, String]
          #
          # @param args [Hash{Symbol=>Object}] Attributes for the chosen variant.
          #
          #   @option args [String] :tool_id
          #
          # @raise [ArgumentError]
          # @return [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, Anthropic::Models::Beta::BetaServerToolCaller20260120]
          def self.new(type:, **args)
            case type.to_sym
            when :direct
              Anthropic::Beta::BetaDirectCaller.new(**args)
            when :code_execution_20250825
              Anthropic::Beta::BetaServerToolCaller.new(**args)
            when :code_execution_20260120
              Anthropic::Beta::BetaServerToolCaller20260120.new(**args)
            else
              raise ArgumentError, "unknown type: #{type}"
            end
          end
        end
      end
    end

    BetaToolUseBlock = Beta::BetaToolUseBlock
  end
end
