module Anthropic
  module Models
    module Beta
      module Organization
        module Federation
          module Rules
            type workspace_add_params =
              {
                federation_rule_id: String,
                workspace_id: String,
                betas: ::Array[Anthropic::Models::anthropic_beta]
              }
              & Anthropic::Internal::Type::request_parameters

            class WorkspaceAddParams < Anthropic::Internal::Type::BaseModel
              extend Anthropic::Internal::Type::RequestParameters::Converter
              include Anthropic::Internal::Type::RequestParameters

              attr_accessor federation_rule_id: String

              attr_accessor workspace_id: String

              attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

              def betas=: (
                ::Array[Anthropic::Models::anthropic_beta]
              ) -> ::Array[Anthropic::Models::anthropic_beta]

              def initialize: (
                federation_rule_id: String,
                workspace_id: String,
                ?betas: ::Array[Anthropic::Models::anthropic_beta],
                ?request_options: Anthropic::request_opts
              ) -> void

              def to_hash: -> {
                federation_rule_id: String,
                workspace_id: String,
                betas: ::Array[Anthropic::Models::anthropic_beta],
                request_options: Anthropic::RequestOptions
              }
            end
          end
        end
      end
    end
  end
end
