module Anthropic
  module Models
    module Skills
      type deleted_skill_version = { id: String, type: :skill_version_deleted }

      class DeletedSkillVersion < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor type: :skill_version_deleted

        def initialize: (id: String, ?type: :skill_version_deleted) -> void

        def to_hash: -> { id: String, type: :skill_version_deleted }
      end
    end
  end
end
