# typed: strong

module Anthropic
  module Models
    module Beta
      module Sessions
        class BetaManagedAgentsSpanModelUsage < Anthropic::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage,
                Anthropic::Internal::AnyHash
              )
            end

          # Tokens used to create prompt cache in this request.
          sig { returns(Integer) }
          attr_accessor :cache_creation_input_tokens

          # Tokens read from prompt cache in this request.
          sig { returns(Integer) }
          attr_accessor :cache_read_input_tokens

          # Input tokens consumed by this request.
          sig { returns(Integer) }
          attr_accessor :input_tokens

          # Output tokens generated by this request.
          sig { returns(Integer) }
          attr_accessor :output_tokens

          # Inference speed mode. `fast` provides significantly faster output token
          # generation at premium pricing. Not all models support `fast`; invalid
          # combinations are rejected at create time.
          sig do
            returns(
              T.nilable(
                Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed::TaggedSymbol
              )
            )
          end
          attr_accessor :speed

          # Token usage for a single model request.
          sig do
            params(
              cache_creation_input_tokens: Integer,
              cache_read_input_tokens: Integer,
              input_tokens: Integer,
              output_tokens: Integer,
              speed:
                T.nilable(
                  Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed::OrSymbol
                )
            ).returns(T.attached_class)
          end
          def self.new(
            # Tokens used to create prompt cache in this request.
            cache_creation_input_tokens:,
            # Tokens read from prompt cache in this request.
            cache_read_input_tokens:,
            # Input tokens consumed by this request.
            input_tokens:,
            # Output tokens generated by this request.
            output_tokens:,
            # Inference speed mode. `fast` provides significantly faster output token
            # generation at premium pricing. Not all models support `fast`; invalid
            # combinations are rejected at create time.
            speed: nil
          )
          end

          sig do
            override.returns(
              {
                cache_creation_input_tokens: Integer,
                cache_read_input_tokens: Integer,
                input_tokens: Integer,
                output_tokens: Integer,
                speed:
                  T.nilable(
                    Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed::TaggedSymbol
                  )
              }
            )
          end
          def to_hash
          end

          # Inference speed mode. `fast` provides significantly faster output token
          # generation at premium pricing. Not all models support `fast`; invalid
          # combinations are rejected at create time.
          module Speed
            extend Anthropic::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            STANDARD =
              T.let(
                :standard,
                Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed::TaggedSymbol
              )
            FAST =
              T.let(
                :fast,
                Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end
      end
    end
  end
end
