module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_environment_variable_create_params =
          {
            networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params,
            secret_name: String,
            secret_value: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams::type_,
            injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams
          }

        class BetaManagedAgentsEnvironmentVariableCreateParams < Anthropic::Internal::Type::BaseModel
          attr_accessor networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params

          attr_accessor secret_name: String

          attr_accessor secret_value: String

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams::type_

          attr_reader injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams?

          def injection_location=: (
            Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams

          def initialize: (
            networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params,
            secret_name: String,
            secret_value: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams::type_,
            ?injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams
          ) -> void

          def to_hash: -> {
            networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params,
            secret_name: String,
            secret_value: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams::type_,
            injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams
          }

          type type_ = :environment_variable

          module Type
            extend Anthropic::Internal::Type::Enum

            ENVIRONMENT_VARIABLE: :environment_variable

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams::type_]
          end
        end
      end
    end
  end
end
