module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_mcpo_auth_create_params =
          {
            access_token: String,
            mcp_server_url: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams::type_,
            expires_at: Time?,
            refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshParams?
          }

        class BetaManagedAgentsMCPOAuthCreateParams < Anthropic::Internal::Type::BaseModel
          attr_accessor access_token: String

          attr_accessor mcp_server_url: String

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams::type_

          attr_accessor expires_at: Time?

          attr_accessor refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshParams?

          def initialize: (
            access_token: String,
            mcp_server_url: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams::type_,
            ?expires_at: Time?,
            ?refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshParams?
          ) -> void

          def to_hash: -> {
            access_token: String,
            mcp_server_url: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams::type_,
            expires_at: Time?,
            refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshParams?
          }

          type type_ = :mcp_oauth

          module Type
            extend Anthropic::Internal::Type::Enum

            MCP_OAUTH: :mcp_oauth

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams::type_]
          end
        end
      end
    end
  end
end
