module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_deleted_credential =
          {
            id: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsDeletedCredential::type_
          }

        class BetaManagedAgentsDeletedCredential < Anthropic::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsDeletedCredential::type_

          def initialize: (
            id: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsDeletedCredential::type_
          ) -> void

          def to_hash: -> {
            id: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsDeletedCredential::type_
          }

          type type_ = :vault_credential_deleted

          module Type
            extend Anthropic::Internal::Type::Enum

            VAULT_CREDENTIAL_DELETED: :vault_credential_deleted

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsDeletedCredential::type_]
          end
        end
      end
    end
  end
end
