module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_credential_validation =
          {
            credential_id: String,
            has_refresh_token: bool,
            mcp_probe: Anthropic::Beta::Vaults::BetaManagedAgentsMCPProbe?,
            refresh: Anthropic::Beta::Vaults::BetaManagedAgentsRefreshObject?,
            status: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_validation_status,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredentialValidation::type_,
            validated_at: Time,
            vault_id: String
          }

        class BetaManagedAgentsCredentialValidation < Anthropic::Internal::Type::BaseModel
          attr_accessor credential_id: String

          attr_accessor has_refresh_token: bool

          attr_accessor mcp_probe: Anthropic::Beta::Vaults::BetaManagedAgentsMCPProbe?

          attr_accessor refresh: Anthropic::Beta::Vaults::BetaManagedAgentsRefreshObject?

          attr_accessor status: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_validation_status

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredentialValidation::type_

          attr_accessor validated_at: Time

          attr_accessor vault_id: String

          def initialize: (
            credential_id: String,
            has_refresh_token: bool,
            mcp_probe: Anthropic::Beta::Vaults::BetaManagedAgentsMCPProbe?,
            refresh: Anthropic::Beta::Vaults::BetaManagedAgentsRefreshObject?,
            status: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_validation_status,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredentialValidation::type_,
            validated_at: Time,
            vault_id: String
          ) -> void

          def to_hash: -> {
            credential_id: String,
            has_refresh_token: bool,
            mcp_probe: Anthropic::Beta::Vaults::BetaManagedAgentsMCPProbe?,
            refresh: Anthropic::Beta::Vaults::BetaManagedAgentsRefreshObject?,
            status: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_validation_status,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredentialValidation::type_,
            validated_at: Time,
            vault_id: String
          }

          type type_ = :vault_credential_validation

          module Type
            extend Anthropic::Internal::Type::Enum

            VAULT_CREDENTIAL_VALIDATION: :vault_credential_validation

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsCredentialValidation::type_]
          end
        end
      end
    end
  end
end
