module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_environment_variable_auth_response =
          {
            injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationResponse,
            networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking,
            secret_name: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_
          }

        class BetaManagedAgentsEnvironmentVariableAuthResponse < Anthropic::Internal::Type::BaseModel
          attr_accessor injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationResponse

          attr_accessor networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking

          attr_accessor secret_name: String

          attr_accessor type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_

          def initialize: (
            injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationResponse,
            networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking,
            secret_name: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_
          ) -> void

          def to_hash: -> {
            injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationResponse,
            networking: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking,
            secret_name: String,
            type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_
          }

          type networking =
            Anthropic::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse
            | Anthropic::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse

          module Networking
            extend Anthropic::Internal::Type::Union

            type type_ = :unrestricted | :limited

            module Type
              extend Anthropic::Internal::Type::Enum

              UNRESTRICTED: :unrestricted
              LIMITED: :limited

              def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::Networking::type_]
            end

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking]

            def self.new:
              (
                type: :unrestricted | "unrestricted"
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsUnrestrictedCredentialNetworkingResponse
              | (
                type: :limited | "limited",
                allowed_hosts: ::Array[String]
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsLimitedCredentialNetworkingResponse
              | (
                type: Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::Networking::type_
                | String,
                ?allowed_hosts: ::Array[String]
              ) -> Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::networking
          end

          type type_ = :environment_variable

          module Type
            extend Anthropic::Internal::Type::Enum

            ENVIRONMENT_VARIABLE: :environment_variable

            def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::BetaManagedAgentsEnvironmentVariableAuthResponse::type_]
          end
        end
      end
    end
  end
end
