module Anthropic
  module Models
    module Beta
      module Vaults
        type credential_list_params =
          {
            vault_id: String,
            include_archived: bool,
            limit: Integer,
            page: String,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            workspace_id: String
          }
          & Anthropic::Internal::Type::request_parameters

        class CredentialListParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor vault_id: String

          attr_reader include_archived: bool?

          def include_archived=: (bool) -> bool

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader page: String?

          def page=: (String) -> String

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          attr_reader workspace_id: String?

          def workspace_id=: (String) -> String

          def initialize: (
            vault_id: String,
            ?include_archived: bool,
            ?limit: Integer,
            ?page: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            vault_id: String,
            include_archived: bool,
            limit: Integer,
            page: String,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            workspace_id: String,
            request_options: Anthropic::RequestOptions
          }
        end
      end
    end
  end
end
