module Anthropic
  module Models
    module Beta
      module Vaults
        type credential_create_params =
          {
            vault_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String],
            betas: ::Array[Anthropic::Models::anthropic_beta],
            workspace_id: String
          }
          & Anthropic::Internal::Type::request_parameters

        class CredentialCreateParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor vault_id: String

          attr_accessor auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth

          attr_accessor display_name: String?

          attr_reader metadata: ::Hash[Symbol, String]?

          def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          attr_reader workspace_id: String?

          def workspace_id=: (String) -> String

          def initialize: (
            vault_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            ?display_name: String?,
            ?metadata: ::Hash[Symbol, String],
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            vault_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String],
            betas: ::Array[Anthropic::Models::anthropic_beta],
            workspace_id: String,
            request_options: Anthropic::RequestOptions
          }

          type auth =
            Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerCreateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams

          module Auth
            extend Anthropic::Internal::Type::Union

            type type_ = :mcp_oauth | :static_bearer | :environment_variable

            module Type
              extend Anthropic::Internal::Type::Enum

              MCP_OAUTH: :mcp_oauth
              STATIC_BEARER: :static_bearer
              ENVIRONMENT_VARIABLE: :environment_variable

              def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::CredentialCreateParams::Auth::type_]
            end

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth]

            def self.new:
              (
                type: :mcp_oauth | "mcp_oauth",
                access_token: String,
                mcp_server_url: String,
                ?expires_at: Time?,
                ?refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshParams?
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthCreateParams
              | (
                type: :static_bearer | "static_bearer",
                token: String,
                mcp_server_url: String
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerCreateParams
              | (
                type: :environment_variable | "environment_variable",
                networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params,
                secret_name: String,
                secret_value: String,
                ?injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableCreateParams
              | (
                type: Anthropic::Models::Beta::Vaults::CredentialCreateParams::Auth::type_
                | String,
                ?access_token: String,
                ?mcp_server_url: String,
                ?expires_at: Time?,
                ?refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshParams?,
                ?token: String,
                ?networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params,
                ?secret_name: String,
                ?secret_value: String,
                ?injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationParams
              ) -> Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth
          end
        end
      end
    end
  end
end
