module Anthropic
  module Models
    module Beta
      module Vaults
        type credential_update_params =
          {
            vault_id: String,
            credential_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String?]?,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            workspace_id: String
          }
          & Anthropic::Internal::Type::request_parameters

        class CredentialUpdateParams < Anthropic::Internal::Type::BaseModel
          extend Anthropic::Internal::Type::RequestParameters::Converter
          include Anthropic::Internal::Type::RequestParameters

          attr_accessor vault_id: String

          attr_accessor credential_id: String

          attr_reader auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth?

          def auth=: (
            Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth
          ) -> Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth

          attr_accessor display_name: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

          def betas=: (
            ::Array[Anthropic::Models::anthropic_beta]
          ) -> ::Array[Anthropic::Models::anthropic_beta]

          attr_reader workspace_id: String?

          def workspace_id=: (String) -> String

          def initialize: (
            vault_id: String,
            credential_id: String,
            ?auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            ?display_name: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> void

          def to_hash: -> {
            vault_id: String,
            credential_id: String,
            auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            display_name: String?,
            metadata: ::Hash[Symbol, String?]?,
            betas: ::Array[Anthropic::Models::anthropic_beta],
            workspace_id: String,
            request_options: Anthropic::RequestOptions
          }

          type auth =
            Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthUpdateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerUpdateParams
            | Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableUpdateParams

          module Auth
            extend Anthropic::Internal::Type::Union

            type type_ = :mcp_oauth | :static_bearer | :environment_variable

            module Type
              extend Anthropic::Internal::Type::Enum

              MCP_OAUTH: :mcp_oauth
              STATIC_BEARER: :static_bearer
              ENVIRONMENT_VARIABLE: :environment_variable

              def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::CredentialUpdateParams::Auth::type_]
            end

            def self?.variants: -> ::Array[Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth]

            def self.new:
              (
                type: :mcp_oauth | "mcp_oauth",
                ?access_token: String?,
                ?expires_at: Time?,
                ?refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshUpdateParams?
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthUpdateParams
              | (
                type: :static_bearer | "static_bearer",
                ?token: String?
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsStaticBearerUpdateParams
              | (
                type: :environment_variable | "environment_variable",
                ?injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationUpdateParams,
                ?networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params?,
                ?secret_value: String?
              ) -> Anthropic::Beta::Vaults::BetaManagedAgentsEnvironmentVariableUpdateParams
              | (
                type: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::Auth::type_
                | String,
                ?access_token: String?,
                ?expires_at: Time?,
                ?refresh: Anthropic::Beta::Vaults::BetaManagedAgentsMCPOAuthRefreshUpdateParams?,
                ?token: String?,
                ?injection_location: Anthropic::Beta::Vaults::BetaManagedAgentsInjectionLocationUpdateParams,
                ?networking: Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_networking_params?,
                ?secret_value: String?
              ) -> Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth
          end
        end
      end
    end
  end
end
