# typed: strong

module Anthropic
  module Models
    module RawContentBlockDelta
      extend Anthropic::Internal::Type::Union

      Variants =
        T.type_alias do
          T.any(
            Anthropic::TextDelta,
            Anthropic::InputJSONDelta,
            Anthropic::CitationsDelta,
            Anthropic::ThinkingDelta,
            Anthropic::SignatureDelta
          )
        end

      module Type
        extend Anthropic::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias { T.all(Symbol, Anthropic::RawContentBlockDelta::Type) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        TEXT_DELTA =
          T.let(
            :text_delta,
            Anthropic::RawContentBlockDelta::Type::TaggedSymbol
          )
        INPUT_JSON_DELTA =
          T.let(
            :input_json_delta,
            Anthropic::RawContentBlockDelta::Type::TaggedSymbol
          )
        CITATIONS_DELTA =
          T.let(
            :citations_delta,
            Anthropic::RawContentBlockDelta::Type::TaggedSymbol
          )
        THINKING_DELTA =
          T.let(
            :thinking_delta,
            Anthropic::RawContentBlockDelta::Type::TaggedSymbol
          )
        SIGNATURE_DELTA =
          T.let(
            :signature_delta,
            Anthropic::RawContentBlockDelta::Type::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[Anthropic::RawContentBlockDelta::Type::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      sig do
        override.returns(T::Array[Anthropic::RawContentBlockDelta::Variants])
      end
      def self.variants
      end

      # Creates a new instance of the variant class whose `type` matches the given
      # value, passing the remaining arguments to its constructor.
      sig do
        params(
          type: Anthropic::RawContentBlockDelta::Type::OrSymbol,
          text: String,
          partial_json: String,
          citation:
            T.any(
              Anthropic::CitationCharLocation::OrHash,
              Anthropic::CitationPageLocation::OrHash,
              Anthropic::CitationContentBlockLocation::OrHash,
              Anthropic::CitationsWebSearchResultLocation::OrHash,
              Anthropic::CitationsSearchResultLocation::OrHash
            ),
          thinking: String,
          signature: String
        ).returns(Anthropic::RawContentBlockDelta::Variants)
      end
      def self.new(
        type:,
        text: nil,
        partial_json: nil,
        citation: nil,
        # The incremental `thinking` text for this content block. Concatenate the
        # `thinking` values of successive `thinking_delta` events to assemble the block's
        # full `thinking` value.
        thinking: nil,
        # The `signature` for this thinking block: an opaque value used to verify that the
        # block was generated by Claude when it is passed back to the API. Delivered in a
        # `signature_delta` event just before the block's `content_block_stop` event.
        signature: nil
      )
      end
    end
  end
end
