# typed: strong

module Anthropic
  module Models
    class ThinkingBlockParam < Anthropic::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(Anthropic::ThinkingBlockParam, Anthropic::Internal::AnyHash)
        end

      # The `signature` value of this thinking block, exactly as returned by the API in
      # a previous response. Used to verify that the block was generated by Claude.
      #
      # Thinking blocks must be passed back unmodified and in their original order; a
      # modified block results in a 400 `invalid_request_error`.
      sig { returns(String) }
      attr_accessor :signature

      # The `thinking` text of this block as returned by the API.
      sig { returns(String) }
      attr_accessor :thinking

      sig { returns(Symbol) }
      attr_accessor :type

      sig do
        params(signature: String, thinking: String, type: Symbol).returns(
          T.attached_class
        )
      end
      def self.new(
        # The `signature` value of this thinking block, exactly as returned by the API in
        # a previous response. Used to verify that the block was generated by Claude.
        #
        # Thinking blocks must be passed back unmodified and in their original order; a
        # modified block results in a 400 `invalid_request_error`.
        signature:,
        # The `thinking` text of this block as returned by the API.
        thinking:,
        type: :thinking
      )
      end

      sig do
        override.returns({ signature: String, thinking: String, type: Symbol })
      end
      def to_hash
      end
    end
  end
end
