module Anthropic
  module Resources
    class Beta
      class Vaults
        class Credentials
          def create: (
            String vault_id,
            auth: Anthropic::Models::Beta::Vaults::CredentialCreateParams::auth,
            ?display_name: String?,
            ?metadata: ::Hash[Symbol, String],
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsCredential

          def retrieve: (
            String credential_id,
            vault_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsCredential

          def update: (
            String credential_id,
            vault_id: String,
            ?auth: Anthropic::Models::Beta::Vaults::CredentialUpdateParams::auth,
            ?display_name: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsCredential

          def list: (
            String vault_id,
            ?include_archived: bool,
            ?limit: Integer,
            ?page: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::Vaults::BetaManagedAgentsCredential]

          def delete: (
            String credential_id,
            vault_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsDeletedCredential

          def archive: (
            String credential_id,
            vault_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsCredential

          def mcp_oauth_validate: (
            String credential_id,
            vault_id: String,
            ?betas: ::Array[Anthropic::Models::anthropic_beta],
            ?workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Beta::Vaults::BetaManagedAgentsCredentialValidation

          def initialize: (client: Anthropic::Client) -> void
        end
      end
    end
  end
end
