using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Core;
using Anthropic.Exceptions;

namespace Anthropic.Models.Messages;

/// <summary>
/// Tool invocation generated by a server-side tool.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ServerToolCaller, ServerToolCallerFromRaw>))]
public sealed record class ServerToolCaller : JsonModel
{
    public required string ToolID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("tool_id");
        }
        init { this._rawData.Set("tool_id", value); }
    }

    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ToolID;
        if (
            !JsonElement.DeepEquals(
                this.Type,
                JsonSerializer.SerializeToElement("code_execution_20250825")
            )
        )
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
    }

    public ServerToolCaller()
    {
        this.Type = JsonSerializer.SerializeToElement("code_execution_20250825");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ServerToolCaller(ServerToolCaller serverToolCaller)
        : base(serverToolCaller) { }
#pragma warning restore CS8618

    public ServerToolCaller(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("code_execution_20250825");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ServerToolCaller(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ServerToolCallerFromRaw.FromRawUnchecked"/>
    public static ServerToolCaller FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public ServerToolCaller(string toolID)
        : this()
    {
        this.ToolID = toolID;
    }
}

class ServerToolCallerFromRaw : IFromRawJson<ServerToolCaller>
{
    /// <inheritdoc/>
    public ServerToolCaller FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        ServerToolCaller.FromRawUnchecked(rawData);
}
