using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Core;
using Anthropic.Exceptions;

namespace Anthropic.Models.Messages;

[JsonConverter(typeof(JsonModelConverter<ThinkingBlockParam, ThinkingBlockParamFromRaw>))]
public sealed record class ThinkingBlockParam : JsonModel
{
    /// <summary>
    /// The `signature` value of this thinking block, exactly as returned by the
    /// API in a previous response. Used to verify that the block was generated by Claude.
    ///
    /// <para>Thinking blocks must be passed back unmodified and in their original
    /// order; a modified block results in a 400 `invalid_request_error`.</para>
    /// </summary>
    public required string Signature
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("signature");
        }
        init { this._rawData.Set("signature", value); }
    }

    /// <summary>
    /// The `thinking` text of this block as returned by the API.
    /// </summary>
    public required string Thinking
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("thinking");
        }
        init { this._rawData.Set("thinking", value); }
    }

    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Signature;
        _ = this.Thinking;
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("thinking")))
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
    }

    public ThinkingBlockParam()
    {
        this.Type = JsonSerializer.SerializeToElement("thinking");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ThinkingBlockParam(ThinkingBlockParam thinkingBlockParam)
        : base(thinkingBlockParam) { }
#pragma warning restore CS8618

    public ThinkingBlockParam(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("thinking");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ThinkingBlockParam(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ThinkingBlockParamFromRaw.FromRawUnchecked"/>
    public static ThinkingBlockParam FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ThinkingBlockParamFromRaw : IFromRawJson<ThinkingBlockParam>
{
    /// <inheritdoc/>
    public ThinkingBlockParam FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        ThinkingBlockParam.FromRawUnchecked(rawData);
}
