using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Core;
using Anthropic.Exceptions;

namespace Anthropic.Models.Messages;

[JsonConverter(typeof(JsonModelConverter<ThinkingBlock, ThinkingBlockFromRaw>))]
public sealed record class ThinkingBlock : JsonModel
{
    /// <summary>
    /// A value used to verify that this thinking block was generated by Claude when
    /// it is passed back to the API.
    ///
    /// <para>This is an opaque field and should not be interpreted or parsed. When
    /// passing thinking blocks back to the API (required when using tools with extended
    /// thinking), pass them back exactly as received, with this field intact.</para>
    ///
    /// <para>See [extended thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking)
    /// for details.</para>
    /// </summary>
    public required string Signature
    {
        get
        {
            this._rawData.Freeze();
            // Some APIs are advertised as Anthropic-compatible but erroneously omit the `signature` field in the response.
            // This is a bug in the API itself, although we can handle it fairly easily here, so we do.
            return this._rawData.GetNullableClass<string>("signature") ?? string.Empty;
        }
        init { this._rawData.Set("signature", value); }
    }

    /// <summary>
    /// The text of Claude's thinking process for this block.
    /// </summary>
    public required string Thinking
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("thinking");
        }
        init { this._rawData.Set("thinking", value); }
    }

    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Signature;
        _ = this.Thinking;
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("thinking")))
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
    }

    public ThinkingBlock()
    {
        this.Type = JsonSerializer.SerializeToElement("thinking");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ThinkingBlock(ThinkingBlock thinkingBlock)
        : base(thinkingBlock) { }
#pragma warning restore CS8618

    public ThinkingBlock(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("thinking");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ThinkingBlock(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ThinkingBlockFromRaw.FromRawUnchecked"/>
    public static ThinkingBlock FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ThinkingBlockFromRaw : IFromRawJson<ThinkingBlock>
{
    /// <inheritdoc/>
    public ThinkingBlock FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        ThinkingBlock.FromRawUnchecked(rawData);
}
