module Anthropic
  module Models
    module Beta
      type agent_create_params =
        {
          model: Anthropic::Models::Beta::AgentCreateParams::model,
          name: String,
          description: String?,
          mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsURLMCPServerParams],
          metadata: ::Hash[Symbol, String],
          multiagent: Anthropic::Beta::BetaManagedAgentsMultiagentParams?,
          skills: ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params],
          system_: String?,
          tools: ::Array[Anthropic::Models::Beta::AgentCreateParams::tool],
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String
        }
        & Anthropic::Internal::Type::request_parameters

      class AgentCreateParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor model: Anthropic::Models::Beta::AgentCreateParams::model

        attr_accessor name: String

        attr_accessor description: String?

        attr_reader mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsURLMCPServerParams]?

        def mcp_servers=: (
          ::Array[Anthropic::Beta::BetaManagedAgentsURLMCPServerParams]
        ) -> ::Array[Anthropic::Beta::BetaManagedAgentsURLMCPServerParams]

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor multiagent: Anthropic::Beta::BetaManagedAgentsMultiagentParams?

        attr_reader skills: ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params]?

        def skills=: (
          ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params]
        ) -> ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params]

        attr_accessor system_: String?

        attr_reader tools: ::Array[Anthropic::Models::Beta::AgentCreateParams::tool]?

        def tools=: (
          ::Array[Anthropic::Models::Beta::AgentCreateParams::tool]
        ) -> ::Array[Anthropic::Models::Beta::AgentCreateParams::tool]

        attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

        def betas=: (
          ::Array[Anthropic::Models::anthropic_beta]
        ) -> ::Array[Anthropic::Models::anthropic_beta]

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        def initialize: (
          model: Anthropic::Models::Beta::AgentCreateParams::model,
          name: String,
          ?description: String?,
          ?mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsURLMCPServerParams],
          ?metadata: ::Hash[Symbol, String],
          ?multiagent: Anthropic::Beta::BetaManagedAgentsMultiagentParams?,
          ?skills: ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params],
          ?system_: String?,
          ?tools: ::Array[Anthropic::Models::Beta::AgentCreateParams::tool],
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          model: Anthropic::Models::Beta::AgentCreateParams::model,
          name: String,
          description: String?,
          mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsURLMCPServerParams],
          metadata: ::Hash[Symbol, String],
          multiagent: Anthropic::Beta::BetaManagedAgentsMultiagentParams?,
          skills: ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params],
          system_: String?,
          tools: ::Array[Anthropic::Models::Beta::AgentCreateParams::tool],
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String,
          request_options: Anthropic::RequestOptions
        }

        type model =
          Anthropic::Beta::BetaManagedAgentsModelConfigParams
          | Anthropic::Models::Beta::beta_managed_agents_model

        module Model
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::AgentCreateParams::model]
        end

        type tool =
          Anthropic::Beta::BetaManagedAgentsAgentToolset20260401Params
          | Anthropic::Beta::BetaManagedAgentsMCPToolsetParams
          | Anthropic::Beta::BetaManagedAgentsCustomToolParams

        module Tool
          extend Anthropic::Internal::Type::Union

          type type_ = :agent_toolset_20260401 | :mcp_toolset | :custom

          module Type
            extend Anthropic::Internal::Type::Enum

            AGENT_TOOLSET_20260401: :agent_toolset_20260401
            MCP_TOOLSET: :mcp_toolset
            CUSTOM: :custom

            def self?.values: -> ::Array[Anthropic::Models::Beta::AgentCreateParams::Tool::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::AgentCreateParams::tool]

          def self.new:
            (
              type: :agent_toolset_20260401 | "agent_toolset_20260401",
              ?configs: ::Array[Anthropic::Models::Beta::beta_managed_agents_agent_tool_config_params],
              ?default_config: Anthropic::Beta::BetaManagedAgentsAgentToolsetDefaultConfigParams?
            ) -> Anthropic::Beta::BetaManagedAgentsAgentToolset20260401Params
            | (
              type: :mcp_toolset | "mcp_toolset",
              mcp_server_name: String,
              ?configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams],
              ?default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfigParams?
            ) -> Anthropic::Beta::BetaManagedAgentsMCPToolsetParams
            | (
              type: :custom | "custom",
              description: String,
              input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
              name: String
            ) -> Anthropic::Beta::BetaManagedAgentsCustomToolParams
            | (
              type: Anthropic::Models::Beta::AgentCreateParams::Tool::type_
              | String,
              ?configs: ::Array[Anthropic::Models::Beta::beta_managed_agents_agent_tool_config_params]
              | ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams],
              ?default_config: Anthropic::Beta::BetaManagedAgentsAgentToolsetDefaultConfigParams?
              | Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfigParams?,
              ?mcp_server_name: String,
              ?description: String,
              ?input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
              ?name: String
            ) -> Anthropic::Models::Beta::AgentCreateParams::tool
        end
      end
    end
  end
end
