module Anthropic
  module Models
    class BetaUserProfileEnrollmentURL = Beta::BetaUserProfileEnrollmentURL

    module Beta
      type beta_user_profile_enrollment_url =
        {
          expires_at: Time,
          type: Anthropic::Models::Beta::BetaUserProfileEnrollmentURL::type_,
          url: String
        }

      class BetaUserProfileEnrollmentURL < Anthropic::Internal::Type::BaseModel
        attr_accessor expires_at: Time

        attr_accessor type: Anthropic::Models::Beta::BetaUserProfileEnrollmentURL::type_

        attr_accessor url: String

        def initialize: (
          expires_at: Time,
          type: Anthropic::Models::Beta::BetaUserProfileEnrollmentURL::type_,
          url: String
        ) -> void

        def to_hash: -> {
          expires_at: Time,
          type: Anthropic::Models::Beta::BetaUserProfileEnrollmentURL::type_,
          url: String
        }

        type type_ = :enrollment_url

        module Type
          extend Anthropic::Internal::Type::Enum

          ENROLLMENT_URL: :enrollment_url

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaUserProfileEnrollmentURL::type_]
        end
      end
    end
  end
end
