module Anthropic
  module Models
    class BetaWebhookSessionRequiresActionEventData = Beta::BetaWebhookSessionRequiresActionEventData

    module Beta
      type beta_webhook_session_requires_action_event_data =
        {
          id: String,
          organization_id: String,
          type: :"session.requires_action",
          workspace_id: String
        }

      class BetaWebhookSessionRequiresActionEventData < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor organization_id: String

        attr_accessor type: :"session.requires_action"

        attr_accessor workspace_id: String

        def initialize: (
          id: String,
          organization_id: String,
          workspace_id: String,
          ?type: :"session.requires_action"
        ) -> void

        def to_hash: -> {
          id: String,
          organization_id: String,
          type: :"session.requires_action",
          workspace_id: String
        }
      end
    end
  end
end
