module Anthropic
  module Models
    class BetaComputerMouseMoveConfig = Beta::BetaComputerMouseMoveConfig

    module Beta
      type beta_computer_mouse_move_config =
        { defer_loading: bool?, enabled: bool? }

      class BetaComputerMouseMoveConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
