module Anthropic
  module Models
    class BetaWebhookVaultCredentialRefreshFailedEventData = Beta::BetaWebhookVaultCredentialRefreshFailedEventData

    module Beta
      type beta_webhook_vault_credential_refresh_failed_event_data =
        {
          id: String,
          organization_id: String,
          type: :"vault_credential.refresh_failed",
          vault_id: String,
          workspace_id: String
        }

      class BetaWebhookVaultCredentialRefreshFailedEventData < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor organization_id: String

        attr_accessor type: :"vault_credential.refresh_failed"

        attr_accessor vault_id: String

        attr_accessor workspace_id: String

        def initialize: (
          id: String,
          organization_id: String,
          vault_id: String,
          workspace_id: String,
          ?type: :"vault_credential.refresh_failed"
        ) -> void

        def to_hash: -> {
          id: String,
          organization_id: String,
          type: :"vault_credential.refresh_failed",
          vault_id: String,
          workspace_id: String
        }
      end
    end
  end
end
