module Anthropic
  module Models
    class BetaBrowserLeftMouseDownConfig = Beta::BetaBrowserLeftMouseDownConfig

    module Beta
      type beta_browser_left_mouse_down_config =
        { defer_loading: bool?, enabled: bool? }

      class BetaBrowserLeftMouseDownConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
