module Anthropic
  module Models
    module BetaManagedAgentsStartEventPreview = Beta::BetaManagedAgentsStartEventPreview

    module Beta
      type beta_managed_agents_start_event_preview =
        Anthropic::Beta::BetaManagedAgentsAgentMessagePreview
        | Anthropic::Beta::BetaManagedAgentsAgentThinkingPreview

      module BetaManagedAgentsStartEventPreview
        extend Anthropic::Internal::Type::Union

        type type_ = :"agent.message" | :"agent.thinking"

        module Type
          extend Anthropic::Internal::Type::Enum

          AGENT_MESSAGE: :"agent.message"
          AGENT_THINKING: :"agent.thinking"

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsStartEventPreview::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_start_event_preview]

        def self.new:
          (
            type: :"agent.message" | "agent.message",
            id: String
          ) -> Anthropic::Beta::BetaManagedAgentsAgentMessagePreview
          | (
            type: :"agent.thinking" | "agent.thinking",
            id: String
          ) -> Anthropic::Beta::BetaManagedAgentsAgentThinkingPreview
          | (
            type: Anthropic::Models::Beta::BetaManagedAgentsStartEventPreview::type_
            | String,
            id: String
          ) -> Anthropic::Models::Beta::beta_managed_agents_start_event_preview
      end
    end
  end
end
