module Anthropic
  module Models
    class BetaCompactionBlock = Beta::BetaCompactionBlock

    module Beta
      type beta_compaction_block =
        {
          content: String?,
          encrypted_content: String?,
          type: :compaction,
          signature: String?,
          tool_changes: ::Array[Anthropic::Models::Beta::BetaCompactionBlock::tool_change]?
        }

      class BetaCompactionBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor content: String?

        attr_accessor encrypted_content: String?

        attr_accessor type: :compaction

        attr_accessor signature: String?

        attr_accessor tool_changes: ::Array[Anthropic::Models::Beta::BetaCompactionBlock::tool_change]?

        def initialize: (
          content: String?,
          encrypted_content: String?,
          ?signature: String?,
          ?tool_changes: ::Array[Anthropic::Models::Beta::BetaCompactionBlock::tool_change]?,
          ?type: :compaction
        ) -> void

        def to_hash: -> {
          content: String?,
          encrypted_content: String?,
          type: :compaction,
          signature: String?,
          tool_changes: ::Array[Anthropic::Models::Beta::BetaCompactionBlock::tool_change]?
        }

        type tool_change =
          Anthropic::Beta::BetaResponseToolAdditionBlock
          | Anthropic::Beta::BetaResponseToolRemovalBlock

        module ToolChange
          extend Anthropic::Internal::Type::Union

          type type_ = :tool_addition | :tool_removal

          module Type
            extend Anthropic::Internal::Type::Enum

            TOOL_ADDITION: :tool_addition
            TOOL_REMOVAL: :tool_removal

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaCompactionBlock::ToolChange::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaCompactionBlock::tool_change]

          def self.new:
            (
              type: :tool_addition | "tool_addition",
              tool: Anthropic::Models::Beta::BetaResponseToolAdditionBlock::tool
            ) -> Anthropic::Beta::BetaResponseToolAdditionBlock
            | (
              type: :tool_removal | "tool_removal",
              tool: Anthropic::Models::Beta::BetaResponseToolRemovalBlock::tool
            ) -> Anthropic::Beta::BetaResponseToolRemovalBlock
            | (
              type: Anthropic::Models::Beta::BetaCompactionBlock::ToolChange::type_
              | String,
              tool: Anthropic::Models::Beta::BetaResponseToolAdditionBlock::tool
              | Anthropic::Models::Beta::BetaResponseToolRemovalBlock::tool
            ) -> Anthropic::Models::Beta::BetaCompactionBlock::tool_change
        end
      end
    end
  end
end
