module Anthropic
  module Models
    module BetaManagedAgentsSkillParams = Beta::BetaManagedAgentsSkillParams

    module Beta
      type beta_managed_agents_skill_params =
        Anthropic::Beta::BetaManagedAgentsAnthropicSkillParams
        | Anthropic::Beta::BetaManagedAgentsCustomSkillParams

      module BetaManagedAgentsSkillParams
        extend Anthropic::Internal::Type::Union

        type type_ = :anthropic | :custom

        module Type
          extend Anthropic::Internal::Type::Enum

          ANTHROPIC: :anthropic
          CUSTOM: :custom

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSkillParams::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_skill_params]

        def self.new:
          (
            type: :anthropic | "anthropic",
            skill_id: String,
            ?version: String?
          ) -> Anthropic::Beta::BetaManagedAgentsAnthropicSkillParams
          | (
            type: :custom | "custom",
            skill_id: String,
            ?version: String?
          ) -> Anthropic::Beta::BetaManagedAgentsCustomSkillParams
          | (
            type: Anthropic::Models::Beta::BetaManagedAgentsSkillParams::type_
            | String,
            skill_id: String,
            ?version: String?
          ) -> Anthropic::Models::Beta::beta_managed_agents_skill_params
      end
    end
  end
end
