module Anthropic
  module Models
    class BetaUserProfileTrustGrant = Beta::BetaUserProfileTrustGrant

    module Beta
      type beta_user_profile_trust_grant =
        { status: Anthropic::Models::Beta::BetaUserProfileTrustGrant::status }

      class BetaUserProfileTrustGrant < Anthropic::Internal::Type::BaseModel
        attr_accessor status: Anthropic::Models::Beta::BetaUserProfileTrustGrant::status

        def initialize: (
          status: Anthropic::Models::Beta::BetaUserProfileTrustGrant::status
        ) -> void

        def to_hash: -> {
          status: Anthropic::Models::Beta::BetaUserProfileTrustGrant::status
        }

        type status = :active | :pending | :rejected

        module Status
          extend Anthropic::Internal::Type::Enum

          ACTIVE: :active
          PENDING: :pending
          REJECTED: :rejected

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaUserProfileTrustGrant::status]
        end
      end
    end
  end
end
