module Anthropic
  module Models
    class BetaComputerCursorPositionConfig = Beta::BetaComputerCursorPositionConfig

    module Beta
      type beta_computer_cursor_position_config =
        { defer_loading: bool?, enabled: bool? }

      class BetaComputerCursorPositionConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
