module Anthropic
  module Models
    class BetaBrowserFileUploadConfig = Beta::BetaBrowserFileUploadConfig

    module Beta
      type beta_browser_file_upload_config =
        { defer_loading: bool?, enabled: bool? }

      class BetaBrowserFileUploadConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
