module Anthropic
  module Models
    module BetaTextCitationParam = Beta::BetaTextCitationParam

    module Beta
      type beta_text_citation_param =
        Anthropic::Beta::BetaCitationCharLocationParam
        | Anthropic::Beta::BetaCitationPageLocationParam
        | Anthropic::Beta::BetaCitationContentBlockLocationParam
        | Anthropic::Beta::BetaCitationWebSearchResultLocationParam
        | Anthropic::Beta::BetaCitationSearchResultLocationParam

      module BetaTextCitationParam
        extend Anthropic::Internal::Type::Union

        type type_ =
          :char_location
          | :page_location
          | :content_block_location
          | :web_search_result_location
          | :search_result_location

        module Type
          extend Anthropic::Internal::Type::Enum

          CHAR_LOCATION: :char_location
          PAGE_LOCATION: :page_location
          CONTENT_BLOCK_LOCATION: :content_block_location
          WEB_SEARCH_RESULT_LOCATION: :web_search_result_location
          SEARCH_RESULT_LOCATION: :search_result_location

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaTextCitationParam::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_text_citation_param]

        def self.new:
          (
            type: :char_location | "char_location",
            cited_text: String,
            document_index: Integer,
            document_title: String?,
            end_char_index: Integer,
            start_char_index: Integer
          ) -> Anthropic::Beta::BetaCitationCharLocationParam
          | (
            type: :page_location | "page_location",
            cited_text: String,
            document_index: Integer,
            document_title: String?,
            end_page_number: Integer,
            start_page_number: Integer
          ) -> Anthropic::Beta::BetaCitationPageLocationParam
          | (
            type: :content_block_location | "content_block_location",
            cited_text: String,
            document_index: Integer,
            document_title: String?,
            end_block_index: Integer,
            start_block_index: Integer
          ) -> Anthropic::Beta::BetaCitationContentBlockLocationParam
          | (
            type: :web_search_result_location | "web_search_result_location",
            cited_text: String,
            encrypted_index: String,
            title: String?,
            url: String
          ) -> Anthropic::Beta::BetaCitationWebSearchResultLocationParam
          | (
            type: :search_result_location | "search_result_location",
            cited_text: String,
            end_block_index: Integer,
            search_result_index: Integer,
            source: String,
            start_block_index: Integer,
            title: String?
          ) -> Anthropic::Beta::BetaCitationSearchResultLocationParam
          | (
            type: Anthropic::Models::Beta::BetaTextCitationParam::type_
            | String,
            cited_text: String,
            ?document_index: Integer,
            ?document_title: String?,
            ?end_char_index: Integer,
            ?start_char_index: Integer,
            ?end_page_number: Integer,
            ?start_page_number: Integer,
            ?end_block_index: Integer,
            ?start_block_index: Integer,
            ?encrypted_index: String,
            ?title: String?,
            ?url: String,
            ?search_result_index: Integer,
            ?source: String
          ) -> Anthropic::Models::Beta::beta_text_citation_param
      end
    end
  end
end
