module Anthropic
  module Models
    class BetaToolChangeToolReference = Beta::BetaToolChangeToolReference

    module Beta
      type beta_tool_change_tool_reference =
        { name: String, type: :tool_reference }

      class BetaToolChangeToolReference < Anthropic::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor type: :tool_reference

        def initialize: (name: String, ?type: :tool_reference) -> void

        def to_hash: -> { name: String, type: :tool_reference }
      end
    end
  end
end
