module Anthropic
  module Models
    class BetaDreamMemoryStoreOutput = Beta::BetaDreamMemoryStoreOutput

    module Beta
      type beta_dream_memory_store_output =
        {
          memory_store_id: String,
          type: Anthropic::Models::Beta::BetaDreamMemoryStoreOutput::type_
        }

      class BetaDreamMemoryStoreOutput < Anthropic::Internal::Type::BaseModel
        attr_accessor memory_store_id: String

        attr_accessor type: Anthropic::Models::Beta::BetaDreamMemoryStoreOutput::type_

        def initialize: (
          memory_store_id: String,
          type: Anthropic::Models::Beta::BetaDreamMemoryStoreOutput::type_
        ) -> void

        def to_hash: -> {
          memory_store_id: String,
          type: Anthropic::Models::Beta::BetaDreamMemoryStoreOutput::type_
        }

        type type_ = :memory_store

        module Type
          extend Anthropic::Internal::Type::Enum

          MEMORY_STORE: :memory_store

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaDreamMemoryStoreOutput::type_]
        end
      end
    end
  end
end
