module Anthropic
  module Models
    class BetaMCPToolListingBlock = Beta::BetaMCPToolListingBlock

    module Beta
      type beta_mcp_tool_listing_block =
        {
          mcp_server_name: String,
          tools: ::Array[Anthropic::Beta::BetaMCPTool],
          type: :mcp_tool_listing
        }

      class BetaMCPToolListingBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor mcp_server_name: String

        attr_accessor tools: ::Array[Anthropic::Beta::BetaMCPTool]

        attr_accessor type: :mcp_tool_listing

        def initialize: (
          mcp_server_name: String,
          tools: ::Array[Anthropic::Beta::BetaMCPTool],
          ?type: :mcp_tool_listing
        ) -> void

        def to_hash: -> {
          mcp_server_name: String,
          tools: ::Array[Anthropic::Beta::BetaMCPTool],
          type: :mcp_tool_listing
        }
      end
    end
  end
end
