module Anthropic
  module Models
    class BetaManagedAgentsAgent = Beta::BetaManagedAgentsAgent

    module Beta
      type beta_managed_agents_agent =
        {
          id: String,
          archived_at: Time?,
          created_at: Time,
          description: String?,
          mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsMCPServerURLDefinition],
          metadata: ::Hash[Symbol, String],
          model: Anthropic::Beta::BetaManagedAgentsModelConfig,
          multiagent: Anthropic::Beta::BetaManagedAgentsMultiagent?,
          name: String,
          skills: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::skill],
          system_: String?,
          tools: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::tool],
          type: Anthropic::Models::Beta::BetaManagedAgentsAgent::type_,
          updated_at: Time,
          version: Integer
        }

      class BetaManagedAgentsAgent < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived_at: Time?

        attr_accessor created_at: Time

        attr_accessor description: String?

        attr_accessor mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsMCPServerURLDefinition]

        attr_accessor metadata: ::Hash[Symbol, String]

        attr_accessor model: Anthropic::Beta::BetaManagedAgentsModelConfig

        attr_accessor multiagent: Anthropic::Beta::BetaManagedAgentsMultiagent?

        attr_accessor name: String

        attr_accessor skills: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::skill]

        attr_accessor system_: String?

        attr_accessor tools: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::tool]

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsAgent::type_

        attr_accessor updated_at: Time

        attr_accessor version: Integer

        def initialize: (
          id: String,
          archived_at: Time?,
          created_at: Time,
          description: String?,
          mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsMCPServerURLDefinition],
          metadata: ::Hash[Symbol, String],
          model: Anthropic::Beta::BetaManagedAgentsModelConfig,
          multiagent: Anthropic::Beta::BetaManagedAgentsMultiagent?,
          name: String,
          skills: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::skill],
          system_: String?,
          tools: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::tool],
          type: Anthropic::Models::Beta::BetaManagedAgentsAgent::type_,
          updated_at: Time,
          version: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          archived_at: Time?,
          created_at: Time,
          description: String?,
          mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsMCPServerURLDefinition],
          metadata: ::Hash[Symbol, String],
          model: Anthropic::Beta::BetaManagedAgentsModelConfig,
          multiagent: Anthropic::Beta::BetaManagedAgentsMultiagent?,
          name: String,
          skills: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::skill],
          system_: String?,
          tools: ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::tool],
          type: Anthropic::Models::Beta::BetaManagedAgentsAgent::type_,
          updated_at: Time,
          version: Integer
        }

        type skill =
          Anthropic::Beta::BetaManagedAgentsAnthropicSkill
          | Anthropic::Beta::BetaManagedAgentsCustomSkill

        module Skill
          extend Anthropic::Internal::Type::Union

          type type_ = :anthropic | :custom

          module Type
            extend Anthropic::Internal::Type::Enum

            ANTHROPIC: :anthropic
            CUSTOM: :custom

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::Skill::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::skill]

          def self.new:
            (
              type: :anthropic | "anthropic",
              skill_id: String,
              version: String
            ) -> Anthropic::Beta::BetaManagedAgentsAnthropicSkill
            | (
              type: :custom | "custom",
              skill_id: String,
              version: String
            ) -> Anthropic::Beta::BetaManagedAgentsCustomSkill
            | (
              type: Anthropic::Models::Beta::BetaManagedAgentsAgent::Skill::type_
              | String,
              skill_id: String,
              version: String
            ) -> Anthropic::Models::Beta::BetaManagedAgentsAgent::skill
        end

        type tool =
          Anthropic::Beta::BetaManagedAgentsAgentToolset20260401
          | Anthropic::Beta::BetaManagedAgentsMCPToolset
          | Anthropic::Beta::BetaManagedAgentsCustomTool

        module Tool
          extend Anthropic::Internal::Type::Union

          type type_ = :agent_toolset_20260401 | :mcp_toolset | :custom

          module Type
            extend Anthropic::Internal::Type::Enum

            AGENT_TOOLSET_20260401: :agent_toolset_20260401
            MCP_TOOLSET: :mcp_toolset
            CUSTOM: :custom

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::Tool::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::tool]

          def self.new:
            (
              type: :agent_toolset_20260401 | "agent_toolset_20260401",
              configs: ::Array[Anthropic::Models::Beta::beta_managed_agents_agent_tool_config],
              default_config: Anthropic::Beta::BetaManagedAgentsAgentToolsetDefaultConfig
            ) -> Anthropic::Beta::BetaManagedAgentsAgentToolset20260401
            | (
              type: :mcp_toolset | "mcp_toolset",
              configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfig],
              default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfig,
              mcp_server_name: String
            ) -> Anthropic::Beta::BetaManagedAgentsMCPToolset
            | (
              type: :custom | "custom",
              description: String,
              input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
              name: String
            ) -> Anthropic::Beta::BetaManagedAgentsCustomTool
            | (
              type: Anthropic::Models::Beta::BetaManagedAgentsAgent::Tool::type_
              | String,
              ?configs: ::Array[Anthropic::Models::Beta::beta_managed_agents_agent_tool_config]
              | ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfig],
              ?default_config: Anthropic::Beta::BetaManagedAgentsAgentToolsetDefaultConfig
              | Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfig,
              ?mcp_server_name: String,
              ?description: String,
              ?input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
              ?name: String
            ) -> Anthropic::Models::Beta::BetaManagedAgentsAgent::tool
        end

        type type_ = :agent

        module Type
          extend Anthropic::Internal::Type::Enum

          AGENT: :agent

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgent::type_]
        end
      end
    end
  end
end
