module Anthropic
  module Models
    class BetaCloudConfigParams = Beta::BetaCloudConfigParams

    module Beta
      type beta_cloud_config_params =
        {
          type: :cloud,
          networking: Anthropic::Models::Beta::BetaCloudConfigParams::networking?,
          packages: Anthropic::Beta::BetaPackagesParams?
        }

      class BetaCloudConfigParams < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :cloud

        attr_accessor networking: Anthropic::Models::Beta::BetaCloudConfigParams::networking?

        attr_accessor packages: Anthropic::Beta::BetaPackagesParams?

        def initialize: (
          ?networking: Anthropic::Models::Beta::BetaCloudConfigParams::networking?,
          ?packages: Anthropic::Beta::BetaPackagesParams?,
          ?type: :cloud
        ) -> void

        def to_hash: -> {
          type: :cloud,
          networking: Anthropic::Models::Beta::BetaCloudConfigParams::networking?,
          packages: Anthropic::Beta::BetaPackagesParams?
        }

        type networking =
          Anthropic::Beta::BetaUnrestrictedNetwork
          | Anthropic::Beta::BetaLimitedNetworkParams

        module Networking
          extend Anthropic::Internal::Type::Union

          type type_ = :unrestricted | :limited

          module Type
            extend Anthropic::Internal::Type::Enum

            UNRESTRICTED: :unrestricted
            LIMITED: :limited

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaCloudConfigParams::Networking::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaCloudConfigParams::networking]

          def self.new:
            (
              type: :unrestricted | "unrestricted"
            ) -> Anthropic::Beta::BetaUnrestrictedNetwork
            | (
              type: :limited | "limited",
              ?allow_mcp_servers: bool?,
              ?allow_package_managers: bool?,
              ?allowed_hosts: ::Array[String]?
            ) -> Anthropic::Beta::BetaLimitedNetworkParams
            | (
              type: Anthropic::Models::Beta::BetaCloudConfigParams::Networking::type_
              | String,
              ?allow_mcp_servers: bool?,
              ?allow_package_managers: bool?,
              ?allowed_hosts: ::Array[String]?
            ) -> Anthropic::Models::Beta::BetaCloudConfigParams::networking
        end
      end
    end
  end
end
