module Anthropic
  module Models
    class BetaCacheMissMessagesChanged = Beta::BetaCacheMissMessagesChanged

    module Beta
      type beta_cache_miss_messages_changed =
        { cache_missed_input_tokens: Integer, type: :messages_changed }

      class BetaCacheMissMessagesChanged < Anthropic::Internal::Type::BaseModel
        attr_accessor cache_missed_input_tokens: Integer

        attr_accessor type: :messages_changed

        def initialize: (
          cache_missed_input_tokens: Integer,
          ?type: :messages_changed
        ) -> void

        def to_hash: -> {
          cache_missed_input_tokens: Integer,
          type: :messages_changed
        }
      end
    end
  end
end
