module Anthropic
  module Models
    module BetaManagedAgentsDeploymentPausedReason = Beta::BetaManagedAgentsDeploymentPausedReason

    module Beta
      type beta_managed_agents_deployment_paused_reason =
        Anthropic::Beta::BetaManagedAgentsManualDeploymentPausedReason
        | Anthropic::Beta::BetaManagedAgentsErrorDeploymentPausedReason

      module BetaManagedAgentsDeploymentPausedReason
        extend Anthropic::Internal::Type::Union

        type type_ = :manual | :error

        module Type
          extend Anthropic::Internal::Type::Enum

          MANUAL: :manual
          ERROR: :error

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentPausedReason::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_deployment_paused_reason]

        def self.new:
          (
            type: :manual | "manual"
          ) -> Anthropic::Beta::BetaManagedAgentsManualDeploymentPausedReason
          | (
            type: :error | "error",
            error: Anthropic::Models::Beta::beta_managed_agents_deployment_paused_reason_error
          ) -> Anthropic::Beta::BetaManagedAgentsErrorDeploymentPausedReason
          | (
            type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentPausedReason::type_
            | String,
            ?error: Anthropic::Models::Beta::beta_managed_agents_deployment_paused_reason_error
          ) -> Anthropic::Models::Beta::beta_managed_agents_deployment_paused_reason
      end
    end
  end
end
