module Anthropic
  module Models
    class BetaManagedAgentsCustomToolInputSchema = Beta::BetaManagedAgentsCustomToolInputSchema

    module Beta
      type beta_managed_agents_custom_tool_input_schema =
        {
          type: :object,
          properties: ::Hash[Symbol, top]?,
          required: ::Array[String]?
        }

      class BetaManagedAgentsCustomToolInputSchema < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :object

        attr_accessor properties: ::Hash[Symbol, top]?

        attr_accessor required: ::Array[String]?

        def initialize: (
          ?properties: ::Hash[Symbol, top]?,
          ?required: ::Array[String]?,
          ?type: :object
        ) -> void

        def to_hash: -> {
          type: :object,
          properties: ::Hash[Symbol, top]?,
          required: ::Array[String]?
        }
      end
    end
  end
end
