module Anthropic
  module Models
    class BetaToolUseBlock = Beta::BetaToolUseBlock

    module Beta
      type beta_tool_use_block =
        {
          id: String,
          input: ::Hash[Symbol, top],
          name: String,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::BetaToolUseBlock::caller_,
          toolset_name: String?
        }

      class BetaToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: ::Hash[Symbol, top]

        attr_accessor name: String

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::BetaToolUseBlock::caller_?

        def caller_=: (
          Anthropic::Models::Beta::BetaToolUseBlock::caller_
        ) -> Anthropic::Models::Beta::BetaToolUseBlock::caller_

        attr_accessor toolset_name: String?

        def initialize: (
          id: String,
          input: ::Hash[Symbol, top],
          name: String,
          ?caller_: Anthropic::Models::Beta::BetaToolUseBlock::caller_,
          ?toolset_name: String?,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: ::Hash[Symbol, top],
          name: String,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::BetaToolUseBlock::caller_,
          toolset_name: String?
        }

        type caller_ =
          Anthropic::Beta::BetaDirectCaller
          | Anthropic::Beta::BetaServerToolCaller
          | Anthropic::Beta::BetaServerToolCaller20260120

        module Caller
          extend Anthropic::Internal::Type::Union

          type type_ =
            :direct | :code_execution_20250825 | :code_execution_20260120

          module Type
            extend Anthropic::Internal::Type::Enum

            DIRECT: :direct
            CODE_EXECUTION_20250825: :code_execution_20250825
            CODE_EXECUTION_20260120: :code_execution_20260120

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaToolUseBlock::Caller::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaToolUseBlock::caller_]

          def self.new:
            (type: :direct | "direct") -> Anthropic::Beta::BetaDirectCaller
            | (
              type: :code_execution_20250825 | "code_execution_20250825",
              tool_id: String
            ) -> Anthropic::Beta::BetaServerToolCaller
            | (
              type: :code_execution_20260120 | "code_execution_20260120",
              tool_id: String
            ) -> Anthropic::Beta::BetaServerToolCaller20260120
            | (
              type: Anthropic::Models::Beta::BetaToolUseBlock::Caller::type_
              | String,
              ?tool_id: String
            ) -> Anthropic::Models::Beta::BetaToolUseBlock::caller_
        end
      end
    end
  end
end
