module Anthropic
  module Models
    class BetaBrowserScrollToConfig = Beta::BetaBrowserScrollToConfig

    module Beta
      type beta_browser_scroll_to_config =
        { defer_loading: bool?, enabled: bool? }

      class BetaBrowserScrollToConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
