module Anthropic
  module Models
    class BetaFallbackBlock = Beta::BetaFallbackBlock

    module Beta
      type beta_fallback_block =
        {
          from: Anthropic::Beta::BetaFallbackInfo,
          to: Anthropic::Beta::BetaFallbackInfo,
          trigger: Anthropic::Beta::BetaFallbackRefusalTrigger,
          type: :fallback
        }

      class BetaFallbackBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor from: Anthropic::Beta::BetaFallbackInfo

        attr_accessor to: Anthropic::Beta::BetaFallbackInfo

        attr_accessor trigger: Anthropic::Beta::BetaFallbackRefusalTrigger

        attr_accessor type: :fallback

        def initialize: (
          from: Anthropic::Beta::BetaFallbackInfo,
          to: Anthropic::Beta::BetaFallbackInfo,
          trigger: Anthropic::Beta::BetaFallbackRefusalTrigger,
          ?type: :fallback
        ) -> void

        def to_hash: -> {
          from: Anthropic::Beta::BetaFallbackInfo,
          to: Anthropic::Beta::BetaFallbackInfo,
          trigger: Anthropic::Beta::BetaFallbackRefusalTrigger,
          type: :fallback
        }
      end
    end
  end
end
