module Anthropic
  module Models
    class BetaManagedAgentsUserLocation = Beta::BetaManagedAgentsUserLocation

    module Beta
      type beta_managed_agents_user_location =
        {
          type: :approximate,
          city: String?,
          country: String?,
          region: String?,
          timezone: String?
        }

      class BetaManagedAgentsUserLocation < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :approximate

        attr_accessor city: String?

        attr_accessor country: String?

        attr_accessor region: String?

        attr_accessor timezone: String?

        def initialize: (
          ?city: String?,
          ?country: String?,
          ?region: String?,
          ?timezone: String?,
          ?type: :approximate
        ) -> void

        def to_hash: -> {
          type: :approximate,
          city: String?,
          country: String?,
          region: String?,
          timezone: String?
        }
      end
    end
  end
end
