module Anthropic
  module Models
    class BetaEnvironment = Beta::BetaEnvironment

    module Beta
      type beta_environment =
        {
          id: String,
          archived_at: String?,
          config: Anthropic::Models::Beta::BetaEnvironment::config,
          created_at: String,
          description: String?,
          metadata: ::Hash[Symbol, String],
          name: String,
          type: :environment,
          updated_at: String,
          scope: Anthropic::Models::Beta::BetaEnvironment::scope
        }

      class BetaEnvironment < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived_at: String?

        attr_accessor config: Anthropic::Models::Beta::BetaEnvironment::config

        attr_accessor created_at: String

        attr_accessor description: String?

        attr_accessor metadata: ::Hash[Symbol, String]

        attr_accessor name: String

        attr_accessor type: :environment

        attr_accessor updated_at: String

        attr_reader scope: Anthropic::Models::Beta::BetaEnvironment::scope?

        def scope=: (
          Anthropic::Models::Beta::BetaEnvironment::scope
        ) -> Anthropic::Models::Beta::BetaEnvironment::scope

        def initialize: (
          id: String,
          archived_at: String?,
          config: Anthropic::Models::Beta::BetaEnvironment::config,
          created_at: String,
          description: String?,
          metadata: ::Hash[Symbol, String],
          name: String,
          updated_at: String,
          ?scope: Anthropic::Models::Beta::BetaEnvironment::scope,
          ?type: :environment
        ) -> void

        def to_hash: -> {
          id: String,
          archived_at: String?,
          config: Anthropic::Models::Beta::BetaEnvironment::config,
          created_at: String,
          description: String?,
          metadata: ::Hash[Symbol, String],
          name: String,
          type: :environment,
          updated_at: String,
          scope: Anthropic::Models::Beta::BetaEnvironment::scope
        }

        type config =
          Anthropic::Beta::BetaCloudConfig
          | Anthropic::Beta::BetaSelfHostedConfig

        module Config
          extend Anthropic::Internal::Type::Union

          type type_ = :cloud | :self_hosted

          module Type
            extend Anthropic::Internal::Type::Enum

            CLOUD: :cloud
            SELF_HOSTED: :self_hosted

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaEnvironment::Config::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaEnvironment::config]

          def self.new:
            (
              type: :cloud | "cloud",
              networking: Anthropic::Models::Beta::BetaCloudConfig::networking,
              packages: Anthropic::Beta::BetaPackages
            ) -> Anthropic::Beta::BetaCloudConfig
            | (
              type: :self_hosted | "self_hosted"
            ) -> Anthropic::Beta::BetaSelfHostedConfig
            | (
              type: Anthropic::Models::Beta::BetaEnvironment::Config::type_
              | String,
              ?networking: Anthropic::Models::Beta::BetaCloudConfig::networking,
              ?packages: Anthropic::Beta::BetaPackages
            ) -> Anthropic::Models::Beta::BetaEnvironment::config
        end

        type scope = :organization | :account

        module Scope
          extend Anthropic::Internal::Type::Enum

          ORGANIZATION: :organization
          ACCOUNT: :account

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaEnvironment::scope]
        end
      end
    end
  end
end
