module Anthropic
  module Models
    class BetaManagedAgentsAutoPolicy = Beta::BetaManagedAgentsAutoPolicy

    module Beta
      type beta_managed_agents_auto_policy = { type: :auto }

      class BetaManagedAgentsAutoPolicy < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :auto

        def initialize: (?type: :auto) -> void

        def to_hash: -> { type: :auto }
      end
    end
  end
end
