module Anthropic
  module Models
    module BetaManagedAgentsDeploymentInitialEventParams = Beta::BetaManagedAgentsDeploymentInitialEventParams

    module Beta
      type beta_managed_agents_deployment_initial_event_params =
        Anthropic::Beta::Sessions::BetaManagedAgentsUserMessageEventParams
        | Anthropic::Beta::Sessions::BetaManagedAgentsUserDefineOutcomeEventParams
        | Anthropic::Beta::Sessions::BetaManagedAgentsSystemMessageEventParams

      module BetaManagedAgentsDeploymentInitialEventParams
        extend Anthropic::Internal::Type::Union

        type type_ =
          :"user.message" | :"user.define_outcome" | :"system.message"

        module Type
          extend Anthropic::Internal::Type::Enum

          USER_MESSAGE: :"user.message"
          USER_DEFINE_OUTCOME: :"user.define_outcome"
          SYSTEM_MESSAGE: :"system.message"

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsDeploymentInitialEventParams::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_deployment_initial_event_params]

        def self.new:
          (
            type: :"user.message" | "user.message",
            content: ::Array[Anthropic::Models::Beta::Sessions::BetaManagedAgentsUserMessageEventParams::content]
          ) -> Anthropic::Beta::Sessions::BetaManagedAgentsUserMessageEventParams
          | (
            type: :"user.define_outcome" | "user.define_outcome",
            description: String,
            rubric: Anthropic::Models::Beta::Sessions::BetaManagedAgentsUserDefineOutcomeEventParams::rubric,
            ?max_iterations: Integer?
          ) -> Anthropic::Beta::Sessions::BetaManagedAgentsUserDefineOutcomeEventParams
          | (
            type: :"system.message" | "system.message",
            content: ::Array[Anthropic::Beta::BetaManagedAgentsSystemContentBlock]
          ) -> Anthropic::Beta::Sessions::BetaManagedAgentsSystemMessageEventParams
          | (
            type: Anthropic::Models::Beta::BetaManagedAgentsDeploymentInitialEventParams::type_
            | String,
            ?content: ::Array[Anthropic::Models::Beta::Sessions::BetaManagedAgentsUserMessageEventParams::content]
            | ::Array[Anthropic::Beta::BetaManagedAgentsSystemContentBlock],
            ?description: String,
            ?rubric: Anthropic::Models::Beta::Sessions::BetaManagedAgentsUserDefineOutcomeEventParams::rubric,
            ?max_iterations: Integer?
          ) -> Anthropic::Models::Beta::beta_managed_agents_deployment_initial_event_params
      end
    end
  end
end
