module Anthropic
  module Models
    class BetaRequestToolRemovalBlock = Beta::BetaRequestToolRemovalBlock

    module Beta
      type beta_request_tool_removal_block =
        {
          tool: Anthropic::Models::Beta::BetaRequestToolRemovalBlock::tool,
          type: :tool_removal,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?
        }

      class BetaRequestToolRemovalBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor tool: Anthropic::Models::Beta::BetaRequestToolRemovalBlock::tool

        attr_accessor type: :tool_removal

        attr_accessor cache_control: Anthropic::Beta::BetaCacheControlEphemeral?

        def initialize: (
          tool: Anthropic::Models::Beta::BetaRequestToolRemovalBlock::tool,
          ?cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          ?type: :tool_removal
        ) -> void

        def to_hash: -> {
          tool: Anthropic::Models::Beta::BetaRequestToolRemovalBlock::tool,
          type: :tool_removal,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?
        }

        type tool =
          Anthropic::Beta::BetaToolChangeToolReference
          | Anthropic::Beta::BetaToolChangeMCPToolReference
          | Anthropic::Beta::BetaToolChangeMCPToolsetReference

        module Tool
          extend Anthropic::Internal::Type::Union

          type type_ =
            :tool_reference | :mcp_tool_reference | :mcp_toolset_reference

          module Type
            extend Anthropic::Internal::Type::Enum

            TOOL_REFERENCE: :tool_reference
            MCP_TOOL_REFERENCE: :mcp_tool_reference
            MCP_TOOLSET_REFERENCE: :mcp_toolset_reference

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaRequestToolRemovalBlock::Tool::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaRequestToolRemovalBlock::tool]

          def self.new:
            (
              type: :tool_reference | "tool_reference",
              name: String
            ) -> Anthropic::Beta::BetaToolChangeToolReference
            | (
              type: :mcp_tool_reference | "mcp_tool_reference",
              name: String,
              server_name: String
            ) -> Anthropic::Beta::BetaToolChangeMCPToolReference
            | (
              type: :mcp_toolset_reference | "mcp_toolset_reference",
              server_name: String
            ) -> Anthropic::Beta::BetaToolChangeMCPToolsetReference
            | (
              type: Anthropic::Models::Beta::BetaRequestToolRemovalBlock::Tool::type_
              | String,
              ?name: String,
              ?server_name: String
            ) -> Anthropic::Models::Beta::BetaRequestToolRemovalBlock::tool
        end
      end
    end
  end
end
