module Anthropic
  module Models
    class BetaManagedAgentsMCPToolset = Beta::BetaManagedAgentsMCPToolset

    module Beta
      type beta_managed_agents_mcp_toolset =
        {
          configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfig],
          default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfig,
          mcp_server_name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolset::type_
        }

      class BetaManagedAgentsMCPToolset < Anthropic::Internal::Type::BaseModel
        attr_accessor configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfig]

        attr_accessor default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfig

        attr_accessor mcp_server_name: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolset::type_

        def initialize: (
          configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfig],
          default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfig,
          mcp_server_name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolset::type_
        ) -> void

        def to_hash: -> {
          configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfig],
          default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfig,
          mcp_server_name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolset::type_
        }

        type type_ = :mcp_toolset

        module Type
          extend Anthropic::Internal::Type::Enum

          MCP_TOOLSET: :mcp_toolset

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMCPToolset::type_]
        end
      end
    end
  end
end
