module Anthropic
  module Models
    class BetaManagedAgentsMultiagentSelfParams = Beta::BetaManagedAgentsMultiagentSelfParams

    module Beta
      type beta_managed_agents_multiagent_self_params =
        {
          type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentSelfParams::type_
        }

      class BetaManagedAgentsMultiagentSelfParams < Anthropic::Internal::Type::BaseModel
        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentSelfParams::type_

        def initialize: (
          type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentSelfParams::type_
        ) -> void

        def to_hash: -> {
          type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentSelfParams::type_
        }

        type type_ = :self

        module Type
          extend Anthropic::Internal::Type::Enum

          SELF: :self

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMultiagentSelfParams::type_]
        end
      end
    end
  end
end
