module Anthropic
  module Models
    class BetaManagedAgentsSessionMultiagentCoordinator = Beta::BetaManagedAgentsSessionMultiagentCoordinator

    module Beta
      type beta_managed_agents_session_multiagent_coordinator =
        {
          agents: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::agent],
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::type_
        }

      class BetaManagedAgentsSessionMultiagentCoordinator < Anthropic::Internal::Type::BaseModel
        attr_accessor agents: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::agent]

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::type_

        def initialize: (
          agents: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::agent],
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::type_
        ) -> void

        def to_hash: -> {
          agents: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::agent],
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::type_
        }

        type agent =
          Anthropic::Beta::BetaManagedAgentsSessionThreadAgent
          | Anthropic::Beta::BetaManagedAgentsAdvisor

        module Agent
          extend Anthropic::Internal::Type::Union

          type type_ = :agent | :advisor

          module Type
            extend Anthropic::Internal::Type::Enum

            AGENT: :agent
            ADVISOR: :advisor

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::Agent::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::agent]

          def self.new:
            (
              type: :agent | "agent",
              id: String,
              description: String?,
              mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsMCPServerURLDefinition],
              model: Anthropic::Beta::BetaManagedAgentsModelConfig,
              name: String,
              skills: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionThreadAgent::skill],
              system_: String?,
              tools: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionThreadAgent::tool],
              version: Integer
            ) -> Anthropic::Beta::BetaManagedAgentsSessionThreadAgent
            | (
              type: :advisor | "advisor",
              model: String
            ) -> Anthropic::Beta::BetaManagedAgentsAdvisor
            | (
              type: Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::Agent::type_
              | String,
              model: Anthropic::Beta::BetaManagedAgentsModelConfig | String,
              ?id: String,
              ?description: String?,
              ?mcp_servers: ::Array[Anthropic::Beta::BetaManagedAgentsMCPServerURLDefinition],
              ?name: String,
              ?skills: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionThreadAgent::skill],
              ?system_: String?,
              ?tools: ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionThreadAgent::tool],
              ?version: Integer
            ) -> Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::agent
        end

        type type_ = :coordinator

        module Type
          extend Anthropic::Internal::Type::Enum

          COORDINATOR: :coordinator

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionMultiagentCoordinator::type_]
        end
      end
    end
  end
end
