module Anthropic
  module Models
    class BetaManagedAgentsCustomTool = Beta::BetaManagedAgentsCustomTool

    module Beta
      type beta_managed_agents_custom_tool =
        {
          description: String,
          input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
          name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsCustomTool::type_
        }

      class BetaManagedAgentsCustomTool < Anthropic::Internal::Type::BaseModel
        attr_accessor description: String

        attr_accessor input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema

        attr_accessor name: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsCustomTool::type_

        def initialize: (
          description: String,
          input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
          name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsCustomTool::type_
        ) -> void

        def to_hash: -> {
          description: String,
          input_schema: Anthropic::Beta::BetaManagedAgentsCustomToolInputSchema,
          name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsCustomTool::type_
        }

        type type_ = :custom

        module Type
          extend Anthropic::Internal::Type::Enum

          CUSTOM: :custom

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsCustomTool::type_]
        end
      end
    end
  end
end
