module Anthropic
  module Models
    class BetaComputerWaitConfig = Beta::BetaComputerWaitConfig

    module Beta
      type beta_computer_wait_config = { defer_loading: bool?, enabled: bool? }

      class BetaComputerWaitConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
