module Anthropic
  module Models
    class BetaManagedAgentsCustomSkill = Beta::BetaManagedAgentsCustomSkill

    module Beta
      type beta_managed_agents_custom_skill =
        {
          skill_id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsCustomSkill::type_,
          version: String
        }

      class BetaManagedAgentsCustomSkill < Anthropic::Internal::Type::BaseModel
        attr_accessor skill_id: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsCustomSkill::type_

        attr_accessor version: String

        def initialize: (
          skill_id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsCustomSkill::type_,
          version: String
        ) -> void

        def to_hash: -> {
          skill_id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsCustomSkill::type_,
          version: String
        }

        type type_ = :custom

        module Type
          extend Anthropic::Internal::Type::Enum

          CUSTOM: :custom

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsCustomSkill::type_]
        end
      end
    end
  end
end
