module Anthropic
  module Models
    class BetaSelfHostedConfigParams = Beta::BetaSelfHostedConfigParams

    module Beta
      type beta_self_hosted_config_params = { type: :self_hosted }

      class BetaSelfHostedConfigParams < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :self_hosted

        def initialize: (?type: :self_hosted) -> void

        def to_hash: -> { type: :self_hosted }
      end
    end
  end
end
