module Anthropic
  module Models
    class BetaManagedAgentsMultiagentCoordinatorParams = Beta::BetaManagedAgentsMultiagentCoordinatorParams

    module Beta
      type beta_managed_agents_multiagent_coordinator_params =
        {
          agents: ::Array[Anthropic::Models::Beta::beta_managed_agents_multiagent_roster_entry_params],
          type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentCoordinatorParams::type_
        }

      class BetaManagedAgentsMultiagentCoordinatorParams < Anthropic::Internal::Type::BaseModel
        attr_accessor agents: ::Array[Anthropic::Models::Beta::beta_managed_agents_multiagent_roster_entry_params]

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentCoordinatorParams::type_

        def initialize: (
          agents: ::Array[Anthropic::Models::Beta::beta_managed_agents_multiagent_roster_entry_params],
          type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentCoordinatorParams::type_
        ) -> void

        def to_hash: -> {
          agents: ::Array[Anthropic::Models::Beta::beta_managed_agents_multiagent_roster_entry_params],
          type: Anthropic::Models::Beta::BetaManagedAgentsMultiagentCoordinatorParams::type_
        }

        type type_ = :coordinator

        module Type
          extend Anthropic::Internal::Type::Enum

          COORDINATOR: :coordinator

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMultiagentCoordinatorParams::type_]
        end
      end
    end
  end
end
