module Anthropic
  module Models
    class BetaContextManagementResponse = Beta::BetaContextManagementResponse

    module Beta
      type beta_context_management_response =
        {
          applied_edits: ::Array[Anthropic::Models::Beta::BetaContextManagementResponse::applied_edit]
        }

      class BetaContextManagementResponse < Anthropic::Internal::Type::BaseModel
        attr_accessor applied_edits: ::Array[Anthropic::Models::Beta::BetaContextManagementResponse::applied_edit]

        def initialize: (
          applied_edits: ::Array[Anthropic::Models::Beta::BetaContextManagementResponse::applied_edit]
        ) -> void

        def to_hash: -> {
          applied_edits: ::Array[Anthropic::Models::Beta::BetaContextManagementResponse::applied_edit]
        }

        type applied_edit =
          Anthropic::Beta::BetaClearToolUses20250919EditResponse
          | Anthropic::Beta::BetaClearThinking20251015EditResponse

        module AppliedEdit
          extend Anthropic::Internal::Type::Union

          type type_ = :clear_tool_uses_20250919 | :clear_thinking_20251015

          module Type
            extend Anthropic::Internal::Type::Enum

            CLEAR_TOOL_USES_20250919: :clear_tool_uses_20250919
            CLEAR_THINKING_20251015: :clear_thinking_20251015

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaContextManagementResponse::AppliedEdit::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaContextManagementResponse::applied_edit]

          def self.new:
            (
              type: :clear_tool_uses_20250919 | "clear_tool_uses_20250919",
              cleared_input_tokens: Integer,
              cleared_tool_uses: Integer
            ) -> Anthropic::Beta::BetaClearToolUses20250919EditResponse
            | (
              type: :clear_thinking_20251015 | "clear_thinking_20251015",
              cleared_input_tokens: Integer,
              cleared_thinking_turns: Integer
            ) -> Anthropic::Beta::BetaClearThinking20251015EditResponse
            | (
              type: Anthropic::Models::Beta::BetaContextManagementResponse::AppliedEdit::type_
              | String,
              cleared_input_tokens: Integer,
              ?cleared_tool_uses: Integer,
              ?cleared_thinking_turns: Integer
            ) -> Anthropic::Models::Beta::BetaContextManagementResponse::applied_edit
        end
      end
    end
  end
end
