module Anthropic
  module Models
    module BetaRawMessageStreamEvent = Beta::BetaRawMessageStreamEvent

    module Beta
      type beta_raw_message_stream_event =
        Anthropic::Beta::BetaRawMessageStartEvent
        | Anthropic::Beta::BetaRawMessageDeltaEvent
        | Anthropic::Beta::BetaRawMessageStopEvent
        | Anthropic::Beta::BetaRawContentBlockStartEvent
        | Anthropic::Beta::BetaRawContentBlockDeltaEvent
        | Anthropic::Beta::BetaRawContentBlockStopEvent

      module BetaRawMessageStreamEvent
        extend Anthropic::Internal::Type::Union

        type type_ =
          :message_start
          | :message_delta
          | :message_stop
          | :content_block_start
          | :content_block_delta
          | :content_block_stop

        module Type
          extend Anthropic::Internal::Type::Enum

          MESSAGE_START: :message_start
          MESSAGE_DELTA: :message_delta
          MESSAGE_STOP: :message_stop
          CONTENT_BLOCK_START: :content_block_start
          CONTENT_BLOCK_DELTA: :content_block_delta
          CONTENT_BLOCK_STOP: :content_block_stop

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaRawMessageStreamEvent::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_raw_message_stream_event]

        def self.new:
          (
            type: :message_start | "message_start",
            message: Anthropic::Beta::BetaMessage
          ) -> Anthropic::Beta::BetaRawMessageStartEvent
          | (
            type: :message_delta | "message_delta",
            context_management: Anthropic::Beta::BetaContextManagementResponse?,
            delta: Anthropic::Beta::BetaRawMessageDeltaEvent::Delta,
            usage: Anthropic::Beta::BetaMessageDeltaUsage,
            ?input_transformations: ::Array[Anthropic::Models::Beta::beta_input_transformation]?
          ) -> Anthropic::Beta::BetaRawMessageDeltaEvent
          | (
            type: :message_stop | "message_stop"
          ) -> Anthropic::Beta::BetaRawMessageStopEvent
          | (
            type: :content_block_start | "content_block_start",
            content_block: Anthropic::Models::Beta::BetaRawContentBlockStartEvent::content_block,
            index: Integer
          ) -> Anthropic::Beta::BetaRawContentBlockStartEvent
          | (
            type: :content_block_delta | "content_block_delta",
            delta: Anthropic::Models::Beta::beta_raw_content_block_delta,
            index: Integer
          ) -> Anthropic::Beta::BetaRawContentBlockDeltaEvent
          | (
            type: :content_block_stop | "content_block_stop",
            index: Integer
          ) -> Anthropic::Beta::BetaRawContentBlockStopEvent
          | (
            type: Anthropic::Models::Beta::BetaRawMessageStreamEvent::type_
            | String,
            ?message: Anthropic::Beta::BetaMessage,
            ?context_management: Anthropic::Beta::BetaContextManagementResponse?,
            ?delta: Anthropic::Beta::BetaRawMessageDeltaEvent::Delta
            | Anthropic::Models::Beta::beta_raw_content_block_delta,
            ?usage: Anthropic::Beta::BetaMessageDeltaUsage,
            ?input_transformations: ::Array[Anthropic::Models::Beta::beta_input_transformation]?,
            ?content_block: Anthropic::Models::Beta::BetaRawContentBlockStartEvent::content_block,
            ?index: Integer
          ) -> Anthropic::Models::Beta::beta_raw_message_stream_event
      end
    end
  end
end
