module Anthropic
  module Models
    class BetaBrowserReadPageConfig = Beta::BetaBrowserReadPageConfig

    module Beta
      type beta_browser_read_page_config =
        { defer_loading: bool?, enabled: bool? }

      class BetaBrowserReadPageConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor defer_loading: bool?

        attr_accessor enabled: bool?

        def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

        def to_hash: -> { defer_loading: bool?, enabled: bool? }
      end
    end
  end
end
