module Anthropic
  module Models
    class BetaManagedAgentsMCPToolConfigParams = Beta::BetaManagedAgentsMCPToolConfigParams

    module Beta
      type beta_managed_agents_mcp_tool_config_params =
        {
          name: String,
          enabled: bool?,
          permission_policy: Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::permission_policy?
        }

      class BetaManagedAgentsMCPToolConfigParams < Anthropic::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor enabled: bool?

        attr_accessor permission_policy: Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::permission_policy?

        def initialize: (
          name: String,
          ?enabled: bool?,
          ?permission_policy: Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::permission_policy?
        ) -> void

        def to_hash: -> {
          name: String,
          enabled: bool?,
          permission_policy: Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::permission_policy?
        }

        type permission_policy =
          Anthropic::Beta::BetaManagedAgentsAlwaysAllowPolicy
          | Anthropic::Beta::BetaManagedAgentsAlwaysAskPolicy
          | Anthropic::Beta::BetaManagedAgentsAutoPolicy

        module PermissionPolicy
          extend Anthropic::Internal::Type::Union

          type type_ = :always_allow | :always_ask | :auto

          module Type
            extend Anthropic::Internal::Type::Enum

            ALWAYS_ALLOW: :always_allow
            ALWAYS_ASK: :always_ask
            AUTO: :auto

            def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::PermissionPolicy::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::permission_policy]

          def self.new:
            (
              type: :always_allow | "always_allow"
            ) -> Anthropic::Beta::BetaManagedAgentsAlwaysAllowPolicy
            | (
              type: :always_ask | "always_ask"
            ) -> Anthropic::Beta::BetaManagedAgentsAlwaysAskPolicy
            | (
              type: :auto | "auto"
            ) -> Anthropic::Beta::BetaManagedAgentsAutoPolicy
            | (
              type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::PermissionPolicy::type_
              | String
            ) -> Anthropic::Models::Beta::BetaManagedAgentsMCPToolConfigParams::permission_policy
        end
      end
    end
  end
end
