module Anthropic
  module Models
    class BetaManagedAgentsSessionUpdatedEvent = Beta::BetaManagedAgentsSessionUpdatedEvent

    module Beta
      type beta_managed_agents_session_updated_event =
        {
          id: String,
          processed_at: Time,
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionUpdatedEvent::type_,
          agent: Anthropic::Beta::BetaManagedAgentsSessionAgent?,
          budget: Anthropic::Beta::BetaManagedAgentsBudgetLimit?,
          metadata: ::Hash[Symbol, String],
          title: String?
        }

      class BetaManagedAgentsSessionUpdatedEvent < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor processed_at: Time

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsSessionUpdatedEvent::type_

        attr_accessor agent: Anthropic::Beta::BetaManagedAgentsSessionAgent?

        attr_accessor budget: Anthropic::Beta::BetaManagedAgentsBudgetLimit?

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor title: String?

        def initialize: (
          id: String,
          processed_at: Time,
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionUpdatedEvent::type_,
          ?agent: Anthropic::Beta::BetaManagedAgentsSessionAgent?,
          ?budget: Anthropic::Beta::BetaManagedAgentsBudgetLimit?,
          ?metadata: ::Hash[Symbol, String],
          ?title: String?
        ) -> void

        def to_hash: -> {
          id: String,
          processed_at: Time,
          type: Anthropic::Models::Beta::BetaManagedAgentsSessionUpdatedEvent::type_,
          agent: Anthropic::Beta::BetaManagedAgentsSessionAgent?,
          budget: Anthropic::Beta::BetaManagedAgentsBudgetLimit?,
          metadata: ::Hash[Symbol, String],
          title: String?
        }

        type type_ = :"session.updated"

        module Type
          extend Anthropic::Internal::Type::Enum

          SESSION_UPDATED: :"session.updated"

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsSessionUpdatedEvent::type_]
        end
      end
    end
  end
end
