module Anthropic
  module Models
    class BetaOutputConfig = Beta::BetaOutputConfig

    module Beta
      type beta_output_config =
        {
          effort: Anthropic::Models::Beta::BetaOutputConfig::effort?,
          format_: Anthropic::Beta::BetaJSONOutputFormat?,
          task_budget: Anthropic::Beta::BetaTokenTaskBudget?
        }

      class BetaOutputConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor effort: Anthropic::Models::Beta::BetaOutputConfig::effort?

        attr_accessor format_: Anthropic::Beta::BetaJSONOutputFormat?

        attr_accessor task_budget: Anthropic::Beta::BetaTokenTaskBudget?

        def initialize: (
          ?effort: Anthropic::Models::Beta::BetaOutputConfig::effort?,
          ?format_: Anthropic::Beta::BetaJSONOutputFormat?,
          ?task_budget: Anthropic::Beta::BetaTokenTaskBudget?
        ) -> void

        def to_hash: -> {
          effort: Anthropic::Models::Beta::BetaOutputConfig::effort?,
          format_: Anthropic::Beta::BetaJSONOutputFormat?,
          task_budget: Anthropic::Beta::BetaTokenTaskBudget?
        }

        type effort = :low | :medium | :high | :xhigh | :max

        module Effort
          extend Anthropic::Internal::Type::Enum

          LOW: :low
          MEDIUM: :medium
          HIGH: :high
          XHIGH: :xhigh
          MAX: :max

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaOutputConfig::effort]
        end
      end
    end
  end
end
