module Anthropic
  module Models
    class BetaManagedAgentsURLMCPServerParams = Beta::BetaManagedAgentsURLMCPServerParams

    module Beta
      type beta_managed_agents_urlmcp_server_params =
        {
          name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsURLMCPServerParams::type_,
          url: String
        }

      class BetaManagedAgentsURLMCPServerParams < Anthropic::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsURLMCPServerParams::type_

        attr_accessor url: String

        def initialize: (
          name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsURLMCPServerParams::type_,
          url: String
        ) -> void

        def to_hash: -> {
          name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsURLMCPServerParams::type_,
          url: String
        }

        type type_ = :url

        module Type
          extend Anthropic::Internal::Type::Enum

          URL: :url

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsURLMCPServerParams::type_]
        end
      end
    end
  end
end
