module Anthropic
  module Models
    class BetaManagedAgentsMCPToolsetParams = Beta::BetaManagedAgentsMCPToolsetParams

    module Beta
      type beta_managed_agents_mcp_toolset_params =
        {
          mcp_server_name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolsetParams::type_,
          configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams],
          default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfigParams?
        }

      class BetaManagedAgentsMCPToolsetParams < Anthropic::Internal::Type::BaseModel
        attr_accessor mcp_server_name: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolsetParams::type_

        attr_reader configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams]?

        def configs=: (
          ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams]
        ) -> ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams]

        attr_accessor default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfigParams?

        def initialize: (
          mcp_server_name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolsetParams::type_,
          ?configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams],
          ?default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfigParams?
        ) -> void

        def to_hash: -> {
          mcp_server_name: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsMCPToolsetParams::type_,
          configs: ::Array[Anthropic::Beta::BetaManagedAgentsMCPToolConfigParams],
          default_config: Anthropic::Beta::BetaManagedAgentsMCPToolsetDefaultConfigParams?
        }

        type type_ = :mcp_toolset

        module Type
          extend Anthropic::Internal::Type::Enum

          MCP_TOOLSET: :mcp_toolset

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsMCPToolsetParams::type_]
        end
      end
    end
  end
end
