module Anthropic
  module Models
    module BetaRawContentBlockDelta = Beta::BetaRawContentBlockDelta

    module Beta
      type beta_raw_content_block_delta =
        Anthropic::Beta::BetaTextDelta
        | Anthropic::Beta::BetaInputJSONDelta
        | Anthropic::Beta::BetaCitationsDelta
        | Anthropic::Beta::BetaThinkingDelta
        | Anthropic::Beta::BetaSignatureDelta
        | Anthropic::Beta::BetaCompactionContentBlockDelta

      module BetaRawContentBlockDelta
        extend Anthropic::Internal::Type::Union

        type type_ =
          :text_delta
          | :input_json_delta
          | :citations_delta
          | :thinking_delta
          | :signature_delta
          | :compaction_delta

        module Type
          extend Anthropic::Internal::Type::Enum

          TEXT_DELTA: :text_delta
          INPUT_JSON_DELTA: :input_json_delta
          CITATIONS_DELTA: :citations_delta
          THINKING_DELTA: :thinking_delta
          SIGNATURE_DELTA: :signature_delta
          COMPACTION_DELTA: :compaction_delta

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaRawContentBlockDelta::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_raw_content_block_delta]

        def self.new:
          (
            type: :text_delta | "text_delta",
            text: String
          ) -> Anthropic::Beta::BetaTextDelta
          | (
            type: :input_json_delta | "input_json_delta",
            partial_json: String
          ) -> Anthropic::Beta::BetaInputJSONDelta
          | (
            type: :citations_delta | "citations_delta",
            citation: Anthropic::Models::Beta::BetaCitationsDelta::citation
          ) -> Anthropic::Beta::BetaCitationsDelta
          | (
            type: :thinking_delta | "thinking_delta",
            estimated_tokens: Integer?,
            thinking: String
          ) -> Anthropic::Beta::BetaThinkingDelta
          | (
            type: :signature_delta | "signature_delta",
            signature: String
          ) -> Anthropic::Beta::BetaSignatureDelta
          | (
            type: :compaction_delta | "compaction_delta",
            content: String?,
            encrypted_content: String?
          ) -> Anthropic::Beta::BetaCompactionContentBlockDelta
          | (
            type: Anthropic::Models::Beta::BetaRawContentBlockDelta::type_
            | String,
            ?text: String,
            ?partial_json: String,
            ?citation: Anthropic::Models::Beta::BetaCitationsDelta::citation,
            ?estimated_tokens: Integer?,
            ?thinking: String,
            ?signature: String,
            ?content: String?,
            ?encrypted_content: String?
          ) -> Anthropic::Models::Beta::beta_raw_content_block_delta
      end
    end
  end
end
