module Anthropic
  module Models
    class BetaManagedAgentsAgentParams = Beta::BetaManagedAgentsAgentParams

    module Beta
      type beta_managed_agents_agent_params =
        {
          id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsAgentParams::type_,
          version: Integer
        }

      class BetaManagedAgentsAgentParams < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor type: Anthropic::Models::Beta::BetaManagedAgentsAgentParams::type_

        attr_reader version: Integer?

        def version=: (Integer) -> Integer

        def initialize: (
          id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsAgentParams::type_,
          ?version: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          type: Anthropic::Models::Beta::BetaManagedAgentsAgentParams::type_,
          version: Integer
        }

        type type_ = :agent

        module Type
          extend Anthropic::Internal::Type::Enum

          AGENT: :agent

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaManagedAgentsAgentParams::type_]
        end
      end
    end
  end
end
