module Anthropic
  module Models
    class BetaWebFetchURLSourceAll = Beta::BetaWebFetchURLSourceAll

    module Beta
      type beta_web_fetch_url_source_all = { type: :all }

      class BetaWebFetchURLSourceAll < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :all

        def initialize: (?type: :all) -> void

        def to_hash: -> { type: :all }
      end
    end
  end
end
