module Anthropic
  module Models
    module Beta
      type dream_create_params =
        {
          inputs: ::Array[Anthropic::Models::Beta::beta_dream_input],
          model: Anthropic::Models::Beta::DreamCreateParams::model,
          instructions: String?,
          output_behavior: Anthropic::Models::Beta::beta_output_behavior,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String
        }
        & Anthropic::Internal::Type::request_parameters

      class DreamCreateParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor inputs: ::Array[Anthropic::Models::Beta::beta_dream_input]

        attr_accessor model: Anthropic::Models::Beta::DreamCreateParams::model

        attr_accessor instructions: String?

        attr_reader output_behavior: Anthropic::Models::Beta::beta_output_behavior?

        def output_behavior=: (
          Anthropic::Models::Beta::beta_output_behavior
        ) -> Anthropic::Models::Beta::beta_output_behavior

        attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

        def betas=: (
          ::Array[Anthropic::Models::anthropic_beta]
        ) -> ::Array[Anthropic::Models::anthropic_beta]

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        def initialize: (
          inputs: ::Array[Anthropic::Models::Beta::beta_dream_input],
          model: Anthropic::Models::Beta::DreamCreateParams::model,
          ?instructions: String?,
          ?output_behavior: Anthropic::Models::Beta::beta_output_behavior,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          inputs: ::Array[Anthropic::Models::Beta::beta_dream_input],
          model: Anthropic::Models::Beta::DreamCreateParams::model,
          instructions: String?,
          output_behavior: Anthropic::Models::Beta::beta_output_behavior,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String,
          request_options: Anthropic::RequestOptions
        }

        type model = Anthropic::Beta::BetaDreamModelConfigParam | String

        module Model
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::DreamCreateParams::model]
        end
      end
    end
  end
end
