module Anthropic
  module Models
    module Beta
      type environment_update_params =
        {
          environment_id: String,
          config: Anthropic::Models::Beta::EnvironmentUpdateParams::config?,
          description: String?,
          metadata: ::Hash[Symbol, String?],
          name: String?,
          scope: Anthropic::Models::Beta::EnvironmentUpdateParams::scope?,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String
        }
        & Anthropic::Internal::Type::request_parameters

      class EnvironmentUpdateParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor environment_id: String

        attr_accessor config: Anthropic::Models::Beta::EnvironmentUpdateParams::config?

        attr_accessor description: String?

        attr_reader metadata: ::Hash[Symbol, String?]?

        def metadata=: (::Hash[Symbol, String?]) -> ::Hash[Symbol, String?]

        attr_accessor name: String?

        attr_accessor scope: Anthropic::Models::Beta::EnvironmentUpdateParams::scope?

        attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

        def betas=: (
          ::Array[Anthropic::Models::anthropic_beta]
        ) -> ::Array[Anthropic::Models::anthropic_beta]

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        def initialize: (
          environment_id: String,
          ?config: Anthropic::Models::Beta::EnvironmentUpdateParams::config?,
          ?description: String?,
          ?metadata: ::Hash[Symbol, String?],
          ?name: String?,
          ?scope: Anthropic::Models::Beta::EnvironmentUpdateParams::scope?,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          environment_id: String,
          config: Anthropic::Models::Beta::EnvironmentUpdateParams::config?,
          description: String?,
          metadata: ::Hash[Symbol, String?],
          name: String?,
          scope: Anthropic::Models::Beta::EnvironmentUpdateParams::scope?,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String,
          request_options: Anthropic::RequestOptions
        }

        type config =
          Anthropic::Beta::BetaCloudConfigParams
          | Anthropic::Beta::BetaSelfHostedConfigParams

        module Config
          extend Anthropic::Internal::Type::Union

          type type_ = :cloud | :self_hosted

          module Type
            extend Anthropic::Internal::Type::Enum

            CLOUD: :cloud
            SELF_HOSTED: :self_hosted

            def self?.values: -> ::Array[Anthropic::Models::Beta::EnvironmentUpdateParams::Config::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::EnvironmentUpdateParams::config]

          def self.new:
            (
              type: :cloud | "cloud",
              ?networking: Anthropic::Models::Beta::BetaCloudConfigParams::networking?,
              ?packages: Anthropic::Beta::BetaPackagesParams?
            ) -> Anthropic::Beta::BetaCloudConfigParams
            | (
              type: :self_hosted | "self_hosted"
            ) -> Anthropic::Beta::BetaSelfHostedConfigParams
            | (
              type: Anthropic::Models::Beta::EnvironmentUpdateParams::Config::type_
              | String,
              ?networking: Anthropic::Models::Beta::BetaCloudConfigParams::networking?,
              ?packages: Anthropic::Beta::BetaPackagesParams?
            ) -> Anthropic::Models::Beta::EnvironmentUpdateParams::config
        end

        type scope = :organization | :account

        module Scope
          extend Anthropic::Internal::Type::Enum

          ORGANIZATION: :organization
          ACCOUNT: :account

          def self?.values: -> ::Array[Anthropic::Models::Beta::EnvironmentUpdateParams::scope]
        end
      end
    end
  end
end
