module Anthropic
  module Models
    module Beta
      type file_download_params =
        {
          file_id: String,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String
        }
        & Anthropic::Internal::Type::request_parameters

      class FileDownloadParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor file_id: String

        attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

        def betas=: (
          ::Array[Anthropic::Models::anthropic_beta]
        ) -> ::Array[Anthropic::Models::anthropic_beta]

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        def initialize: (
          file_id: String,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?workspace_id: String,
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          file_id: String,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          workspace_id: String,
          request_options: Anthropic::RequestOptions
        }
      end
    end
  end
end
