package com.anthropic.models.beta.sessions

import com.anthropic.core.JsonValue
import com.anthropic.core.jsonMapper
import com.anthropic.models.beta.BetaCurrency
import com.anthropic.models.beta.BetaMonetaryAmount
import com.anthropic.models.beta.agents.BetaManagedAgentsAgentToolset20260401
import com.anthropic.models.beta.agents.BetaManagedAgentsAgentToolsetDefaultConfig
import com.anthropic.models.beta.agents.BetaManagedAgentsAlwaysAllowPolicy
import com.anthropic.models.beta.agents.BetaManagedAgentsAlwaysAskPolicy
import com.anthropic.models.beta.agents.BetaManagedAgentsAnthropicSkill
import com.anthropic.models.beta.agents.BetaManagedAgentsBashToolConfig
import com.anthropic.models.beta.agents.BetaManagedAgentsCustomSkill
import com.anthropic.models.beta.agents.BetaManagedAgentsEffortLow
import com.anthropic.models.beta.agents.BetaManagedAgentsMcpServerUrlDefinition
import com.anthropic.models.beta.agents.BetaManagedAgentsModel
import com.anthropic.models.beta.agents.BetaManagedAgentsModelConfig
import com.anthropic.models.beta.agents.BetaManagedAgentsSessionThreadAgent
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BetaManagedAgentsSessionUpdatedEventTest {

    @Test
    fun create() {
        val betaManagedAgentsSessionUpdatedEvent =
            BetaManagedAgentsSessionUpdatedEvent.builder()
                .id("id")
                .processedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .type(BetaManagedAgentsSessionUpdatedEvent.Type.SESSION_UPDATED)
                .agent(
                    BetaManagedAgentsSessionAgent.builder()
                        .id("agent_011CZkYpogX7uDKUyvBTophP")
                        .description("A general-purpose starter agent.")
                        .addMcpServer(
                            BetaManagedAgentsMcpServerUrlDefinition.builder()
                                .name("example-mcp")
                                .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                .url("https://example-server.modelcontextprotocol.io/sse")
                                .build()
                        )
                        .model(
                            BetaManagedAgentsModelConfig.builder()
                                .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                .effort(
                                    BetaManagedAgentsEffortLow.of(
                                        BetaManagedAgentsEffortLow.Type.LOW
                                    )
                                )
                                .inferenceGeo("inference_geo")
                                .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                .build()
                        )
                        .multiagent(
                            BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                .addAgent(
                                    BetaManagedAgentsSessionThreadAgent.builder()
                                        .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                        .description("A focused research subagent.")
                                        .addMcpServer(
                                            BetaManagedAgentsMcpServerUrlDefinition.builder()
                                                .name("example-mcp")
                                                .type(
                                                    BetaManagedAgentsMcpServerUrlDefinition.Type.URL
                                                )
                                                .url(
                                                    "https://example-server.modelcontextprotocol.io/sse"
                                                )
                                                .build()
                                        )
                                        .model(
                                            BetaManagedAgentsModelConfig.builder()
                                                .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                .effort(
                                                    BetaManagedAgentsEffortLow.of(
                                                        BetaManagedAgentsEffortLow.Type.LOW
                                                    )
                                                )
                                                .inferenceGeo("inference_geo")
                                                .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                                .build()
                                        )
                                        .name("Researcher")
                                        .addSkill(
                                            BetaManagedAgentsAnthropicSkill.builder()
                                                .skillId("xlsx")
                                                .type(
                                                    BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC
                                                )
                                                .version("1")
                                                .build()
                                        )
                                        .system(
                                            "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                        )
                                        .addTool(
                                            BetaManagedAgentsAgentToolset20260401.builder()
                                                .addConfig(
                                                    BetaManagedAgentsBashToolConfig.builder()
                                                        .enabled(true)
                                                        .permissionPolicy(
                                                            BetaManagedAgentsAlwaysAllowPolicy.of(
                                                                BetaManagedAgentsAlwaysAllowPolicy
                                                                    .Type
                                                                    .ALWAYS_ALLOW
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .defaultConfig(
                                                    BetaManagedAgentsAgentToolsetDefaultConfig
                                                        .builder()
                                                        .enabled(true)
                                                        .permissionPolicy(
                                                            BetaManagedAgentsAlwaysAskPolicy.of(
                                                                BetaManagedAgentsAlwaysAskPolicy
                                                                    .Type
                                                                    .ALWAYS_ASK
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .type(
                                                    BetaManagedAgentsAgentToolset20260401.Type
                                                        .AGENT_TOOLSET_20260401
                                                )
                                                .build()
                                        )
                                        .type(BetaManagedAgentsSessionThreadAgent.Type.AGENT)
                                        .version(1)
                                        .build()
                                )
                                .type(
                                    BetaManagedAgentsSessionMultiagentCoordinator.Type.COORDINATOR
                                )
                                .build()
                        )
                        .name("My First Agent")
                        .addSkill(
                            BetaManagedAgentsAnthropicSkill.builder()
                                .skillId("xlsx")
                                .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                .version("1")
                                .build()
                        )
                        .addSkill(
                            BetaManagedAgentsCustomSkill.builder()
                                .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                .version("2")
                                .build()
                        )
                        .system(
                            "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                        )
                        .addTool(
                            BetaManagedAgentsAgentToolset20260401.builder()
                                .addConfig(
                                    BetaManagedAgentsBashToolConfig.builder()
                                        .enabled(true)
                                        .permissionPolicy(
                                            BetaManagedAgentsAlwaysAllowPolicy.of(
                                                BetaManagedAgentsAlwaysAllowPolicy.Type.ALWAYS_ALLOW
                                            )
                                        )
                                        .build()
                                )
                                .defaultConfig(
                                    BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                        .enabled(true)
                                        .permissionPolicy(
                                            BetaManagedAgentsAlwaysAskPolicy.of(
                                                BetaManagedAgentsAlwaysAskPolicy.Type.ALWAYS_ASK
                                            )
                                        )
                                        .build()
                                )
                                .type(
                                    BetaManagedAgentsAgentToolset20260401.Type
                                        .AGENT_TOOLSET_20260401
                                )
                                .build()
                        )
                        .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                        .version(1)
                        .build()
                )
                .budget(
                    BetaManagedAgentsBudgetLimit.builder()
                        .maxListCost(
                            BetaMonetaryAmount.builder()
                                .amount("2500")
                                .currency(BetaCurrency.USD)
                                .build()
                        )
                        .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                        .build()
                )
                .metadata(
                    BetaManagedAgentsSessionUpdatedEvent.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .title("title")
                .build()

        assertThat(betaManagedAgentsSessionUpdatedEvent.id()).isEqualTo("id")
        assertThat(betaManagedAgentsSessionUpdatedEvent.processedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(betaManagedAgentsSessionUpdatedEvent.type())
            .isEqualTo(BetaManagedAgentsSessionUpdatedEvent.Type.SESSION_UPDATED)
        assertThat(betaManagedAgentsSessionUpdatedEvent.agent())
            .contains(
                BetaManagedAgentsSessionAgent.builder()
                    .id("agent_011CZkYpogX7uDKUyvBTophP")
                    .description("A general-purpose starter agent.")
                    .addMcpServer(
                        BetaManagedAgentsMcpServerUrlDefinition.builder()
                            .name("example-mcp")
                            .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                            .url("https://example-server.modelcontextprotocol.io/sse")
                            .build()
                    )
                    .model(
                        BetaManagedAgentsModelConfig.builder()
                            .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                            .effort(
                                BetaManagedAgentsEffortLow.of(BetaManagedAgentsEffortLow.Type.LOW)
                            )
                            .inferenceGeo("inference_geo")
                            .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                            .build()
                    )
                    .multiagent(
                        BetaManagedAgentsSessionMultiagentCoordinator.builder()
                            .addAgent(
                                BetaManagedAgentsSessionThreadAgent.builder()
                                    .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                    .description("A focused research subagent.")
                                    .addMcpServer(
                                        BetaManagedAgentsMcpServerUrlDefinition.builder()
                                            .name("example-mcp")
                                            .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                            .url(
                                                "https://example-server.modelcontextprotocol.io/sse"
                                            )
                                            .build()
                                    )
                                    .model(
                                        BetaManagedAgentsModelConfig.builder()
                                            .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                            .effort(
                                                BetaManagedAgentsEffortLow.of(
                                                    BetaManagedAgentsEffortLow.Type.LOW
                                                )
                                            )
                                            .inferenceGeo("inference_geo")
                                            .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                            .build()
                                    )
                                    .name("Researcher")
                                    .addSkill(
                                        BetaManagedAgentsAnthropicSkill.builder()
                                            .skillId("xlsx")
                                            .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                            .version("1")
                                            .build()
                                    )
                                    .system(
                                        "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                    )
                                    .addTool(
                                        BetaManagedAgentsAgentToolset20260401.builder()
                                            .addConfig(
                                                BetaManagedAgentsBashToolConfig.builder()
                                                    .enabled(true)
                                                    .permissionPolicy(
                                                        BetaManagedAgentsAlwaysAllowPolicy.of(
                                                            BetaManagedAgentsAlwaysAllowPolicy.Type
                                                                .ALWAYS_ALLOW
                                                        )
                                                    )
                                                    .build()
                                            )
                                            .defaultConfig(
                                                BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                                    .enabled(true)
                                                    .permissionPolicy(
                                                        BetaManagedAgentsAlwaysAskPolicy.of(
                                                            BetaManagedAgentsAlwaysAskPolicy.Type
                                                                .ALWAYS_ASK
                                                        )
                                                    )
                                                    .build()
                                            )
                                            .type(
                                                BetaManagedAgentsAgentToolset20260401.Type
                                                    .AGENT_TOOLSET_20260401
                                            )
                                            .build()
                                    )
                                    .type(BetaManagedAgentsSessionThreadAgent.Type.AGENT)
                                    .version(1)
                                    .build()
                            )
                            .type(BetaManagedAgentsSessionMultiagentCoordinator.Type.COORDINATOR)
                            .build()
                    )
                    .name("My First Agent")
                    .addSkill(
                        BetaManagedAgentsAnthropicSkill.builder()
                            .skillId("xlsx")
                            .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                            .version("1")
                            .build()
                    )
                    .addSkill(
                        BetaManagedAgentsCustomSkill.builder()
                            .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                            .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                            .version("2")
                            .build()
                    )
                    .system(
                        "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                    )
                    .addTool(
                        BetaManagedAgentsAgentToolset20260401.builder()
                            .addConfig(
                                BetaManagedAgentsBashToolConfig.builder()
                                    .enabled(true)
                                    .permissionPolicy(
                                        BetaManagedAgentsAlwaysAllowPolicy.of(
                                            BetaManagedAgentsAlwaysAllowPolicy.Type.ALWAYS_ALLOW
                                        )
                                    )
                                    .build()
                            )
                            .defaultConfig(
                                BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                    .enabled(true)
                                    .permissionPolicy(
                                        BetaManagedAgentsAlwaysAskPolicy.of(
                                            BetaManagedAgentsAlwaysAskPolicy.Type.ALWAYS_ASK
                                        )
                                    )
                                    .build()
                            )
                            .type(BetaManagedAgentsAgentToolset20260401.Type.AGENT_TOOLSET_20260401)
                            .build()
                    )
                    .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                    .version(1)
                    .build()
            )
        assertThat(betaManagedAgentsSessionUpdatedEvent.budget())
            .contains(
                BetaManagedAgentsBudgetLimit.builder()
                    .maxListCost(
                        BetaMonetaryAmount.builder()
                            .amount("2500")
                            .currency(BetaCurrency.USD)
                            .build()
                    )
                    .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                    .build()
            )
        assertThat(betaManagedAgentsSessionUpdatedEvent.metadata())
            .contains(
                BetaManagedAgentsSessionUpdatedEvent.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(betaManagedAgentsSessionUpdatedEvent.title()).contains("title")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val betaManagedAgentsSessionUpdatedEvent =
            BetaManagedAgentsSessionUpdatedEvent.builder()
                .id("id")
                .processedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .type(BetaManagedAgentsSessionUpdatedEvent.Type.SESSION_UPDATED)
                .agent(
                    BetaManagedAgentsSessionAgent.builder()
                        .id("agent_011CZkYpogX7uDKUyvBTophP")
                        .description("A general-purpose starter agent.")
                        .addMcpServer(
                            BetaManagedAgentsMcpServerUrlDefinition.builder()
                                .name("example-mcp")
                                .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                .url("https://example-server.modelcontextprotocol.io/sse")
                                .build()
                        )
                        .model(
                            BetaManagedAgentsModelConfig.builder()
                                .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                .effort(
                                    BetaManagedAgentsEffortLow.of(
                                        BetaManagedAgentsEffortLow.Type.LOW
                                    )
                                )
                                .inferenceGeo("inference_geo")
                                .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                .build()
                        )
                        .multiagent(
                            BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                .addAgent(
                                    BetaManagedAgentsSessionThreadAgent.builder()
                                        .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                        .description("A focused research subagent.")
                                        .addMcpServer(
                                            BetaManagedAgentsMcpServerUrlDefinition.builder()
                                                .name("example-mcp")
                                                .type(
                                                    BetaManagedAgentsMcpServerUrlDefinition.Type.URL
                                                )
                                                .url(
                                                    "https://example-server.modelcontextprotocol.io/sse"
                                                )
                                                .build()
                                        )
                                        .model(
                                            BetaManagedAgentsModelConfig.builder()
                                                .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                .effort(
                                                    BetaManagedAgentsEffortLow.of(
                                                        BetaManagedAgentsEffortLow.Type.LOW
                                                    )
                                                )
                                                .inferenceGeo("inference_geo")
                                                .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                                .build()
                                        )
                                        .name("Researcher")
                                        .addSkill(
                                            BetaManagedAgentsAnthropicSkill.builder()
                                                .skillId("xlsx")
                                                .type(
                                                    BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC
                                                )
                                                .version("1")
                                                .build()
                                        )
                                        .system(
                                            "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                        )
                                        .addTool(
                                            BetaManagedAgentsAgentToolset20260401.builder()
                                                .addConfig(
                                                    BetaManagedAgentsBashToolConfig.builder()
                                                        .enabled(true)
                                                        .permissionPolicy(
                                                            BetaManagedAgentsAlwaysAllowPolicy.of(
                                                                BetaManagedAgentsAlwaysAllowPolicy
                                                                    .Type
                                                                    .ALWAYS_ALLOW
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .defaultConfig(
                                                    BetaManagedAgentsAgentToolsetDefaultConfig
                                                        .builder()
                                                        .enabled(true)
                                                        .permissionPolicy(
                                                            BetaManagedAgentsAlwaysAskPolicy.of(
                                                                BetaManagedAgentsAlwaysAskPolicy
                                                                    .Type
                                                                    .ALWAYS_ASK
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .type(
                                                    BetaManagedAgentsAgentToolset20260401.Type
                                                        .AGENT_TOOLSET_20260401
                                                )
                                                .build()
                                        )
                                        .type(BetaManagedAgentsSessionThreadAgent.Type.AGENT)
                                        .version(1)
                                        .build()
                                )
                                .type(
                                    BetaManagedAgentsSessionMultiagentCoordinator.Type.COORDINATOR
                                )
                                .build()
                        )
                        .name("My First Agent")
                        .addSkill(
                            BetaManagedAgentsAnthropicSkill.builder()
                                .skillId("xlsx")
                                .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                .version("1")
                                .build()
                        )
                        .addSkill(
                            BetaManagedAgentsCustomSkill.builder()
                                .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                .version("2")
                                .build()
                        )
                        .system(
                            "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                        )
                        .addTool(
                            BetaManagedAgentsAgentToolset20260401.builder()
                                .addConfig(
                                    BetaManagedAgentsBashToolConfig.builder()
                                        .enabled(true)
                                        .permissionPolicy(
                                            BetaManagedAgentsAlwaysAllowPolicy.of(
                                                BetaManagedAgentsAlwaysAllowPolicy.Type.ALWAYS_ALLOW
                                            )
                                        )
                                        .build()
                                )
                                .defaultConfig(
                                    BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                        .enabled(true)
                                        .permissionPolicy(
                                            BetaManagedAgentsAlwaysAskPolicy.of(
                                                BetaManagedAgentsAlwaysAskPolicy.Type.ALWAYS_ASK
                                            )
                                        )
                                        .build()
                                )
                                .type(
                                    BetaManagedAgentsAgentToolset20260401.Type
                                        .AGENT_TOOLSET_20260401
                                )
                                .build()
                        )
                        .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                        .version(1)
                        .build()
                )
                .budget(
                    BetaManagedAgentsBudgetLimit.builder()
                        .maxListCost(
                            BetaMonetaryAmount.builder()
                                .amount("2500")
                                .currency(BetaCurrency.USD)
                                .build()
                        )
                        .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                        .build()
                )
                .metadata(
                    BetaManagedAgentsSessionUpdatedEvent.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .title("title")
                .build()

        val roundtrippedBetaManagedAgentsSessionUpdatedEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(betaManagedAgentsSessionUpdatedEvent),
                jacksonTypeRef<BetaManagedAgentsSessionUpdatedEvent>(),
            )

        assertThat(roundtrippedBetaManagedAgentsSessionUpdatedEvent)
            .isEqualTo(betaManagedAgentsSessionUpdatedEvent)
    }
}
