package com.anthropic.models.beta.sessions

import com.anthropic.core.jsonMapper
import com.anthropic.models.beta.BetaCurrency
import com.anthropic.models.beta.BetaMonetaryAmount
import com.anthropic.models.beta.agents.BetaManagedAgentsAgentToolset20260401
import com.anthropic.models.beta.agents.BetaManagedAgentsAgentToolsetDefaultConfig
import com.anthropic.models.beta.agents.BetaManagedAgentsAlwaysAllowPolicy
import com.anthropic.models.beta.agents.BetaManagedAgentsAlwaysAskPolicy
import com.anthropic.models.beta.agents.BetaManagedAgentsAnthropicSkill
import com.anthropic.models.beta.agents.BetaManagedAgentsBashToolConfig
import com.anthropic.models.beta.agents.BetaManagedAgentsCustomSkill
import com.anthropic.models.beta.agents.BetaManagedAgentsEffortLow
import com.anthropic.models.beta.agents.BetaManagedAgentsMcpServerUrlDefinition
import com.anthropic.models.beta.agents.BetaManagedAgentsModel
import com.anthropic.models.beta.agents.BetaManagedAgentsModelConfig
import com.anthropic.models.beta.agents.BetaManagedAgentsSessionThreadAgent
import com.anthropic.models.beta.sessions.resources.BetaManagedAgentsFileResource
import com.anthropic.models.beta.sessions.resources.BetaManagedAgentsGitHubRepositoryResource
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SessionListPageResponseTest {

    @Test
    fun create() {
        val sessionListPageResponse =
            SessionListPageResponse.builder()
                .addData(
                    BetaManagedAgentsSession.builder()
                        .id("sesn_011CZkZAtmR3yMPDzynEDxu7")
                        .agent(
                            BetaManagedAgentsSessionAgent.builder()
                                .id("agent_011CZkYpogX7uDKUyvBTophP")
                                .description("A general-purpose starter agent.")
                                .addMcpServer(
                                    BetaManagedAgentsMcpServerUrlDefinition.builder()
                                        .name("example-mcp")
                                        .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                        .url("https://example-server.modelcontextprotocol.io/sse")
                                        .build()
                                )
                                .model(
                                    BetaManagedAgentsModelConfig.builder()
                                        .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                        .effort(
                                            BetaManagedAgentsEffortLow.of(
                                                BetaManagedAgentsEffortLow.Type.LOW
                                            )
                                        )
                                        .inferenceGeo("inference_geo")
                                        .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                        .build()
                                )
                                .multiagent(
                                    BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                        .addAgent(
                                            BetaManagedAgentsSessionThreadAgent.builder()
                                                .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                                .description("A focused research subagent.")
                                                .addMcpServer(
                                                    BetaManagedAgentsMcpServerUrlDefinition
                                                        .builder()
                                                        .name("example-mcp")
                                                        .type(
                                                            BetaManagedAgentsMcpServerUrlDefinition
                                                                .Type
                                                                .URL
                                                        )
                                                        .url(
                                                            "https://example-server.modelcontextprotocol.io/sse"
                                                        )
                                                        .build()
                                                )
                                                .model(
                                                    BetaManagedAgentsModelConfig.builder()
                                                        .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                        .effort(
                                                            BetaManagedAgentsEffortLow.of(
                                                                BetaManagedAgentsEffortLow.Type.LOW
                                                            )
                                                        )
                                                        .inferenceGeo("inference_geo")
                                                        .speed(
                                                            BetaManagedAgentsModelConfig.Speed
                                                                .STANDARD
                                                        )
                                                        .build()
                                                )
                                                .name("Researcher")
                                                .addSkill(
                                                    BetaManagedAgentsAnthropicSkill.builder()
                                                        .skillId("xlsx")
                                                        .type(
                                                            BetaManagedAgentsAnthropicSkill.Type
                                                                .ANTHROPIC
                                                        )
                                                        .version("1")
                                                        .build()
                                                )
                                                .system(
                                                    "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                                )
                                                .addTool(
                                                    BetaManagedAgentsAgentToolset20260401.builder()
                                                        .addConfig(
                                                            BetaManagedAgentsBashToolConfig
                                                                .builder()
                                                                .enabled(true)
                                                                .permissionPolicy(
                                                                    BetaManagedAgentsAlwaysAllowPolicy
                                                                        .of(
                                                                            BetaManagedAgentsAlwaysAllowPolicy
                                                                                .Type
                                                                                .ALWAYS_ALLOW
                                                                        )
                                                                )
                                                                .build()
                                                        )
                                                        .defaultConfig(
                                                            BetaManagedAgentsAgentToolsetDefaultConfig
                                                                .builder()
                                                                .enabled(true)
                                                                .permissionPolicy(
                                                                    BetaManagedAgentsAlwaysAskPolicy
                                                                        .of(
                                                                            BetaManagedAgentsAlwaysAskPolicy
                                                                                .Type
                                                                                .ALWAYS_ASK
                                                                        )
                                                                )
                                                                .build()
                                                        )
                                                        .type(
                                                            BetaManagedAgentsAgentToolset20260401
                                                                .Type
                                                                .AGENT_TOOLSET_20260401
                                                        )
                                                        .build()
                                                )
                                                .type(
                                                    BetaManagedAgentsSessionThreadAgent.Type.AGENT
                                                )
                                                .version(1)
                                                .build()
                                        )
                                        .type(
                                            BetaManagedAgentsSessionMultiagentCoordinator.Type
                                                .COORDINATOR
                                        )
                                        .build()
                                )
                                .name("My First Agent")
                                .addSkill(
                                    BetaManagedAgentsAnthropicSkill.builder()
                                        .skillId("xlsx")
                                        .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                        .version("1")
                                        .build()
                                )
                                .addSkill(
                                    BetaManagedAgentsCustomSkill.builder()
                                        .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                        .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                        .version("2")
                                        .build()
                                )
                                .system(
                                    "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                                )
                                .addTool(
                                    BetaManagedAgentsAgentToolset20260401.builder()
                                        .addConfig(
                                            BetaManagedAgentsBashToolConfig.builder()
                                                .enabled(true)
                                                .permissionPolicy(
                                                    BetaManagedAgentsAlwaysAllowPolicy.of(
                                                        BetaManagedAgentsAlwaysAllowPolicy.Type
                                                            .ALWAYS_ALLOW
                                                    )
                                                )
                                                .build()
                                        )
                                        .defaultConfig(
                                            BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                                .enabled(true)
                                                .permissionPolicy(
                                                    BetaManagedAgentsAlwaysAskPolicy.of(
                                                        BetaManagedAgentsAlwaysAskPolicy.Type
                                                            .ALWAYS_ASK
                                                    )
                                                )
                                                .build()
                                        )
                                        .type(
                                            BetaManagedAgentsAgentToolset20260401.Type
                                                .AGENT_TOOLSET_20260401
                                        )
                                        .build()
                                )
                                .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                                .version(1)
                                .build()
                        )
                        .archivedAt(null)
                        .budget(
                            BetaManagedAgentsBudgetLimit.builder()
                                .maxListCost(
                                    BetaMonetaryAmount.builder()
                                        .amount("2500")
                                        .currency(BetaCurrency.USD)
                                        .build()
                                )
                                .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                        .environmentId("env_011CZkZ9X2dpNyB7HsEFoRfW")
                        .metadata(BetaManagedAgentsSession.Metadata.builder().build())
                        .addOutcomeEvaluation(
                            BetaManagedAgentsOutcomeEvaluationResource.builder()
                                .completedAt(OffsetDateTime.parse("2026-03-15T10:02:31Z"))
                                .description("Produce a 2-page summary as summary.md")
                                .explanation("All five sections present with inline citations.")
                                .iteration(0)
                                .outcomeId("outc_011CZkZRSw2kEfs6ncTVljxP")
                                .result("satisfied")
                                .type(
                                    BetaManagedAgentsOutcomeEvaluationResource.Type
                                        .OUTCOME_EVALUATION
                                )
                                .build()
                        )
                        .addResource(
                            BetaManagedAgentsFileResource.builder()
                                .id("sesrsc_011CZkZBJq5dWxk9fVLNcPht")
                                .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .fileId("file_011CNha8iCJcU1wXNR6q4V8w")
                                .mountPath("/uploads/receipt.pdf")
                                .type(BetaManagedAgentsFileResource.Type.FILE)
                                .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .build()
                        )
                        .addResource(
                            BetaManagedAgentsGitHubRepositoryResource.builder()
                                .id("sesrsc_011CZkZCKr6eXyl0gWMOdQiu")
                                .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .mountPath("/workspace/example-repo")
                                .type(
                                    BetaManagedAgentsGitHubRepositoryResource.Type.GITHUB_REPOSITORY
                                )
                                .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .url("https://github.com/example-org/example-repo")
                                .branchCheckout("main")
                                .build()
                        )
                        .stats(
                            BetaManagedAgentsSessionStats.builder()
                                .activeSeconds(0.0)
                                .durationSeconds(0.0)
                                .build()
                        )
                        .status(BetaManagedAgentsSession.Status.IDLE)
                        .title("Order #1234 inquiry")
                        .type(BetaManagedAgentsSession.Type.SESSION)
                        .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                        .usage(
                            BetaManagedAgentsSessionUsage.builder()
                                .activeSeconds(0.0)
                                .cacheCreation(
                                    BetaManagedAgentsCacheCreationUsage.builder()
                                        .ephemeral1hInputTokens(0)
                                        .ephemeral5mInputTokens(0)
                                        .build()
                                )
                                .cacheReadInputTokens(0)
                                .inputTokens(0)
                                .listCost(
                                    BetaMonetaryAmount.builder()
                                        .amount("2500")
                                        .currency(BetaCurrency.USD)
                                        .build()
                                )
                                .outputTokens(0)
                                .serverToolUse(
                                    BetaManagedAgentsServerToolUsage.builder()
                                        .webFetchRequests(0)
                                        .webSearchRequests(3)
                                        .build()
                                )
                                .build()
                        )
                        .addVaultId("vlt_011CZkZDLs7fYzm1hXNPeRjv")
                        .deploymentId("deployment_id")
                        .build()
                )
                .nextPage("page_MjAyNS0wNS0xNFQwMDowMDowMFo=")
                .prevPage("page_MjAyNS0wNS0xM1QwMDowMDowMFo=")
                .build()

        assertThat(sessionListPageResponse.data().getOrNull())
            .containsExactly(
                BetaManagedAgentsSession.builder()
                    .id("sesn_011CZkZAtmR3yMPDzynEDxu7")
                    .agent(
                        BetaManagedAgentsSessionAgent.builder()
                            .id("agent_011CZkYpogX7uDKUyvBTophP")
                            .description("A general-purpose starter agent.")
                            .addMcpServer(
                                BetaManagedAgentsMcpServerUrlDefinition.builder()
                                    .name("example-mcp")
                                    .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                    .url("https://example-server.modelcontextprotocol.io/sse")
                                    .build()
                            )
                            .model(
                                BetaManagedAgentsModelConfig.builder()
                                    .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                    .effort(
                                        BetaManagedAgentsEffortLow.of(
                                            BetaManagedAgentsEffortLow.Type.LOW
                                        )
                                    )
                                    .inferenceGeo("inference_geo")
                                    .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                    .build()
                            )
                            .multiagent(
                                BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                    .addAgent(
                                        BetaManagedAgentsSessionThreadAgent.builder()
                                            .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                            .description("A focused research subagent.")
                                            .addMcpServer(
                                                BetaManagedAgentsMcpServerUrlDefinition.builder()
                                                    .name("example-mcp")
                                                    .type(
                                                        BetaManagedAgentsMcpServerUrlDefinition.Type
                                                            .URL
                                                    )
                                                    .url(
                                                        "https://example-server.modelcontextprotocol.io/sse"
                                                    )
                                                    .build()
                                            )
                                            .model(
                                                BetaManagedAgentsModelConfig.builder()
                                                    .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                    .effort(
                                                        BetaManagedAgentsEffortLow.of(
                                                            BetaManagedAgentsEffortLow.Type.LOW
                                                        )
                                                    )
                                                    .inferenceGeo("inference_geo")
                                                    .speed(
                                                        BetaManagedAgentsModelConfig.Speed.STANDARD
                                                    )
                                                    .build()
                                            )
                                            .name("Researcher")
                                            .addSkill(
                                                BetaManagedAgentsAnthropicSkill.builder()
                                                    .skillId("xlsx")
                                                    .type(
                                                        BetaManagedAgentsAnthropicSkill.Type
                                                            .ANTHROPIC
                                                    )
                                                    .version("1")
                                                    .build()
                                            )
                                            .system(
                                                "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                            )
                                            .addTool(
                                                BetaManagedAgentsAgentToolset20260401.builder()
                                                    .addConfig(
                                                        BetaManagedAgentsBashToolConfig.builder()
                                                            .enabled(true)
                                                            .permissionPolicy(
                                                                BetaManagedAgentsAlwaysAllowPolicy
                                                                    .of(
                                                                        BetaManagedAgentsAlwaysAllowPolicy
                                                                            .Type
                                                                            .ALWAYS_ALLOW
                                                                    )
                                                            )
                                                            .build()
                                                    )
                                                    .defaultConfig(
                                                        BetaManagedAgentsAgentToolsetDefaultConfig
                                                            .builder()
                                                            .enabled(true)
                                                            .permissionPolicy(
                                                                BetaManagedAgentsAlwaysAskPolicy.of(
                                                                    BetaManagedAgentsAlwaysAskPolicy
                                                                        .Type
                                                                        .ALWAYS_ASK
                                                                )
                                                            )
                                                            .build()
                                                    )
                                                    .type(
                                                        BetaManagedAgentsAgentToolset20260401.Type
                                                            .AGENT_TOOLSET_20260401
                                                    )
                                                    .build()
                                            )
                                            .type(BetaManagedAgentsSessionThreadAgent.Type.AGENT)
                                            .version(1)
                                            .build()
                                    )
                                    .type(
                                        BetaManagedAgentsSessionMultiagentCoordinator.Type
                                            .COORDINATOR
                                    )
                                    .build()
                            )
                            .name("My First Agent")
                            .addSkill(
                                BetaManagedAgentsAnthropicSkill.builder()
                                    .skillId("xlsx")
                                    .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                    .version("1")
                                    .build()
                            )
                            .addSkill(
                                BetaManagedAgentsCustomSkill.builder()
                                    .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                    .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                    .version("2")
                                    .build()
                            )
                            .system(
                                "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                            )
                            .addTool(
                                BetaManagedAgentsAgentToolset20260401.builder()
                                    .addConfig(
                                        BetaManagedAgentsBashToolConfig.builder()
                                            .enabled(true)
                                            .permissionPolicy(
                                                BetaManagedAgentsAlwaysAllowPolicy.of(
                                                    BetaManagedAgentsAlwaysAllowPolicy.Type
                                                        .ALWAYS_ALLOW
                                                )
                                            )
                                            .build()
                                    )
                                    .defaultConfig(
                                        BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                            .enabled(true)
                                            .permissionPolicy(
                                                BetaManagedAgentsAlwaysAskPolicy.of(
                                                    BetaManagedAgentsAlwaysAskPolicy.Type.ALWAYS_ASK
                                                )
                                            )
                                            .build()
                                    )
                                    .type(
                                        BetaManagedAgentsAgentToolset20260401.Type
                                            .AGENT_TOOLSET_20260401
                                    )
                                    .build()
                            )
                            .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                            .version(1)
                            .build()
                    )
                    .archivedAt(null)
                    .budget(
                        BetaManagedAgentsBudgetLimit.builder()
                            .maxListCost(
                                BetaMonetaryAmount.builder()
                                    .amount("2500")
                                    .currency(BetaCurrency.USD)
                                    .build()
                            )
                            .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                    .environmentId("env_011CZkZ9X2dpNyB7HsEFoRfW")
                    .metadata(BetaManagedAgentsSession.Metadata.builder().build())
                    .addOutcomeEvaluation(
                        BetaManagedAgentsOutcomeEvaluationResource.builder()
                            .completedAt(OffsetDateTime.parse("2026-03-15T10:02:31Z"))
                            .description("Produce a 2-page summary as summary.md")
                            .explanation("All five sections present with inline citations.")
                            .iteration(0)
                            .outcomeId("outc_011CZkZRSw2kEfs6ncTVljxP")
                            .result("satisfied")
                            .type(
                                BetaManagedAgentsOutcomeEvaluationResource.Type.OUTCOME_EVALUATION
                            )
                            .build()
                    )
                    .addResource(
                        BetaManagedAgentsFileResource.builder()
                            .id("sesrsc_011CZkZBJq5dWxk9fVLNcPht")
                            .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .fileId("file_011CNha8iCJcU1wXNR6q4V8w")
                            .mountPath("/uploads/receipt.pdf")
                            .type(BetaManagedAgentsFileResource.Type.FILE)
                            .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .build()
                    )
                    .addResource(
                        BetaManagedAgentsGitHubRepositoryResource.builder()
                            .id("sesrsc_011CZkZCKr6eXyl0gWMOdQiu")
                            .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .mountPath("/workspace/example-repo")
                            .type(BetaManagedAgentsGitHubRepositoryResource.Type.GITHUB_REPOSITORY)
                            .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .url("https://github.com/example-org/example-repo")
                            .branchCheckout("main")
                            .build()
                    )
                    .stats(
                        BetaManagedAgentsSessionStats.builder()
                            .activeSeconds(0.0)
                            .durationSeconds(0.0)
                            .build()
                    )
                    .status(BetaManagedAgentsSession.Status.IDLE)
                    .title("Order #1234 inquiry")
                    .type(BetaManagedAgentsSession.Type.SESSION)
                    .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                    .usage(
                        BetaManagedAgentsSessionUsage.builder()
                            .activeSeconds(0.0)
                            .cacheCreation(
                                BetaManagedAgentsCacheCreationUsage.builder()
                                    .ephemeral1hInputTokens(0)
                                    .ephemeral5mInputTokens(0)
                                    .build()
                            )
                            .cacheReadInputTokens(0)
                            .inputTokens(0)
                            .listCost(
                                BetaMonetaryAmount.builder()
                                    .amount("2500")
                                    .currency(BetaCurrency.USD)
                                    .build()
                            )
                            .outputTokens(0)
                            .serverToolUse(
                                BetaManagedAgentsServerToolUsage.builder()
                                    .webFetchRequests(0)
                                    .webSearchRequests(3)
                                    .build()
                            )
                            .build()
                    )
                    .addVaultId("vlt_011CZkZDLs7fYzm1hXNPeRjv")
                    .deploymentId("deployment_id")
                    .build()
            )
        assertThat(sessionListPageResponse.nextPage()).contains("page_MjAyNS0wNS0xNFQwMDowMDowMFo=")
        assertThat(sessionListPageResponse.prevPage()).contains("page_MjAyNS0wNS0xM1QwMDowMDowMFo=")
    }

    @Test
    fun addToUnsetListsOnToBuilder() {
        val baseSessionListPageResponse = SessionListPageResponse.builder().build()

        val sessionListPageResponse =
            baseSessionListPageResponse
                .toBuilder()
                .addData(
                    BetaManagedAgentsSession.builder()
                        .id("sesn_011CZkZAtmR3yMPDzynEDxu7")
                        .agent(
                            BetaManagedAgentsSessionAgent.builder()
                                .id("agent_011CZkYpogX7uDKUyvBTophP")
                                .description("A general-purpose starter agent.")
                                .addMcpServer(
                                    BetaManagedAgentsMcpServerUrlDefinition.builder()
                                        .name("example-mcp")
                                        .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                        .url("https://example-server.modelcontextprotocol.io/sse")
                                        .build()
                                )
                                .model(
                                    BetaManagedAgentsModelConfig.builder()
                                        .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                        .effort(
                                            BetaManagedAgentsEffortLow.of(
                                                BetaManagedAgentsEffortLow.Type.LOW
                                            )
                                        )
                                        .inferenceGeo("inference_geo")
                                        .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                        .build()
                                )
                                .multiagent(
                                    BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                        .addAgent(
                                            BetaManagedAgentsSessionThreadAgent.builder()
                                                .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                                .description("A focused research subagent.")
                                                .addMcpServer(
                                                    BetaManagedAgentsMcpServerUrlDefinition
                                                        .builder()
                                                        .name("example-mcp")
                                                        .type(
                                                            BetaManagedAgentsMcpServerUrlDefinition
                                                                .Type
                                                                .URL
                                                        )
                                                        .url(
                                                            "https://example-server.modelcontextprotocol.io/sse"
                                                        )
                                                        .build()
                                                )
                                                .model(
                                                    BetaManagedAgentsModelConfig.builder()
                                                        .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                        .effort(
                                                            BetaManagedAgentsEffortLow.of(
                                                                BetaManagedAgentsEffortLow.Type.LOW
                                                            )
                                                        )
                                                        .inferenceGeo("inference_geo")
                                                        .speed(
                                                            BetaManagedAgentsModelConfig.Speed
                                                                .STANDARD
                                                        )
                                                        .build()
                                                )
                                                .name("Researcher")
                                                .addSkill(
                                                    BetaManagedAgentsAnthropicSkill.builder()
                                                        .skillId("xlsx")
                                                        .type(
                                                            BetaManagedAgentsAnthropicSkill.Type
                                                                .ANTHROPIC
                                                        )
                                                        .version("1")
                                                        .build()
                                                )
                                                .system(
                                                    "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                                )
                                                .addTool(
                                                    BetaManagedAgentsAgentToolset20260401.builder()
                                                        .addConfig(
                                                            BetaManagedAgentsBashToolConfig
                                                                .builder()
                                                                .enabled(true)
                                                                .permissionPolicy(
                                                                    BetaManagedAgentsAlwaysAllowPolicy
                                                                        .of(
                                                                            BetaManagedAgentsAlwaysAllowPolicy
                                                                                .Type
                                                                                .ALWAYS_ALLOW
                                                                        )
                                                                )
                                                                .build()
                                                        )
                                                        .defaultConfig(
                                                            BetaManagedAgentsAgentToolsetDefaultConfig
                                                                .builder()
                                                                .enabled(true)
                                                                .permissionPolicy(
                                                                    BetaManagedAgentsAlwaysAskPolicy
                                                                        .of(
                                                                            BetaManagedAgentsAlwaysAskPolicy
                                                                                .Type
                                                                                .ALWAYS_ASK
                                                                        )
                                                                )
                                                                .build()
                                                        )
                                                        .type(
                                                            BetaManagedAgentsAgentToolset20260401
                                                                .Type
                                                                .AGENT_TOOLSET_20260401
                                                        )
                                                        .build()
                                                )
                                                .type(
                                                    BetaManagedAgentsSessionThreadAgent.Type.AGENT
                                                )
                                                .version(1)
                                                .build()
                                        )
                                        .type(
                                            BetaManagedAgentsSessionMultiagentCoordinator.Type
                                                .COORDINATOR
                                        )
                                        .build()
                                )
                                .name("My First Agent")
                                .addSkill(
                                    BetaManagedAgentsAnthropicSkill.builder()
                                        .skillId("xlsx")
                                        .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                        .version("1")
                                        .build()
                                )
                                .addSkill(
                                    BetaManagedAgentsCustomSkill.builder()
                                        .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                        .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                        .version("2")
                                        .build()
                                )
                                .system(
                                    "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                                )
                                .addTool(
                                    BetaManagedAgentsAgentToolset20260401.builder()
                                        .addConfig(
                                            BetaManagedAgentsBashToolConfig.builder()
                                                .enabled(true)
                                                .permissionPolicy(
                                                    BetaManagedAgentsAlwaysAllowPolicy.of(
                                                        BetaManagedAgentsAlwaysAllowPolicy.Type
                                                            .ALWAYS_ALLOW
                                                    )
                                                )
                                                .build()
                                        )
                                        .defaultConfig(
                                            BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                                .enabled(true)
                                                .permissionPolicy(
                                                    BetaManagedAgentsAlwaysAskPolicy.of(
                                                        BetaManagedAgentsAlwaysAskPolicy.Type
                                                            .ALWAYS_ASK
                                                    )
                                                )
                                                .build()
                                        )
                                        .type(
                                            BetaManagedAgentsAgentToolset20260401.Type
                                                .AGENT_TOOLSET_20260401
                                        )
                                        .build()
                                )
                                .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                                .version(1)
                                .build()
                        )
                        .archivedAt(null)
                        .budget(
                            BetaManagedAgentsBudgetLimit.builder()
                                .maxListCost(
                                    BetaMonetaryAmount.builder()
                                        .amount("2500")
                                        .currency(BetaCurrency.USD)
                                        .build()
                                )
                                .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                        .environmentId("env_011CZkZ9X2dpNyB7HsEFoRfW")
                        .metadata(BetaManagedAgentsSession.Metadata.builder().build())
                        .addOutcomeEvaluation(
                            BetaManagedAgentsOutcomeEvaluationResource.builder()
                                .completedAt(OffsetDateTime.parse("2026-03-15T10:02:31Z"))
                                .description("Produce a 2-page summary as summary.md")
                                .explanation("All five sections present with inline citations.")
                                .iteration(0)
                                .outcomeId("outc_011CZkZRSw2kEfs6ncTVljxP")
                                .result("satisfied")
                                .type(
                                    BetaManagedAgentsOutcomeEvaluationResource.Type
                                        .OUTCOME_EVALUATION
                                )
                                .build()
                        )
                        .addResource(
                            BetaManagedAgentsFileResource.builder()
                                .id("sesrsc_011CZkZBJq5dWxk9fVLNcPht")
                                .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .fileId("file_011CNha8iCJcU1wXNR6q4V8w")
                                .mountPath("/uploads/receipt.pdf")
                                .type(BetaManagedAgentsFileResource.Type.FILE)
                                .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .build()
                        )
                        .addResource(
                            BetaManagedAgentsGitHubRepositoryResource.builder()
                                .id("sesrsc_011CZkZCKr6eXyl0gWMOdQiu")
                                .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .mountPath("/workspace/example-repo")
                                .type(
                                    BetaManagedAgentsGitHubRepositoryResource.Type.GITHUB_REPOSITORY
                                )
                                .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .url("https://github.com/example-org/example-repo")
                                .branchCheckout("main")
                                .build()
                        )
                        .stats(
                            BetaManagedAgentsSessionStats.builder()
                                .activeSeconds(0.0)
                                .durationSeconds(0.0)
                                .build()
                        )
                        .status(BetaManagedAgentsSession.Status.IDLE)
                        .title("Order #1234 inquiry")
                        .type(BetaManagedAgentsSession.Type.SESSION)
                        .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                        .usage(
                            BetaManagedAgentsSessionUsage.builder()
                                .activeSeconds(0.0)
                                .cacheCreation(
                                    BetaManagedAgentsCacheCreationUsage.builder()
                                        .ephemeral1hInputTokens(0)
                                        .ephemeral5mInputTokens(0)
                                        .build()
                                )
                                .cacheReadInputTokens(0)
                                .inputTokens(0)
                                .listCost(
                                    BetaMonetaryAmount.builder()
                                        .amount("2500")
                                        .currency(BetaCurrency.USD)
                                        .build()
                                )
                                .outputTokens(0)
                                .serverToolUse(
                                    BetaManagedAgentsServerToolUsage.builder()
                                        .webFetchRequests(0)
                                        .webSearchRequests(3)
                                        .build()
                                )
                                .build()
                        )
                        .addVaultId("vlt_011CZkZDLs7fYzm1hXNPeRjv")
                        .deploymentId("deployment_id")
                        .build()
                )
                .build()

        assertThat(sessionListPageResponse.data().getOrNull())
            .containsExactly(
                BetaManagedAgentsSession.builder()
                    .id("sesn_011CZkZAtmR3yMPDzynEDxu7")
                    .agent(
                        BetaManagedAgentsSessionAgent.builder()
                            .id("agent_011CZkYpogX7uDKUyvBTophP")
                            .description("A general-purpose starter agent.")
                            .addMcpServer(
                                BetaManagedAgentsMcpServerUrlDefinition.builder()
                                    .name("example-mcp")
                                    .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                    .url("https://example-server.modelcontextprotocol.io/sse")
                                    .build()
                            )
                            .model(
                                BetaManagedAgentsModelConfig.builder()
                                    .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                    .effort(
                                        BetaManagedAgentsEffortLow.of(
                                            BetaManagedAgentsEffortLow.Type.LOW
                                        )
                                    )
                                    .inferenceGeo("inference_geo")
                                    .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                    .build()
                            )
                            .multiagent(
                                BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                    .addAgent(
                                        BetaManagedAgentsSessionThreadAgent.builder()
                                            .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                            .description("A focused research subagent.")
                                            .addMcpServer(
                                                BetaManagedAgentsMcpServerUrlDefinition.builder()
                                                    .name("example-mcp")
                                                    .type(
                                                        BetaManagedAgentsMcpServerUrlDefinition.Type
                                                            .URL
                                                    )
                                                    .url(
                                                        "https://example-server.modelcontextprotocol.io/sse"
                                                    )
                                                    .build()
                                            )
                                            .model(
                                                BetaManagedAgentsModelConfig.builder()
                                                    .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                    .effort(
                                                        BetaManagedAgentsEffortLow.of(
                                                            BetaManagedAgentsEffortLow.Type.LOW
                                                        )
                                                    )
                                                    .inferenceGeo("inference_geo")
                                                    .speed(
                                                        BetaManagedAgentsModelConfig.Speed.STANDARD
                                                    )
                                                    .build()
                                            )
                                            .name("Researcher")
                                            .addSkill(
                                                BetaManagedAgentsAnthropicSkill.builder()
                                                    .skillId("xlsx")
                                                    .type(
                                                        BetaManagedAgentsAnthropicSkill.Type
                                                            .ANTHROPIC
                                                    )
                                                    .version("1")
                                                    .build()
                                            )
                                            .system(
                                                "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                            )
                                            .addTool(
                                                BetaManagedAgentsAgentToolset20260401.builder()
                                                    .addConfig(
                                                        BetaManagedAgentsBashToolConfig.builder()
                                                            .enabled(true)
                                                            .permissionPolicy(
                                                                BetaManagedAgentsAlwaysAllowPolicy
                                                                    .of(
                                                                        BetaManagedAgentsAlwaysAllowPolicy
                                                                            .Type
                                                                            .ALWAYS_ALLOW
                                                                    )
                                                            )
                                                            .build()
                                                    )
                                                    .defaultConfig(
                                                        BetaManagedAgentsAgentToolsetDefaultConfig
                                                            .builder()
                                                            .enabled(true)
                                                            .permissionPolicy(
                                                                BetaManagedAgentsAlwaysAskPolicy.of(
                                                                    BetaManagedAgentsAlwaysAskPolicy
                                                                        .Type
                                                                        .ALWAYS_ASK
                                                                )
                                                            )
                                                            .build()
                                                    )
                                                    .type(
                                                        BetaManagedAgentsAgentToolset20260401.Type
                                                            .AGENT_TOOLSET_20260401
                                                    )
                                                    .build()
                                            )
                                            .type(BetaManagedAgentsSessionThreadAgent.Type.AGENT)
                                            .version(1)
                                            .build()
                                    )
                                    .type(
                                        BetaManagedAgentsSessionMultiagentCoordinator.Type
                                            .COORDINATOR
                                    )
                                    .build()
                            )
                            .name("My First Agent")
                            .addSkill(
                                BetaManagedAgentsAnthropicSkill.builder()
                                    .skillId("xlsx")
                                    .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                    .version("1")
                                    .build()
                            )
                            .addSkill(
                                BetaManagedAgentsCustomSkill.builder()
                                    .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                    .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                    .version("2")
                                    .build()
                            )
                            .system(
                                "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                            )
                            .addTool(
                                BetaManagedAgentsAgentToolset20260401.builder()
                                    .addConfig(
                                        BetaManagedAgentsBashToolConfig.builder()
                                            .enabled(true)
                                            .permissionPolicy(
                                                BetaManagedAgentsAlwaysAllowPolicy.of(
                                                    BetaManagedAgentsAlwaysAllowPolicy.Type
                                                        .ALWAYS_ALLOW
                                                )
                                            )
                                            .build()
                                    )
                                    .defaultConfig(
                                        BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                            .enabled(true)
                                            .permissionPolicy(
                                                BetaManagedAgentsAlwaysAskPolicy.of(
                                                    BetaManagedAgentsAlwaysAskPolicy.Type.ALWAYS_ASK
                                                )
                                            )
                                            .build()
                                    )
                                    .type(
                                        BetaManagedAgentsAgentToolset20260401.Type
                                            .AGENT_TOOLSET_20260401
                                    )
                                    .build()
                            )
                            .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                            .version(1)
                            .build()
                    )
                    .archivedAt(null)
                    .budget(
                        BetaManagedAgentsBudgetLimit.builder()
                            .maxListCost(
                                BetaMonetaryAmount.builder()
                                    .amount("2500")
                                    .currency(BetaCurrency.USD)
                                    .build()
                            )
                            .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                    .environmentId("env_011CZkZ9X2dpNyB7HsEFoRfW")
                    .metadata(BetaManagedAgentsSession.Metadata.builder().build())
                    .addOutcomeEvaluation(
                        BetaManagedAgentsOutcomeEvaluationResource.builder()
                            .completedAt(OffsetDateTime.parse("2026-03-15T10:02:31Z"))
                            .description("Produce a 2-page summary as summary.md")
                            .explanation("All five sections present with inline citations.")
                            .iteration(0)
                            .outcomeId("outc_011CZkZRSw2kEfs6ncTVljxP")
                            .result("satisfied")
                            .type(
                                BetaManagedAgentsOutcomeEvaluationResource.Type.OUTCOME_EVALUATION
                            )
                            .build()
                    )
                    .addResource(
                        BetaManagedAgentsFileResource.builder()
                            .id("sesrsc_011CZkZBJq5dWxk9fVLNcPht")
                            .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .fileId("file_011CNha8iCJcU1wXNR6q4V8w")
                            .mountPath("/uploads/receipt.pdf")
                            .type(BetaManagedAgentsFileResource.Type.FILE)
                            .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .build()
                    )
                    .addResource(
                        BetaManagedAgentsGitHubRepositoryResource.builder()
                            .id("sesrsc_011CZkZCKr6eXyl0gWMOdQiu")
                            .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .mountPath("/workspace/example-repo")
                            .type(BetaManagedAgentsGitHubRepositoryResource.Type.GITHUB_REPOSITORY)
                            .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                            .url("https://github.com/example-org/example-repo")
                            .branchCheckout("main")
                            .build()
                    )
                    .stats(
                        BetaManagedAgentsSessionStats.builder()
                            .activeSeconds(0.0)
                            .durationSeconds(0.0)
                            .build()
                    )
                    .status(BetaManagedAgentsSession.Status.IDLE)
                    .title("Order #1234 inquiry")
                    .type(BetaManagedAgentsSession.Type.SESSION)
                    .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                    .usage(
                        BetaManagedAgentsSessionUsage.builder()
                            .activeSeconds(0.0)
                            .cacheCreation(
                                BetaManagedAgentsCacheCreationUsage.builder()
                                    .ephemeral1hInputTokens(0)
                                    .ephemeral5mInputTokens(0)
                                    .build()
                            )
                            .cacheReadInputTokens(0)
                            .inputTokens(0)
                            .listCost(
                                BetaMonetaryAmount.builder()
                                    .amount("2500")
                                    .currency(BetaCurrency.USD)
                                    .build()
                            )
                            .outputTokens(0)
                            .serverToolUse(
                                BetaManagedAgentsServerToolUsage.builder()
                                    .webFetchRequests(0)
                                    .webSearchRequests(3)
                                    .build()
                            )
                            .build()
                    )
                    .addVaultId("vlt_011CZkZDLs7fYzm1hXNPeRjv")
                    .deploymentId("deployment_id")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val sessionListPageResponse =
            SessionListPageResponse.builder()
                .addData(
                    BetaManagedAgentsSession.builder()
                        .id("sesn_011CZkZAtmR3yMPDzynEDxu7")
                        .agent(
                            BetaManagedAgentsSessionAgent.builder()
                                .id("agent_011CZkYpogX7uDKUyvBTophP")
                                .description("A general-purpose starter agent.")
                                .addMcpServer(
                                    BetaManagedAgentsMcpServerUrlDefinition.builder()
                                        .name("example-mcp")
                                        .type(BetaManagedAgentsMcpServerUrlDefinition.Type.URL)
                                        .url("https://example-server.modelcontextprotocol.io/sse")
                                        .build()
                                )
                                .model(
                                    BetaManagedAgentsModelConfig.builder()
                                        .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                        .effort(
                                            BetaManagedAgentsEffortLow.of(
                                                BetaManagedAgentsEffortLow.Type.LOW
                                            )
                                        )
                                        .inferenceGeo("inference_geo")
                                        .speed(BetaManagedAgentsModelConfig.Speed.STANDARD)
                                        .build()
                                )
                                .multiagent(
                                    BetaManagedAgentsSessionMultiagentCoordinator.builder()
                                        .addAgent(
                                            BetaManagedAgentsSessionThreadAgent.builder()
                                                .id("agent_011CZkYqphY8vELVzwCUpqiQ")
                                                .description("A focused research subagent.")
                                                .addMcpServer(
                                                    BetaManagedAgentsMcpServerUrlDefinition
                                                        .builder()
                                                        .name("example-mcp")
                                                        .type(
                                                            BetaManagedAgentsMcpServerUrlDefinition
                                                                .Type
                                                                .URL
                                                        )
                                                        .url(
                                                            "https://example-server.modelcontextprotocol.io/sse"
                                                        )
                                                        .build()
                                                )
                                                .model(
                                                    BetaManagedAgentsModelConfig.builder()
                                                        .id(BetaManagedAgentsModel.CLAUDE_OPUS_5)
                                                        .effort(
                                                            BetaManagedAgentsEffortLow.of(
                                                                BetaManagedAgentsEffortLow.Type.LOW
                                                            )
                                                        )
                                                        .inferenceGeo("inference_geo")
                                                        .speed(
                                                            BetaManagedAgentsModelConfig.Speed
                                                                .STANDARD
                                                        )
                                                        .build()
                                                )
                                                .name("Researcher")
                                                .addSkill(
                                                    BetaManagedAgentsAnthropicSkill.builder()
                                                        .skillId("xlsx")
                                                        .type(
                                                            BetaManagedAgentsAnthropicSkill.Type
                                                                .ANTHROPIC
                                                        )
                                                        .version("1")
                                                        .build()
                                                )
                                                .system(
                                                    "You are a research subagent that gathers and summarises sources for the coordinating agent."
                                                )
                                                .addTool(
                                                    BetaManagedAgentsAgentToolset20260401.builder()
                                                        .addConfig(
                                                            BetaManagedAgentsBashToolConfig
                                                                .builder()
                                                                .enabled(true)
                                                                .permissionPolicy(
                                                                    BetaManagedAgentsAlwaysAllowPolicy
                                                                        .of(
                                                                            BetaManagedAgentsAlwaysAllowPolicy
                                                                                .Type
                                                                                .ALWAYS_ALLOW
                                                                        )
                                                                )
                                                                .build()
                                                        )
                                                        .defaultConfig(
                                                            BetaManagedAgentsAgentToolsetDefaultConfig
                                                                .builder()
                                                                .enabled(true)
                                                                .permissionPolicy(
                                                                    BetaManagedAgentsAlwaysAskPolicy
                                                                        .of(
                                                                            BetaManagedAgentsAlwaysAskPolicy
                                                                                .Type
                                                                                .ALWAYS_ASK
                                                                        )
                                                                )
                                                                .build()
                                                        )
                                                        .type(
                                                            BetaManagedAgentsAgentToolset20260401
                                                                .Type
                                                                .AGENT_TOOLSET_20260401
                                                        )
                                                        .build()
                                                )
                                                .type(
                                                    BetaManagedAgentsSessionThreadAgent.Type.AGENT
                                                )
                                                .version(1)
                                                .build()
                                        )
                                        .type(
                                            BetaManagedAgentsSessionMultiagentCoordinator.Type
                                                .COORDINATOR
                                        )
                                        .build()
                                )
                                .name("My First Agent")
                                .addSkill(
                                    BetaManagedAgentsAnthropicSkill.builder()
                                        .skillId("xlsx")
                                        .type(BetaManagedAgentsAnthropicSkill.Type.ANTHROPIC)
                                        .version("1")
                                        .build()
                                )
                                .addSkill(
                                    BetaManagedAgentsCustomSkill.builder()
                                        .skillId("skill_011CZkZFNu9hAbo3jZPRgTlx")
                                        .type(BetaManagedAgentsCustomSkill.Type.CUSTOM)
                                        .version("2")
                                        .build()
                                )
                                .system(
                                    "You are a general-purpose agent that can research, write code, run commands, and use connected tools to complete the user's task end to end."
                                )
                                .addTool(
                                    BetaManagedAgentsAgentToolset20260401.builder()
                                        .addConfig(
                                            BetaManagedAgentsBashToolConfig.builder()
                                                .enabled(true)
                                                .permissionPolicy(
                                                    BetaManagedAgentsAlwaysAllowPolicy.of(
                                                        BetaManagedAgentsAlwaysAllowPolicy.Type
                                                            .ALWAYS_ALLOW
                                                    )
                                                )
                                                .build()
                                        )
                                        .defaultConfig(
                                            BetaManagedAgentsAgentToolsetDefaultConfig.builder()
                                                .enabled(true)
                                                .permissionPolicy(
                                                    BetaManagedAgentsAlwaysAskPolicy.of(
                                                        BetaManagedAgentsAlwaysAskPolicy.Type
                                                            .ALWAYS_ASK
                                                    )
                                                )
                                                .build()
                                        )
                                        .type(
                                            BetaManagedAgentsAgentToolset20260401.Type
                                                .AGENT_TOOLSET_20260401
                                        )
                                        .build()
                                )
                                .type(BetaManagedAgentsSessionAgent.Type.AGENT)
                                .version(1)
                                .build()
                        )
                        .archivedAt(null)
                        .budget(
                            BetaManagedAgentsBudgetLimit.builder()
                                .maxListCost(
                                    BetaMonetaryAmount.builder()
                                        .amount("2500")
                                        .currency(BetaCurrency.USD)
                                        .build()
                                )
                                .type(BetaManagedAgentsBudgetLimit.Type.LIMIT)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                        .environmentId("env_011CZkZ9X2dpNyB7HsEFoRfW")
                        .metadata(BetaManagedAgentsSession.Metadata.builder().build())
                        .addOutcomeEvaluation(
                            BetaManagedAgentsOutcomeEvaluationResource.builder()
                                .completedAt(OffsetDateTime.parse("2026-03-15T10:02:31Z"))
                                .description("Produce a 2-page summary as summary.md")
                                .explanation("All five sections present with inline citations.")
                                .iteration(0)
                                .outcomeId("outc_011CZkZRSw2kEfs6ncTVljxP")
                                .result("satisfied")
                                .type(
                                    BetaManagedAgentsOutcomeEvaluationResource.Type
                                        .OUTCOME_EVALUATION
                                )
                                .build()
                        )
                        .addResource(
                            BetaManagedAgentsFileResource.builder()
                                .id("sesrsc_011CZkZBJq5dWxk9fVLNcPht")
                                .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .fileId("file_011CNha8iCJcU1wXNR6q4V8w")
                                .mountPath("/uploads/receipt.pdf")
                                .type(BetaManagedAgentsFileResource.Type.FILE)
                                .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .build()
                        )
                        .addResource(
                            BetaManagedAgentsGitHubRepositoryResource.builder()
                                .id("sesrsc_011CZkZCKr6eXyl0gWMOdQiu")
                                .createdAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .mountPath("/workspace/example-repo")
                                .type(
                                    BetaManagedAgentsGitHubRepositoryResource.Type.GITHUB_REPOSITORY
                                )
                                .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                                .url("https://github.com/example-org/example-repo")
                                .branchCheckout("main")
                                .build()
                        )
                        .stats(
                            BetaManagedAgentsSessionStats.builder()
                                .activeSeconds(0.0)
                                .durationSeconds(0.0)
                                .build()
                        )
                        .status(BetaManagedAgentsSession.Status.IDLE)
                        .title("Order #1234 inquiry")
                        .type(BetaManagedAgentsSession.Type.SESSION)
                        .updatedAt(OffsetDateTime.parse("2026-03-15T10:00:00Z"))
                        .usage(
                            BetaManagedAgentsSessionUsage.builder()
                                .activeSeconds(0.0)
                                .cacheCreation(
                                    BetaManagedAgentsCacheCreationUsage.builder()
                                        .ephemeral1hInputTokens(0)
                                        .ephemeral5mInputTokens(0)
                                        .build()
                                )
                                .cacheReadInputTokens(0)
                                .inputTokens(0)
                                .listCost(
                                    BetaMonetaryAmount.builder()
                                        .amount("2500")
                                        .currency(BetaCurrency.USD)
                                        .build()
                                )
                                .outputTokens(0)
                                .serverToolUse(
                                    BetaManagedAgentsServerToolUsage.builder()
                                        .webFetchRequests(0)
                                        .webSearchRequests(3)
                                        .build()
                                )
                                .build()
                        )
                        .addVaultId("vlt_011CZkZDLs7fYzm1hXNPeRjv")
                        .deploymentId("deployment_id")
                        .build()
                )
                .nextPage("page_MjAyNS0wNS0xNFQwMDowMDowMFo=")
                .prevPage("page_MjAyNS0wNS0xM1QwMDowMDowMFo=")
                .build()

        val roundtrippedSessionListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(sessionListPageResponse),
                jacksonTypeRef<SessionListPageResponse>(),
            )

        assertThat(roundtrippedSessionListPageResponse).isEqualTo(sessionListPageResponse)
    }
}
