module Anthropic
  module Models
    type browser_state_change_tab_opened = { tab_id: String, type: :tab_opened }

    class BrowserStateChangeTabOpened < Anthropic::Internal::Type::BaseModel
      attr_accessor tab_id: String

      attr_accessor type: :tab_opened

      def initialize: (tab_id: String, ?type: :tab_opened) -> void

      def to_hash: -> { tab_id: String, type: :tab_opened }
    end
  end
end
