module Anthropic
  module Models
    type browser_state_change =
      Anthropic::BrowserStateChangeTabOpened
      | Anthropic::BrowserStateChangeDownloadStarted
      | Anthropic::BrowserStateChangeDownloadCompleted
      | Anthropic::BrowserStateChangeDownloadFailed

    module BrowserStateChange
      extend Anthropic::Internal::Type::Union

      type type_ =
        :tab_opened | :download_started | :download_completed | :download_failed

      module Type
        extend Anthropic::Internal::Type::Enum

        TAB_OPENED: :tab_opened
        DOWNLOAD_STARTED: :download_started
        DOWNLOAD_COMPLETED: :download_completed
        DOWNLOAD_FAILED: :download_failed

        def self?.values: -> ::Array[Anthropic::Models::BrowserStateChange::type_]
      end

      def self?.variants: -> ::Array[Anthropic::Models::browser_state_change]

      def self.new:
        (
          type: :tab_opened | "tab_opened",
          tab_id: String
        ) -> Anthropic::BrowserStateChangeTabOpened
        | (
          type: :download_started | "download_started",
          download_id: String,
          url: String
        ) -> Anthropic::BrowserStateChangeDownloadStarted
        | (
          type: :download_completed | "download_completed",
          download_id: String,
          url: String,
          ?path: String?,
          ?size_bytes: Integer?
        ) -> Anthropic::BrowserStateChangeDownloadCompleted
        | (
          type: :download_failed | "download_failed",
          download_id: String,
          url: String,
          ?error: String?
        ) -> Anthropic::BrowserStateChangeDownloadFailed
        | (
          type: Anthropic::Models::BrowserStateChange::type_ | String,
          ?tab_id: String,
          ?download_id: String,
          ?url: String,
          ?path: String?,
          ?size_bytes: Integer?,
          ?error: String?
        ) -> Anthropic::Models::browser_state_change
    end
  end
end
