module Anthropic
  module Models
    type browser_screenshot_config = { defer_loading: bool?, enabled: bool? }

    class BrowserScreenshotConfig < Anthropic::Internal::Type::BaseModel
      attr_accessor defer_loading: bool?

      attr_accessor enabled: bool?

      def initialize: (?defer_loading: bool?, ?enabled: bool?) -> void

      def to_hash: -> { defer_loading: bool?, enabled: bool? }
    end
  end
end
