module Anthropic
  module Models
    type citations_delta =
      {
        citation: Anthropic::Models::CitationsDelta::citation,
        type: :citations_delta
      }

    class CitationsDelta < Anthropic::Internal::Type::BaseModel
      attr_accessor citation: Anthropic::Models::CitationsDelta::citation

      attr_accessor type: :citations_delta

      def initialize: (
        citation: Anthropic::Models::CitationsDelta::citation,
        ?type: :citations_delta
      ) -> void

      def to_hash: -> {
        citation: Anthropic::Models::CitationsDelta::citation,
        type: :citations_delta
      }

      type citation =
        Anthropic::CitationCharLocation
        | Anthropic::CitationPageLocation
        | Anthropic::CitationContentBlockLocation
        | Anthropic::CitationsWebSearchResultLocation
        | Anthropic::CitationsSearchResultLocation

      module Citation
        extend Anthropic::Internal::Type::Union

        type type_ =
          :char_location
          | :page_location
          | :content_block_location
          | :web_search_result_location
          | :search_result_location

        module Type
          extend Anthropic::Internal::Type::Enum

          CHAR_LOCATION: :char_location
          PAGE_LOCATION: :page_location
          CONTENT_BLOCK_LOCATION: :content_block_location
          WEB_SEARCH_RESULT_LOCATION: :web_search_result_location
          SEARCH_RESULT_LOCATION: :search_result_location

          def self?.values: -> ::Array[Anthropic::Models::CitationsDelta::Citation::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::CitationsDelta::citation]

        def self.new:
          (
            type: :char_location | "char_location",
            cited_text: String,
            document_index: Integer,
            document_title: String?,
            end_char_index: Integer,
            file_id: String?,
            start_char_index: Integer
          ) -> Anthropic::CitationCharLocation
          | (
            type: :page_location | "page_location",
            cited_text: String,
            document_index: Integer,
            document_title: String?,
            end_page_number: Integer,
            file_id: String?,
            start_page_number: Integer
          ) -> Anthropic::CitationPageLocation
          | (
            type: :content_block_location | "content_block_location",
            cited_text: String,
            document_index: Integer,
            document_title: String?,
            end_block_index: Integer,
            file_id: String?,
            start_block_index: Integer
          ) -> Anthropic::CitationContentBlockLocation
          | (
            type: :web_search_result_location | "web_search_result_location",
            cited_text: String,
            encrypted_index: String,
            title: String?,
            url: String
          ) -> Anthropic::CitationsWebSearchResultLocation
          | (
            type: :search_result_location | "search_result_location",
            cited_text: String,
            end_block_index: Integer,
            search_result_index: Integer,
            source: String,
            start_block_index: Integer,
            title: String?
          ) -> Anthropic::CitationsSearchResultLocation
          | (
            type: Anthropic::Models::CitationsDelta::Citation::type_ | String,
            cited_text: String,
            ?document_index: Integer,
            ?document_title: String?,
            ?end_char_index: Integer,
            ?file_id: String?,
            ?start_char_index: Integer,
            ?end_page_number: Integer,
            ?start_page_number: Integer,
            ?end_block_index: Integer,
            ?start_block_index: Integer,
            ?encrypted_index: String,
            ?title: String?,
            ?url: String,
            ?search_result_index: Integer,
            ?source: String
          ) -> Anthropic::Models::CitationsDelta::citation
      end
    end
  end
end
