module Anthropic
  module Models
    type content_block_source_content =
      Anthropic::TextBlockParam | Anthropic::ImageBlockParam

    module ContentBlockSourceContent
      extend Anthropic::Internal::Type::Union

      type type_ = :text | :image

      module Type
        extend Anthropic::Internal::Type::Enum

        TEXT: :text
        IMAGE: :image

        def self?.values: -> ::Array[Anthropic::Models::ContentBlockSourceContent::type_]
      end

      def self?.variants: -> ::Array[Anthropic::Models::content_block_source_content]

      def self.new:
        (
          type: :text | "text",
          text: String,
          ?cache_control: Anthropic::CacheControlEphemeral?,
          ?citations: ::Array[Anthropic::Models::text_citation_param]?
        ) -> Anthropic::TextBlockParam
        | (
          type: :image | "image",
          source: Anthropic::Models::ImageBlockParam::source,
          ?cache_control: Anthropic::CacheControlEphemeral?,
          ?transformations: Anthropic::ImageTransformationsParam?
        ) -> Anthropic::ImageBlockParam
        | (
          type: Anthropic::Models::ContentBlockSourceContent::type_ | String,
          ?text: String,
          ?cache_control: Anthropic::CacheControlEphemeral?,
          ?citations: ::Array[Anthropic::Models::text_citation_param]?,
          ?source: Anthropic::Models::ImageBlockParam::source,
          ?transformations: Anthropic::ImageTransformationsParam?
        ) -> Anthropic::Models::content_block_source_content
    end
  end
end
