module Anthropic
  module Models
    type file_list_params =
      {
        ids: ::Array[String]?,
        limit: Integer,
        page: String?,
        workspace_id: String
      }
      & Anthropic::Internal::Type::request_parameters

    class FileListParams < Anthropic::Internal::Type::BaseModel
      extend Anthropic::Internal::Type::RequestParameters::Converter
      include Anthropic::Internal::Type::RequestParameters

      attr_accessor ids: ::Array[String]?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor page: String?

      attr_reader workspace_id: String?

      def workspace_id=: (String) -> String

      def initialize: (
        ?ids: ::Array[String]?,
        ?limit: Integer,
        ?page: String?,
        ?workspace_id: String,
        ?request_options: Anthropic::request_opts
      ) -> void

      def to_hash: -> {
        ids: ::Array[String]?,
        limit: Integer,
        page: String?,
        workspace_id: String,
        request_options: Anthropic::RequestOptions
      }
    end
  end
end
