module Anthropic
  module Models
    type file_image_source = { file_id: String, type: :file }

    class FileImageSource < Anthropic::Internal::Type::BaseModel
      attr_accessor file_id: String

      attr_accessor type: :file

      def initialize: (file_id: String, ?type: :file) -> void

      def to_hash: -> { file_id: String, type: :file }
    end
  end
end
