module Anthropic
  module Models
    type raw_message_stream_event =
      Anthropic::RawMessageStartEvent
      | Anthropic::RawMessageDeltaEvent
      | Anthropic::RawMessageStopEvent
      | Anthropic::RawContentBlockStartEvent
      | Anthropic::RawContentBlockDeltaEvent
      | Anthropic::RawContentBlockStopEvent

    module RawMessageStreamEvent
      extend Anthropic::Internal::Type::Union

      type type_ =
        :message_start
        | :message_delta
        | :message_stop
        | :content_block_start
        | :content_block_delta
        | :content_block_stop

      module Type
        extend Anthropic::Internal::Type::Enum

        MESSAGE_START: :message_start
        MESSAGE_DELTA: :message_delta
        MESSAGE_STOP: :message_stop
        CONTENT_BLOCK_START: :content_block_start
        CONTENT_BLOCK_DELTA: :content_block_delta
        CONTENT_BLOCK_STOP: :content_block_stop

        def self?.values: -> ::Array[Anthropic::Models::RawMessageStreamEvent::type_]
      end

      def self?.variants: -> ::Array[Anthropic::Models::raw_message_stream_event]

      def self.new:
        (
          type: :message_start | "message_start",
          message: Anthropic::Message
        ) -> Anthropic::RawMessageStartEvent
        | (
          type: :message_delta | "message_delta",
          delta: Anthropic::RawMessageDeltaEvent::Delta,
          usage: Anthropic::MessageDeltaUsage
        ) -> Anthropic::RawMessageDeltaEvent
        | (
          type: :message_stop | "message_stop"
        ) -> Anthropic::RawMessageStopEvent
        | (
          type: :content_block_start | "content_block_start",
          content_block: Anthropic::Models::RawContentBlockStartEvent::content_block,
          index: Integer
        ) -> Anthropic::RawContentBlockStartEvent
        | (
          type: :content_block_delta | "content_block_delta",
          delta: Anthropic::Models::raw_content_block_delta,
          index: Integer
        ) -> Anthropic::RawContentBlockDeltaEvent
        | (
          type: :content_block_stop | "content_block_stop",
          index: Integer
        ) -> Anthropic::RawContentBlockStopEvent
        | (
          type: Anthropic::Models::RawMessageStreamEvent::type_ | String,
          ?message: Anthropic::Message,
          ?delta: Anthropic::RawMessageDeltaEvent::Delta
          | Anthropic::Models::raw_content_block_delta,
          ?usage: Anthropic::MessageDeltaUsage,
          ?content_block: Anthropic::Models::RawContentBlockStartEvent::content_block,
          ?index: Integer
        ) -> Anthropic::Models::raw_message_stream_event
    end
  end
end
