module Anthropic
  module Models
    type text_citation_param =
      Anthropic::CitationCharLocationParam
      | Anthropic::CitationPageLocationParam
      | Anthropic::CitationContentBlockLocationParam
      | Anthropic::CitationWebSearchResultLocationParam
      | Anthropic::CitationSearchResultLocationParam

    module TextCitationParam
      extend Anthropic::Internal::Type::Union

      type type_ =
        :char_location
        | :page_location
        | :content_block_location
        | :web_search_result_location
        | :search_result_location

      module Type
        extend Anthropic::Internal::Type::Enum

        CHAR_LOCATION: :char_location
        PAGE_LOCATION: :page_location
        CONTENT_BLOCK_LOCATION: :content_block_location
        WEB_SEARCH_RESULT_LOCATION: :web_search_result_location
        SEARCH_RESULT_LOCATION: :search_result_location

        def self?.values: -> ::Array[Anthropic::Models::TextCitationParam::type_]
      end

      def self?.variants: -> ::Array[Anthropic::Models::text_citation_param]

      def self.new:
        (
          type: :char_location | "char_location",
          cited_text: String,
          document_index: Integer,
          document_title: String?,
          end_char_index: Integer,
          start_char_index: Integer
        ) -> Anthropic::CitationCharLocationParam
        | (
          type: :page_location | "page_location",
          cited_text: String,
          document_index: Integer,
          document_title: String?,
          end_page_number: Integer,
          start_page_number: Integer
        ) -> Anthropic::CitationPageLocationParam
        | (
          type: :content_block_location | "content_block_location",
          cited_text: String,
          document_index: Integer,
          document_title: String?,
          end_block_index: Integer,
          start_block_index: Integer
        ) -> Anthropic::CitationContentBlockLocationParam
        | (
          type: :web_search_result_location | "web_search_result_location",
          cited_text: String,
          encrypted_index: String,
          title: String?,
          url: String
        ) -> Anthropic::CitationWebSearchResultLocationParam
        | (
          type: :search_result_location | "search_result_location",
          cited_text: String,
          end_block_index: Integer,
          search_result_index: Integer,
          source: String,
          start_block_index: Integer,
          title: String?
        ) -> Anthropic::CitationSearchResultLocationParam
        | (
          type: Anthropic::Models::TextCitationParam::type_ | String,
          cited_text: String,
          ?document_index: Integer,
          ?document_title: String?,
          ?end_char_index: Integer,
          ?start_char_index: Integer,
          ?end_page_number: Integer,
          ?start_page_number: Integer,
          ?end_block_index: Integer,
          ?start_block_index: Integer,
          ?encrypted_index: String,
          ?title: String?,
          ?url: String,
          ?search_result_index: Integer,
          ?source: String
        ) -> Anthropic::Models::text_citation_param
    end
  end
end
