module Anthropic
  module Models
    type tool_choice =
      Anthropic::ToolChoiceAuto
      | Anthropic::ToolChoiceAny
      | Anthropic::ToolChoiceTool
      | Anthropic::ToolChoiceNone

    module ToolChoice
      extend Anthropic::Internal::Type::Union

      type type_ = :auto | :any | :tool | :none

      module Type
        extend Anthropic::Internal::Type::Enum

        AUTO: :auto
        ANY: :any
        TOOL: :tool
        NONE: :none

        def self?.values: -> ::Array[Anthropic::Models::ToolChoice::type_]
      end

      def self?.variants: -> ::Array[Anthropic::Models::tool_choice]

      def self.new:
        (
          type: :auto | "auto",
          ?disable_parallel_tool_use: bool
        ) -> Anthropic::ToolChoiceAuto
        | (
          type: :any | "any",
          ?disable_parallel_tool_use: bool
        ) -> Anthropic::ToolChoiceAny
        | (
          type: :tool | "tool",
          name: String,
          ?disable_parallel_tool_use: bool
        ) -> Anthropic::ToolChoiceTool
        | (type: :none | "none") -> Anthropic::ToolChoiceNone
        | (
          type: Anthropic::Models::ToolChoice::type_ | String,
          ?disable_parallel_tool_use: bool,
          ?name: String
        ) -> Anthropic::Models::tool_choice
    end
  end
end
