module Anthropic
  module Models
    type web_fetch_url_sources =
      {
        client_tool_results: Anthropic::Models::WebFetchURLSources::client_tool_results,
        server_tool_results: Anthropic::Models::WebFetchURLSources::server_tool_results,
        user_input: Anthropic::Models::WebFetchURLSources::user_input
      }

    class WebFetchURLSources < Anthropic::Internal::Type::BaseModel
      attr_reader client_tool_results: Anthropic::Models::WebFetchURLSources::client_tool_results?

      def client_tool_results=: (
        Anthropic::Models::WebFetchURLSources::client_tool_results
      ) -> Anthropic::Models::WebFetchURLSources::client_tool_results

      attr_reader server_tool_results: Anthropic::Models::WebFetchURLSources::server_tool_results?

      def server_tool_results=: (
        Anthropic::Models::WebFetchURLSources::server_tool_results
      ) -> Anthropic::Models::WebFetchURLSources::server_tool_results

      attr_reader user_input: Anthropic::Models::WebFetchURLSources::user_input?

      def user_input=: (
        Anthropic::Models::WebFetchURLSources::user_input
      ) -> Anthropic::Models::WebFetchURLSources::user_input

      def initialize: (
        ?client_tool_results: Anthropic::Models::WebFetchURLSources::client_tool_results,
        ?server_tool_results: Anthropic::Models::WebFetchURLSources::server_tool_results,
        ?user_input: Anthropic::Models::WebFetchURLSources::user_input
      ) -> void

      def to_hash: -> {
        client_tool_results: Anthropic::Models::WebFetchURLSources::client_tool_results,
        server_tool_results: Anthropic::Models::WebFetchURLSources::server_tool_results,
        user_input: Anthropic::Models::WebFetchURLSources::user_input
      }

      type client_tool_results =
        Anthropic::WebFetchURLSourceAll
        | Anthropic::WebFetchURLSourceNone
        | Anthropic::WebFetchURLSourceOnly
        | Anthropic::WebFetchURLSourceExcept

      module ClientToolResults
        extend Anthropic::Internal::Type::Union

        type type_ = :all | :none | :only | :except

        module Type
          extend Anthropic::Internal::Type::Enum

          ALL: :all
          NONE: :none
          ONLY: :only
          EXCEPT: :except

          def self?.values: -> ::Array[Anthropic::Models::WebFetchURLSources::ClientToolResults::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::WebFetchURLSources::client_tool_results]

        def self.new:
          (type: :all | "all") -> Anthropic::WebFetchURLSourceAll
          | (type: :none | "none") -> Anthropic::WebFetchURLSourceNone
          | (
            type: :only | "only",
            tools: ::Array[Anthropic::WebFetchURLSourceToolReference]
          ) -> Anthropic::WebFetchURLSourceOnly
          | (
            type: :except | "except",
            tools: ::Array[Anthropic::WebFetchURLSourceToolReference]
          ) -> Anthropic::WebFetchURLSourceExcept
          | (
            type: Anthropic::Models::WebFetchURLSources::ClientToolResults::type_
            | String,
            ?tools: ::Array[Anthropic::WebFetchURLSourceToolReference]
          ) -> Anthropic::Models::WebFetchURLSources::client_tool_results
      end

      type server_tool_results =
        Anthropic::WebFetchURLSourceAll
        | Anthropic::WebFetchURLSourceNone
        | Anthropic::WebFetchURLSourceOnly
        | Anthropic::WebFetchURLSourceExcept

      module ServerToolResults
        extend Anthropic::Internal::Type::Union

        type type_ = :all | :none | :only | :except

        module Type
          extend Anthropic::Internal::Type::Enum

          ALL: :all
          NONE: :none
          ONLY: :only
          EXCEPT: :except

          def self?.values: -> ::Array[Anthropic::Models::WebFetchURLSources::ServerToolResults::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::WebFetchURLSources::server_tool_results]

        def self.new:
          (type: :all | "all") -> Anthropic::WebFetchURLSourceAll
          | (type: :none | "none") -> Anthropic::WebFetchURLSourceNone
          | (
            type: :only | "only",
            tools: ::Array[Anthropic::WebFetchURLSourceToolReference]
          ) -> Anthropic::WebFetchURLSourceOnly
          | (
            type: :except | "except",
            tools: ::Array[Anthropic::WebFetchURLSourceToolReference]
          ) -> Anthropic::WebFetchURLSourceExcept
          | (
            type: Anthropic::Models::WebFetchURLSources::ServerToolResults::type_
            | String,
            ?tools: ::Array[Anthropic::WebFetchURLSourceToolReference]
          ) -> Anthropic::Models::WebFetchURLSources::server_tool_results
      end

      type user_input =
        Anthropic::WebFetchURLSourceAll | Anthropic::WebFetchURLSourceNone

      module UserInput
        extend Anthropic::Internal::Type::Union

        type type_ = :all | :none

        module Type
          extend Anthropic::Internal::Type::Enum

          ALL: :all
          NONE: :none

          def self?.values: -> ::Array[Anthropic::Models::WebFetchURLSources::UserInput::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::WebFetchURLSources::user_input]

        def self.new:
          (type: :all | "all") -> Anthropic::WebFetchURLSourceAll
          | (type: :none | "none") -> Anthropic::WebFetchURLSourceNone
          | (
            type: Anthropic::Models::WebFetchURLSources::UserInput::type_
            | String
          ) -> Anthropic::Models::WebFetchURLSources::user_input
      end
    end
  end
end
