# frozen_string_literal: true

module Anthropic
  module Models
    class ServerToolUseBlock < Anthropic::Internal::Type::BaseModel
      # @!attribute id
      #
      #   @return [String]
      required :id, String

      # @!attribute caller_
      #
      #   @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      required :caller_, union: -> { Anthropic::ServerToolUseBlock::Caller }, api_name: :caller

      # @!attribute input
      #
      #   @return [Object]
      required :input, Anthropic::Internal::Type::Unknown

      # @!attribute name
      #
      #   @return [Symbol, Anthropic::Models::ServerToolUseBlock::Name]
      required :name, enum: -> { Anthropic::ServerToolUseBlock::Name }

      # @!attribute type
      #
      #   @return [Symbol, :server_tool_use]
      required :type, const: :server_tool_use

      # @!method initialize(id:, caller_:, input:, name:, type: :server_tool_use)
      #   @param id [String]
      #   @param caller_ [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      #   @param input [Object]
      #   @param name [Symbol, Anthropic::Models::ServerToolUseBlock::Name]
      #   @param type [Symbol, :server_tool_use]

      # @see Anthropic::Models::ServerToolUseBlock#caller_
      module Caller
        extend Anthropic::Internal::Type::Union

        discriminator :type

        # Tool invocation directly from the model.
        variant :direct, -> { Anthropic::DirectCaller }

        # Tool invocation generated by a server-side tool.
        variant :code_execution_20250825, -> { Anthropic::ServerToolCaller }

        variant :code_execution_20260120, -> { Anthropic::ServerToolCaller20260120 }

        module Type
          extend Anthropic::Internal::Type::Enum

          DIRECT = :direct
          CODE_EXECUTION_20250825 = :code_execution_20250825
          CODE_EXECUTION_20260120 = :code_execution_20260120

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @!method self.variants
        #   @return [Array(Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120)]

        # Creates a new instance of the variant class whose `type` matches the given
        # value, passing the remaining arguments to its constructor.
        #
        # @param type [Symbol, Anthropic::Models::ServerToolUseBlock::Caller::Type, String]
        #
        # @param args [Hash{Symbol=>Object}] Attributes for the chosen variant.
        #
        #   @option args [String] :tool_id
        #
        # @raise [ArgumentError]
        # @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
        def self.new(type:, **args)
          case type.to_sym
          when :direct
            Anthropic::DirectCaller.new(**args)
          when :code_execution_20250825
            Anthropic::ServerToolCaller.new(**args)
          when :code_execution_20260120
            Anthropic::ServerToolCaller20260120.new(**args)
          else
            raise ArgumentError, "unknown type: #{type}"
          end
        end
      end

      # @see Anthropic::Models::ServerToolUseBlock#name
      module Name
        extend Anthropic::Internal::Type::Enum

        WEB_SEARCH = :web_search
        WEB_FETCH = :web_fetch
        CODE_EXECUTION = :code_execution
        BASH_CODE_EXECUTION = :bash_code_execution
        TEXT_EDITOR_CODE_EXECUTION = :text_editor_code_execution
        TOOL_SEARCH_TOOL_REGEX = :tool_search_tool_regex
        TOOL_SEARCH_TOOL_BM25 = :tool_search_tool_bm25

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
