# frozen_string_literal: true

module Anthropic
  module Models
    class ThinkingBlockParam < Anthropic::Internal::Type::BaseModel
      # @!attribute signature
      #   The `signature` value of this thinking block, exactly as returned by the API in
      #   a previous response. Used to verify that the block was generated by Claude.
      #
      #   Thinking blocks must be passed back unmodified and in their original order; a
      #   modified block results in a 400 `invalid_request_error`.
      #
      #   @return [String]
      required :signature, String

      # @!attribute thinking
      #   The `thinking` text of this block as returned by the API.
      #
      #   @return [String]
      required :thinking, String

      # @!attribute type
      #
      #   @return [Symbol, :thinking]
      required :type, const: :thinking

      # @!method initialize(signature:, thinking:, type: :thinking)
      #   Some parameter documentations has been truncated, see
      #   {Anthropic::Models::ThinkingBlockParam} for more details.
      #
      #   @param signature [String] The `signature` value of this thinking block, exactly as returned by the API in
      #
      #   @param thinking [String] The `thinking` text of this block as returned by the API.
      #
      #   @param type [Symbol, :thinking]
    end
  end
end
