# frozen_string_literal: true

module Anthropic
  module Models
    class ToolUseBlock < Anthropic::Internal::Type::BaseModel
      # @!attribute id
      #
      #   @return [String]
      required :id, String

      # @!attribute caller_
      #
      #   @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      required :caller_, union: -> { Anthropic::ToolUseBlock::Caller }, api_name: :caller

      # @!attribute input
      #
      #   @return [Object]
      required :input, Anthropic::Internal::Type::Unknown

      # @!attribute name
      #
      #   @return [String]
      required :name, String

      # @!attribute type
      #
      #   @return [Symbol, :tool_use]
      required :type, const: :tool_use

      # @!attribute toolset_name
      #   For a toolset member tool_use, the toolset family.
      #
      #   @return [String, nil]
      optional :toolset_name, String, nil?: true

      response_only do
        # @api public
        #
        # Parsed input data coerced to the tool's input schema model.
        # Only present when tools are defined using the InputSchema DSL.
        optional :parsed, Anthropic::Internal::Type::Unknown

        # @api private
        #
        # Internal buffer for accumulating partial JSON during streaming.
        # Used by streaming helpers to reconstruct complete JSON input from deltas.
        optional :_json_buf, String
      end

      # @!method initialize(id:, caller_:, input:, name:, toolset_name: nil, type: :tool_use)
      #   @param id [String]
      #
      #   @param caller_ [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      #
      #   @param input [Object]
      #
      #   @param name [String]
      #
      #   @param toolset_name [String, nil] For a toolset member tool_use, the toolset family.
      #
      #   @param type [Symbol, :tool_use]

      # @see Anthropic::Models::ToolUseBlock#caller_
      module Caller
        extend Anthropic::Internal::Type::Union

        discriminator :type

        # Tool invocation directly from the model.
        variant :direct, -> { Anthropic::DirectCaller }

        # Tool invocation generated by a server-side tool.
        variant :code_execution_20250825, -> { Anthropic::ServerToolCaller }

        variant :code_execution_20260120, -> { Anthropic::ServerToolCaller20260120 }

        module Type
          extend Anthropic::Internal::Type::Enum

          DIRECT = :direct
          CODE_EXECUTION_20250825 = :code_execution_20250825
          CODE_EXECUTION_20260120 = :code_execution_20260120

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @!method self.variants
        #   @return [Array(Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120)]

        # Creates a new instance of the variant class whose `type` matches the given
        # value, passing the remaining arguments to its constructor.
        #
        # @param type [Symbol, Anthropic::Models::ToolUseBlock::Caller::Type, String]
        #
        # @param args [Hash{Symbol=>Object}] Attributes for the chosen variant.
        #
        #   @option args [String] :tool_id
        #
        # @raise [ArgumentError]
        # @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
        def self.new(type:, **args)
          case type.to_sym
          when :direct
            Anthropic::DirectCaller.new(**args)
          when :code_execution_20250825
            Anthropic::ServerToolCaller.new(**args)
          when :code_execution_20260120
            Anthropic::ServerToolCaller20260120.new(**args)
          else
            raise ArgumentError, "unknown type: #{type}"
          end
        end
      end
    end
  end
end
