# frozen_string_literal: true

module Anthropic
  module Models
    class ToolUseBlockParam < Anthropic::Internal::Type::BaseModel
      # @!attribute id
      #
      #   @return [String]
      required :id, String

      # @!attribute input
      #
      #   @return [Hash{Symbol=>Object}]
      required :input, Anthropic::Internal::Type::HashOf[Anthropic::Internal::Type::Unknown]

      # @!attribute name
      #
      #   @return [String]
      required :name, String

      # @!attribute type
      #
      #   @return [Symbol, :tool_use]
      required :type, const: :tool_use

      # @!attribute cache_control
      #   Create a cache control breakpoint at this content block.
      #
      #   @return [Anthropic::Models::CacheControlEphemeral, nil]
      optional :cache_control, -> { Anthropic::CacheControlEphemeral }, nil?: true

      # @!attribute caller_
      #
      #   @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120, nil]
      optional :caller_, union: -> { Anthropic::ToolUseBlockParam::Caller }, api_name: :caller

      # @!attribute toolset_name
      #   For a toolset member tool_use, the toolset family this member belongs to.
      #
      #   @return [String, nil]
      optional :toolset_name, String, nil?: true

      # @!method initialize(id:, input:, name:, cache_control: nil, caller_: nil, toolset_name: nil, type: :tool_use)
      #   @param id [String]
      #
      #   @param input [Hash{Symbol=>Object}]
      #
      #   @param name [String]
      #
      #   @param cache_control [Anthropic::Models::CacheControlEphemeral, nil] Create a cache control breakpoint at this content block.
      #
      #   @param caller_ [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      #
      #   @param toolset_name [String, nil] For a toolset member tool_use, the toolset family this member belongs to.
      #
      #   @param type [Symbol, :tool_use]

      # @see Anthropic::Models::ToolUseBlockParam#caller_
      module Caller
        extend Anthropic::Internal::Type::Union

        discriminator :type

        # Tool invocation directly from the model.
        variant :direct, -> { Anthropic::DirectCaller }

        # Tool invocation generated by a server-side tool.
        variant :code_execution_20250825, -> { Anthropic::ServerToolCaller }

        variant :code_execution_20260120, -> { Anthropic::ServerToolCaller20260120 }

        module Type
          extend Anthropic::Internal::Type::Enum

          DIRECT = :direct
          CODE_EXECUTION_20250825 = :code_execution_20250825
          CODE_EXECUTION_20260120 = :code_execution_20260120

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @!method self.variants
        #   @return [Array(Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120)]

        # Creates a new instance of the variant class whose `type` matches the given
        # value, passing the remaining arguments to its constructor.
        #
        # @param type [Symbol, Anthropic::Models::ToolUseBlockParam::Caller::Type, String]
        #
        # @param args [Hash{Symbol=>Object}] Attributes for the chosen variant.
        #
        #   @option args [String] :tool_id
        #
        # @raise [ArgumentError]
        # @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
        def self.new(type:, **args)
          case type.to_sym
          when :direct
            Anthropic::DirectCaller.new(**args)
          when :code_execution_20250825
            Anthropic::ServerToolCaller.new(**args)
          when :code_execution_20260120
            Anthropic::ServerToolCaller20260120.new(**args)
          else
            raise ArgumentError, "unknown type: #{type}"
          end
        end
      end
    end
  end
end
