module Anthropic
  module Models
    module Beta
      module Organization
        module Workspaces
          type service_account_update_params =
            {
              workspace_id: String,
              service_account_id: String,
              workspace_role: Anthropic::Models::Beta::Organization::beta_no_billing_workspace_role,
              betas: ::Array[Anthropic::Models::anthropic_beta]
            }
            & Anthropic::Internal::Type::request_parameters

          class ServiceAccountUpdateParams < Anthropic::Internal::Type::BaseModel
            extend Anthropic::Internal::Type::RequestParameters::Converter
            include Anthropic::Internal::Type::RequestParameters

            attr_accessor workspace_id: String

            attr_accessor service_account_id: String

            attr_accessor workspace_role: Anthropic::Models::Beta::Organization::beta_no_billing_workspace_role

            attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

            def betas=: (
              ::Array[Anthropic::Models::anthropic_beta]
            ) -> ::Array[Anthropic::Models::anthropic_beta]

            def initialize: (
              workspace_id: String,
              service_account_id: String,
              workspace_role: Anthropic::Models::Beta::Organization::beta_no_billing_workspace_role,
              ?betas: ::Array[Anthropic::Models::anthropic_beta],
              ?request_options: Anthropic::request_opts
            ) -> void

            def to_hash: -> {
              workspace_id: String,
              service_account_id: String,
              workspace_role: Anthropic::Models::Beta::Organization::beta_no_billing_workspace_role,
              betas: ::Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::RequestOptions
            }
          end
        end
      end
    end
  end
end
