module Anthropic
  module Models
    module Beta
      module MemoryStores
        type beta_managed_agents_actor =
          Anthropic::Beta::MemoryStores::BetaManagedAgentsSessionActor
          | Anthropic::Beta::MemoryStores::BetaManagedAgentsAPIActor
          | Anthropic::Beta::MemoryStores::BetaManagedAgentsUserActor
          | Anthropic::Beta::MemoryStores::BetaManagedAgentsServiceAccountActor

        module BetaManagedAgentsActor
          extend Anthropic::Internal::Type::Union

          type type_ =
            :session_actor | :api_actor | :user_actor | :service_account_actor

          module Type
            extend Anthropic::Internal::Type::Enum

            SESSION_ACTOR: :session_actor
            API_ACTOR: :api_actor
            USER_ACTOR: :user_actor
            SERVICE_ACCOUNT_ACTOR: :service_account_actor

            def self?.values: -> ::Array[Anthropic::Models::Beta::MemoryStores::BetaManagedAgentsActor::type_]
          end

          def self?.variants: -> ::Array[Anthropic::Models::Beta::MemoryStores::beta_managed_agents_actor]

          def self.new:
            (
              type: :session_actor | "session_actor",
              session_id: String
            ) -> Anthropic::Beta::MemoryStores::BetaManagedAgentsSessionActor
            | (
              type: :api_actor | "api_actor",
              api_key_id: String
            ) -> Anthropic::Beta::MemoryStores::BetaManagedAgentsAPIActor
            | (
              type: :user_actor | "user_actor",
              user_id: String
            ) -> Anthropic::Beta::MemoryStores::BetaManagedAgentsUserActor
            | (
              type: :service_account_actor | "service_account_actor",
              service_account_id: String
            ) -> Anthropic::Beta::MemoryStores::BetaManagedAgentsServiceAccountActor
            | (
              type: Anthropic::Models::Beta::MemoryStores::BetaManagedAgentsActor::type_
              | String,
              ?session_id: String,
              ?api_key_id: String,
              ?user_id: String,
              ?service_account_id: String
            ) -> Anthropic::Models::Beta::MemoryStores::beta_managed_agents_actor
        end
      end
    end
  end
end
