module Anthropic
  module Models
    module Beta
      module MemoryStores
        type beta_managed_agents_service_account_actor =
          { service_account_id: String, type: :service_account_actor }

        class BetaManagedAgentsServiceAccountActor < Anthropic::Internal::Type::BaseModel
          attr_accessor service_account_id: String

          attr_accessor type: :service_account_actor

          def initialize: (
            service_account_id: String,
            ?type: :service_account_actor
          ) -> void

          def to_hash: -> {
            service_account_id: String,
            type: :service_account_actor
          }
        end
      end
    end
  end
end
