# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      module Sessions
        class BetaManagedAgentsSpanModelUsage < Anthropic::Internal::Type::BaseModel
          # @!attribute cache_creation_input_tokens
          #   Tokens used to create prompt cache in this request.
          #
          #   @return [Integer]
          required :cache_creation_input_tokens, Integer

          # @!attribute cache_read_input_tokens
          #   Tokens read from prompt cache in this request.
          #
          #   @return [Integer]
          required :cache_read_input_tokens, Integer

          # @!attribute input_tokens
          #   Input tokens consumed by this request.
          #
          #   @return [Integer]
          required :input_tokens, Integer

          # @!attribute output_tokens
          #   Output tokens generated by this request.
          #
          #   @return [Integer]
          required :output_tokens, Integer

          # @!attribute speed
          #   Inference speed mode. `fast` provides significantly faster output token
          #   generation at premium pricing. Not all models support `fast`; invalid
          #   combinations are rejected at create time.
          #
          #   @return [Symbol, Anthropic::Models::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed, nil]
          optional :speed,
                   enum: -> { Anthropic::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed },
                   nil?: true

          # @!method initialize(cache_creation_input_tokens:, cache_read_input_tokens:, input_tokens:, output_tokens:, speed: nil)
          #   Token usage for a single model request.
          #
          #   Some parameter documentations has been truncated, see
          #   {Anthropic::Models::Beta::Sessions::BetaManagedAgentsSpanModelUsage} for more
          #   details.
          #
          #   @param cache_creation_input_tokens [Integer] Tokens used to create prompt cache in this request.
          #
          #   @param cache_read_input_tokens [Integer] Tokens read from prompt cache in this request.
          #
          #   @param input_tokens [Integer] Input tokens consumed by this request.
          #
          #   @param output_tokens [Integer] Output tokens generated by this request.
          #
          #   @param speed [Symbol, Anthropic::Models::Beta::Sessions::BetaManagedAgentsSpanModelUsage::Speed, nil] Inference speed mode. `fast` provides significantly faster output token generati

          # Inference speed mode. `fast` provides significantly faster output token
          # generation at premium pricing. Not all models support `fast`; invalid
          # combinations are rejected at create time.
          #
          # @see Anthropic::Models::Beta::Sessions::BetaManagedAgentsSpanModelUsage#speed
          module Speed
            extend Anthropic::Internal::Type::Enum

            STANDARD = :standard
            FAST = :fast

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end
  end
end
