using System.Net.Http.Headers;
using Azure.Core;

namespace Anthropic.Foundry;

/// <summary>
/// Provides access to the Azure Foundry API though the usage of the environmental authentication generated by the <see cref="DefaultAnthropicFoundryCredentials.FromEnv"/> method.
/// </summary>
public class AnthropicFoundryIdentityTokenCredentials : IAnthropicFoundryCredentials
{
    private readonly TokenCredential _tokenCredential;
    private readonly string[] _scopes = ["https://ai.azure.com/.default"];

    public string ResourceName { get; }

    /// <summary>
    /// Creates a new instance of the <see cref="AnthropicFoundryIdentityTokenCredentials"/>.
    /// </summary>
    /// <param name="tokenCredential">The credential provider. Use any specialization of <see cref="TokenCredential"/> to get your access token in supported environments.</param>
    /// <param name="resourceName">The service resource subdomain name to use in the anthropic azure endpoint</param>
    /// <param name="scopes">The scopes to use when requesting the token. If null, defaults to "https://ai.azure.com/.default"</param>
    public AnthropicFoundryIdentityTokenCredentials(
        TokenCredential tokenCredential,
        string resourceName,
        string[]? scopes = null
    )
    {
        ResourceName = resourceName ?? throw new ArgumentNullException(nameof(resourceName));
        _tokenCredential =
            tokenCredential ?? throw new ArgumentNullException(nameof(tokenCredential));
        _scopes = scopes ?? _scopes;
    }

    public void Apply(HttpRequestMessage requestMessage)
    {
        requestMessage.Headers.Authorization = new AuthenticationHeaderValue(
            "bearer",
            this._tokenCredential.GetToken(
                new TokenRequestContext(this._scopes),
                CancellationToken.None
            ).Token
        );
    }
}
